//! Fail-closed authority for bounded sparse-memory Poseidon2 provider shards.
//!
//! This is deliberately separate from R-008's guest-I/O provider.  It plans
//! the base `poseidon2` relation generated by
//! `HashComponent(.poseidon2, .narrow_memory)`: one canonical ordered call
//! authority is partitioned into contiguous shards, each with the exact
//! 445-main/8-interaction-column geometry of `poseidon2_air`.
//!
//! This tranche is authority and algebra only.  It does not activate a proof
//! path.  In particular, the ordered call commitment is not yet AIR-proved,
//! no caller+N transcript/manifest or joint interaction PoW is wired, no
//! bounded two-pass PCS owner exists, and recursion does not verify the shard
//! artifacts.  Those gaps remain explicit constants below.

const std = @import("std");
const m31 = @import("stwo_core").fields.m31;
const QM31 = @import("stwo_core").fields.qm31.QM31;
const poseidon2_air = @import("../../air/memory_commitment/poseidon2_air.zig");
const aggregation_hash = @import("../../aggregation/hash.zig");
const residency_shard_plan = @import("stwo_prover_engine").pcs.residency_shard_plan;

pub const RESEARCH_ONLY = true;
pub const ACTIVATES_PRODUCTION_PROOF = false;
pub const ORDERED_CALL_COMMITMENT_IS_AIR_PROVED = false;
pub const CALLER_N_MANIFEST_IMPLEMENTED = false;
pub const JOINT_INTERACTION_POW_IMPLEMENTED = false;
pub const TWO_PASS_BOUNDED_PCS_IMPLEMENTED = false;
pub const RECURSIVE_VERIFICATION_IMPLEMENTED = false;

pub const format_version: u32 = 1;
pub const minimum_shard_log_size: u32 = 4;
pub const maximum_shard_log_size: u32 = 20;
pub const main_column_count: u16 = poseidon2_air.N_MAIN_COLUMNS;
pub const interaction_column_count: u16 = poseidon2_air.N_INTERACTION_COLUMNS;

comptime {
    if (main_column_count != 445 or interaction_column_count != 8)
        @compileError("narrow-memory Poseidon2 shard geometry drifted");
}

pub const Digest = aggregation_hash.Digest;

pub const Mode = enum(u8) {
    narrow_memory = 1,
};

/// Exact request/result projection from the generic PCS residency planner.
/// The provider authority never selects a size with a second implementation.
pub const ResidencyPlanningAuthorityV1 = struct {
    request: residency_shard_plan.Request,
    result: residency_shard_plan.Plan,

    pub fn canonical(
        request: residency_shard_plan.Request,
    ) !ResidencyPlanningAuthorityV1 {
        const result = try residency_shard_plan.create(request);
        if (request.column_count != main_column_count or
            result.shard_log_size < minimum_shard_log_size or
            result.shard_log_size > maximum_shard_log_size)
        {
            return error.InvalidProviderResidencyPolicy;
        }
        const authority = ResidencyPlanningAuthorityV1{
            .request = request,
            .result = result,
        };
        try authority.validate();
        return authority;
    }

    pub fn validate(self: ResidencyPlanningAuthorityV1) !void {
        try self.result.validateAgainst(self.request);
        if (self.request.column_count != main_column_count or
            self.result.shard_log_size < minimum_shard_log_size or
            self.result.shard_log_size > maximum_shard_log_size)
        {
            return error.InvalidProviderResidencyPolicy;
        }
        if (!aggregation_hash.eql(
            self.result.request_identity,
            self.request.identity(),
        )) return error.ResidencyRequestIdentityMismatch;
        if (!aggregation_hash.eql(
            self.result.plan_identity,
            residency_shard_plan.planIdentity(&self.result),
        )) return error.ResidencyPlanIdentityMismatch;
    }
};

pub const ProviderShardDescriptorV1 = struct {
    format: u32,
    session: Digest,
    shard_index: u32,
    shard_count: u32,
    first_call: u64,
    call_count: u32,
    global_call_list_commitment: Digest,
    shard_call_list_commitment: Digest,
    mode: Mode,
    expected_log_size: u32,
    main_columns: u16,
    interaction_columns: u16,
    identity: Digest,

    fn canonical(
        session: Digest,
        shard_index: u32,
        shard_count: u32,
        first_call: u64,
        calls: []const poseidon2_air.Call,
        global_call_list_commitment: Digest,
    ) !ProviderShardDescriptorV1 {
        const call_count = std.math.cast(u32, calls.len) orelse
            return error.CallCountOutOfRange;
        if (call_count == 0) return error.EmptyProviderShard;
        var result = ProviderShardDescriptorV1{
            .format = format_version,
            .session = session,
            .shard_index = shard_index,
            .shard_count = shard_count,
            .first_call = first_call,
            .call_count = call_count,
            .global_call_list_commitment = global_call_list_commitment,
            .shard_call_list_commitment = try orderedShardCallCommitment(
                first_call,
                calls,
            ),
            .mode = .narrow_memory,
            .expected_log_size = expectedLogSize(call_count),
            .main_columns = main_column_count,
            .interaction_columns = interaction_column_count,
            .identity = undefined,
        };
        result.identity = descriptorIdentity(result);
        return result;
    }
};

pub const ProviderShardPlanV1 = struct {
    format: u32,
    session: Digest,
    total_call_count: u64,
    shard_count: u32,
    residency: ResidencyPlanningAuthorityV1,
    call_list_commitment: Digest,
    shards: []ProviderShardDescriptorV1,
    identity: Digest,

    pub fn create(
        allocator: std.mem.Allocator,
        session: Digest,
        calls: []const poseidon2_air.Call,
        residency_request: residency_shard_plan.Request,
    ) !ProviderShardPlanV1 {
        if (aggregation_hash.isZero(session)) return error.ZeroSession;
        if (calls.len == 0) return error.EmptyCallAuthority;
        try validateNarrowCalls(calls);

        const total_call_count = std.math.cast(u64, calls.len) orelse
            return error.CallCountOutOfRange;
        if (residency_request.logical_row_count != total_call_count)
            return error.ResidencyCallCountMismatch;
        const residency = try ResidencyPlanningAuthorityV1.canonical(
            residency_request,
        );
        const capacity = std.math.cast(
            usize,
            residency.result.shard_capacity,
        ) orelse return error.CallCountOutOfRange;
        const shard_count_usize = std.math.cast(
            usize,
            residency.result.shard_count,
        ) orelse return error.ShardCountOutOfRange;
        const shard_count = std.math.cast(u32, shard_count_usize) orelse
            return error.ShardCountOutOfRange;
        const global_commitment = try orderedCallListCommitment(calls);
        const shards = try allocator.alloc(
            ProviderShardDescriptorV1,
            shard_count_usize,
        );
        errdefer allocator.free(shards);

        for (shards, 0..) |*shard, index| {
            const first = try std.math.mul(usize, index, capacity);
            const end = @min(calls.len, try std.math.add(usize, first, capacity));
            shard.* = try ProviderShardDescriptorV1.canonical(
                session,
                @intCast(index),
                shard_count,
                @intCast(first),
                calls[first..end],
                global_commitment,
            );
        }

        var result = ProviderShardPlanV1{
            .format = format_version,
            .session = session,
            .total_call_count = total_call_count,
            .shard_count = shard_count,
            .residency = residency,
            .call_list_commitment = global_commitment,
            .shards = shards,
            .identity = undefined,
        };
        result.identity = planIdentity(&result);
        try result.validate(calls);
        return result;
    }

    pub fn deinit(self: *ProviderShardPlanV1, allocator: std.mem.Allocator) void {
        allocator.free(self.shards);
        self.* = undefined;
    }

    /// Reopens the complete ordered source authority.  No shard-provided
    /// offset, count, commitment, geometry, or identity is trusted.
    pub fn validate(
        self: *const ProviderShardPlanV1,
        calls: []const poseidon2_air.Call,
    ) !void {
        if (self.format != format_version) return error.InvalidFormatVersion;
        if (aggregation_hash.isZero(self.session)) return error.ZeroSession;
        try self.residency.validate();
        if (calls.len == 0) return error.EmptyCallAuthority;
        try validateNarrowCalls(calls);
        if (self.total_call_count != calls.len)
            return error.TotalCallCountMismatch;
        if (self.residency.request.logical_row_count != self.total_call_count)
            return error.ResidencyCallCountMismatch;

        const capacity = std.math.cast(
            usize,
            self.residency.result.shard_capacity,
        ) orelse return error.CallCountOutOfRange;
        const expected_shard_count = std.math.cast(
            usize,
            self.residency.result.shard_count,
        ) orelse return error.ShardCountOutOfRange;
        if (self.shard_count != expected_shard_count or
            self.shards.len != expected_shard_count)
        {
            return error.ShardCountMismatch;
        }

        const global_commitment = try orderedCallListCommitment(calls);
        if (!aggregation_hash.eql(
            self.call_list_commitment,
            global_commitment,
        )) return error.GlobalCallCommitmentMismatch;

        var next_first: usize = 0;
        for (self.shards, 0..) |shard, index| {
            if (shard.format != format_version)
                return error.InvalidFormatVersion;
            if (!aggregation_hash.eql(shard.session, self.session))
                return error.SessionMismatch;
            if (shard.shard_index != index or
                shard.shard_count != self.shard_count)
            {
                return error.NonCanonicalShardPosition;
            }
            if (shard.first_call != next_first)
                return error.NonContiguousShardCoverage;
            const remaining = calls.len - next_first;
            const expected_count = @min(remaining, capacity);
            if (shard.call_count != expected_count or expected_count == 0)
                return error.NonCanonicalShardSize;
            const end = std.math.add(
                usize,
                next_first,
                expected_count,
            ) catch return error.CallCountOutOfRange;
            if (!aggregation_hash.eql(
                shard.global_call_list_commitment,
                global_commitment,
            )) return error.GlobalCallCommitmentMismatch;
            const shard_commitment = try orderedShardCallCommitment(
                shard.first_call,
                calls[next_first..end],
            );
            if (!aggregation_hash.eql(
                shard.shard_call_list_commitment,
                shard_commitment,
            )) return error.ShardCallCommitmentMismatch;
            if (shard.mode != .narrow_memory or
                shard.main_columns != main_column_count or
                shard.interaction_columns != interaction_column_count)
            {
                return error.ProviderGeometryMismatch;
            }
            if (shard.expected_log_size != expectedLogSize(shard.call_count) or
                shard.expected_log_size > self.residency.result.shard_log_size)
            {
                return error.ProviderLogSizeMismatch;
            }
            if (!aggregation_hash.eql(shard.identity, descriptorIdentity(shard)))
                return error.ShardIdentityMismatch;
            next_first = end;
        }
        if (next_first != calls.len) return error.IncompleteShardCoverage;
        if (!aggregation_hash.eql(self.identity, planIdentity(self)))
            return error.PlanIdentityMismatch;
    }
};

/// Process-local proof that one complete plan/call corpus has passed the
/// expensive canonical validation. The token owns exact descriptor identity
/// snapshots and is pointer-closed; it has deliberately no codec. Internal
/// shard work can therefore recheck one descriptor in O(1) without walking or
/// hashing the complete call list again.
pub const OwnedValidatedPlanCallAuthorityV1 = struct {
    pub const WorkReceiptV1 = struct {
        full_corpus_validations: u64,
        fast_pointer_checks: u64,

        pub fn validate(self: WorkReceiptV1) !void {
            if (self.full_corpus_validations != 1)
                return error.InvalidValidatedProviderPlanCallWorkReceipt;
        }
    };

    const CountersV1 = struct {
        fast_pointer_checks: std.atomic.Value(u64) = .init(0),

        fn recordFastCheck(self: *const CountersV1) void {
            const mutable = @constCast(self);
            _ = mutable.fast_pointer_checks.fetchAdd(1, .monotonic);
        }

        fn snapshot(self: *const CountersV1) WorkReceiptV1 {
            return .{
                .full_corpus_validations = 1,
                .fast_pointer_checks = self.fast_pointer_checks.load(.acquire),
            };
        }
    };

    allocator: std.mem.Allocator,
    plan: *const ProviderShardPlanV1,
    calls_ptr: [*]const poseidon2_air.Call,
    calls_len: usize,
    shards_ptr: [*]const ProviderShardDescriptorV1,
    descriptor_identities: []Digest,
    plan_identity: Digest,
    call_list_commitment: Digest,
    session: Digest,
    counters: CountersV1 = .{},

    pub fn init(
        allocator: std.mem.Allocator,
        plan: *const ProviderShardPlanV1,
        calls: []const poseidon2_air.Call,
    ) !OwnedValidatedPlanCallAuthorityV1 {
        try plan.validate(calls);
        const identities = try allocator.alloc(Digest, plan.shards.len);
        errdefer allocator.free(identities);
        for (identities, plan.shards) |*destination, descriptor|
            destination.* = descriptor.identity;
        var result = OwnedValidatedPlanCallAuthorityV1{
            .allocator = allocator,
            .plan = plan,
            .calls_ptr = calls.ptr,
            .calls_len = calls.len,
            .shards_ptr = plan.shards.ptr,
            .descriptor_identities = identities,
            .plan_identity = plan.identity,
            .call_list_commitment = plan.call_list_commitment,
            .session = plan.session,
        };
        try result.validateBorrowedCore(plan, calls);
        return result;
    }

    pub fn validateBorrowed(
        self: *const OwnedValidatedPlanCallAuthorityV1,
        plan: *const ProviderShardPlanV1,
        calls: []const poseidon2_air.Call,
    ) !void {
        self.counters.recordFastCheck();
        return self.validateBorrowedCore(plan, calls);
    }

    fn validateBorrowedCore(
        self: *const OwnedValidatedPlanCallAuthorityV1,
        plan: *const ProviderShardPlanV1,
        calls: []const poseidon2_air.Call,
    ) !void {
        if (self.plan != plan or self.calls_ptr != calls.ptr or
            self.calls_len != calls.len or self.shards_ptr != plan.shards.ptr or
            self.descriptor_identities.len != plan.shards.len or
            self.calls_len == 0 or self.descriptor_identities.len == 0 or
            plan.format != format_version or plan.total_call_count != calls.len or
            plan.shard_count != plan.shards.len or
            !aggregation_hash.eql(self.plan_identity, plan.identity) or
            !aggregation_hash.eql(self.call_list_commitment, plan.call_list_commitment) or
            !aggregation_hash.eql(self.session, plan.session))
        {
            return error.InvalidValidatedProviderPlanCallAuthority;
        }
    }

    pub fn admittedShard(
        self: *const OwnedValidatedPlanCallAuthorityV1,
        plan: *const ProviderShardPlanV1,
        calls: []const poseidon2_air.Call,
        shard_index: u32,
    ) ![]const poseidon2_air.Call {
        try self.validateBorrowed(plan, calls);
        const index = std.math.cast(usize, shard_index) orelse
            return error.ShardIndexOutOfRange;
        if (index >= plan.shards.len) return error.ShardIndexOutOfRange;
        const descriptor = plan.shards[index];
        const capacity = std.math.cast(
            usize,
            plan.residency.result.shard_capacity,
        ) orelse return error.CallCountOutOfRange;
        const expected_first = std.math.mul(usize, index, capacity) catch
            return error.CallCountOutOfRange;
        if (expected_first >= calls.len) return error.CallCountOutOfRange;
        const expected_count = @min(calls.len - expected_first, capacity);
        const end = std.math.add(usize, expected_first, expected_count) catch
            return error.CallCountOutOfRange;
        if (!aggregation_hash.eql(
            descriptor.identity,
            self.descriptor_identities[index],
        ) or !aggregation_hash.eql(
            descriptor.identity,
            descriptorIdentity(descriptor),
        ) or descriptor.format != format_version or
            !aggregation_hash.eql(descriptor.session, self.session) or
            descriptor.shard_index != index or
            descriptor.shard_count != plan.shard_count or
            descriptor.first_call != expected_first or
            descriptor.call_count != expected_count or
            !aggregation_hash.eql(
                descriptor.global_call_list_commitment,
                self.call_list_commitment,
            ) or descriptor.mode != .narrow_memory or
            descriptor.main_columns != main_column_count or
            descriptor.interaction_columns != interaction_column_count or
            descriptor.expected_log_size != expectedLogSize(descriptor.call_count) or
            descriptor.expected_log_size > plan.residency.result.shard_log_size)
        {
            return error.InvalidValidatedProviderShardAuthority;
        }
        return calls[expected_first..end];
    }

    pub fn workReceipt(
        self: *const OwnedValidatedPlanCallAuthorityV1,
    ) WorkReceiptV1 {
        return self.counters.snapshot();
    }

    pub fn deinit(self: *OwnedValidatedPlanCallAuthorityV1) void {
        self.allocator.free(self.descriptor_identities);
        self.* = undefined;
    }
};

/// Exact relation pair shared by the core caller and all provider shards.
/// The session is part of its identity, preventing cross-session claim reuse.
pub const PoseidonRelationContextV1 = struct {
    session: Digest,
    z: QM31,
    alpha: QM31,
    identity: Digest,

    pub fn canonical(session: Digest, z: QM31, alpha: QM31) !@This() {
        if (aggregation_hash.isZero(session)) return error.ZeroSession;
        var result = @This(){
            .session = session,
            .z = z,
            .alpha = alpha,
            .identity = undefined,
        };
        result.identity = relationContextIdentity(result);
        return result;
    }

    pub fn validate(self: @This(), expected_session: Digest) !void {
        if (!aggregation_hash.eql(self.session, expected_session))
            return error.SessionMismatch;
        if (!aggregation_hash.eql(self.identity, relationContextIdentity(self)))
            return error.RelationContextIdentityMismatch;
    }
};

pub const CorePoseidonClaimV1 = struct {
    plan_identity: Digest,
    relation_context_identity: Digest,
    claim: QM31,
};

pub const ProviderShardClaimV1 = struct {
    plan_identity: Digest,
    descriptor_identity: Digest,
    shard_index: u32,
    relation_context_identity: Digest,
    claims: poseidon2_air.Claims,
};

pub const AggregateClosureV1 = struct {
    plan_identity: Digest,
    relation_context_identity: Digest,
    shard_count: u32,
    core_claim: QM31,
    provider_claim: QM31,
    closed_sum: QM31,
};

/// Recompute the only accepted native closure.  A future production caller
/// must supply these values from fresh-verifier-minted receipts; this helper
/// never turns detached metadata into proof authority by itself.
pub fn verifyAggregateClosure(
    plan: *const ProviderShardPlanV1,
    calls: []const poseidon2_air.Call,
    relation: PoseidonRelationContextV1,
    core: CorePoseidonClaimV1,
    provider_shards: []const ProviderShardClaimV1,
) !AggregateClosureV1 {
    return verifyAggregateClosureInternal(
        null,
        plan,
        calls,
        relation,
        core,
        provider_shards,
    );
}

/// Identity-neutral sibling of `verifyAggregateClosure`.  The only difference
/// is that the complete plan/call corpus is readmitted through an already
/// minted `OwnedValidatedPlanCallAuthorityV1` in O(1) instead of being
/// rehashed.  Every claim, sum, and returned field is computed identically.
pub fn verifyAggregateClosureValidated(
    validated: *const OwnedValidatedPlanCallAuthorityV1,
    plan: *const ProviderShardPlanV1,
    calls: []const poseidon2_air.Call,
    relation: PoseidonRelationContextV1,
    core: CorePoseidonClaimV1,
    provider_shards: []const ProviderShardClaimV1,
) !AggregateClosureV1 {
    return verifyAggregateClosureInternal(
        validated,
        plan,
        calls,
        relation,
        core,
        provider_shards,
    );
}

fn verifyAggregateClosureInternal(
    validated: ?*const OwnedValidatedPlanCallAuthorityV1,
    plan: *const ProviderShardPlanV1,
    calls: []const poseidon2_air.Call,
    relation: PoseidonRelationContextV1,
    core: CorePoseidonClaimV1,
    provider_shards: []const ProviderShardClaimV1,
) !AggregateClosureV1 {
    if (validated) |token|
        try token.validateBorrowed(plan, calls)
    else
        try plan.validate(calls);
    try relation.validate(plan.session);
    if (!aggregation_hash.eql(core.plan_identity, plan.identity))
        return error.PlanIdentityMismatch;
    if (!aggregation_hash.eql(
        core.relation_context_identity,
        relation.identity,
    )) return error.RelationContextMismatch;
    if (provider_shards.len != plan.shards.len)
        return error.ShardClaimCountMismatch;

    var provider_total = QM31.zero();
    for (provider_shards, plan.shards, 0..) |claim, descriptor, index| {
        if (claim.shard_index != index)
            return error.NonCanonicalShardClaimOrder;
        if (!aggregation_hash.eql(claim.plan_identity, plan.identity))
            return error.PlanIdentityMismatch;
        if (!aggregation_hash.eql(
            claim.descriptor_identity,
            descriptor.identity,
        )) return error.ShardClaimDescriptorMismatch;
        if (!aggregation_hash.eql(
            claim.relation_context_identity,
            relation.identity,
        )) return error.RelationContextMismatch;
        provider_total = provider_total.add(claim.claims.total());
    }

    const closed_sum = core.claim.add(provider_total);
    if (!closed_sum.isZero()) return error.PoseidonRelationNotClosed;
    return .{
        .plan_identity = plan.identity,
        .relation_context_identity = relation.identity,
        .shard_count = plan.shard_count,
        .core_claim = core.claim,
        .provider_claim = provider_total,
        .closed_sum = closed_sum,
    };
}

pub fn orderedCallListCommitment(
    calls: []const poseidon2_air.Call,
) !Digest {
    if (calls.len == 0) return error.EmptyCallAuthority;
    try validateNarrowCalls(calls);
    return callCommitment(global_calls_domain, 0, calls);
}

fn orderedShardCallCommitment(
    first_call: u64,
    calls: []const poseidon2_air.Call,
) !Digest {
    if (calls.len == 0) return error.EmptyProviderShard;
    try validateNarrowCalls(calls);
    return callCommitment(shard_calls_domain, first_call, calls);
}

fn callCommitment(
    domain: []const u8,
    first_call: u64,
    calls: []const poseidon2_air.Call,
) Digest {
    var sink = aggregation_hash.HashSink.init(domain);
    aggregation_hash.writeU32(&sink, format_version) catch unreachable;
    aggregation_hash.writeU64(&sink, first_call) catch unreachable;
    aggregation_hash.writeU64(&sink, calls.len) catch unreachable;
    for (calls, 0..) |call, offset| {
        aggregation_hash.writeU64(
            &sink,
            first_call + @as(u64, @intCast(offset)),
        ) catch unreachable;
        for (call.input) |value|
            aggregation_hash.writeU32(&sink, value) catch unreachable;
        aggregation_hash.writeU32(&sink, call.narrow_output.?) catch unreachable;
    }
    return sink.finalize();
}

fn validateNarrowCalls(calls: []const poseidon2_air.Call) !void {
    for (calls) |call| {
        if (call.wide or call.io or call.narrow_output == null)
            return error.NonCanonicalNarrowCall;
        if (call.input[0] >= m31.Modulus or
            call.input[1] >= m31.Modulus or
            call.narrow_output.? >= m31.Modulus)
        {
            return error.NonCanonicalM31Value;
        }
        for (call.input[2..]) |value| {
            if (value != 0) return error.NonCanonicalNarrowCall;
        }
    }
}

fn descriptorIdentity(descriptor: ProviderShardDescriptorV1) Digest {
    var sink = aggregation_hash.HashSink.init(descriptor_domain);
    aggregation_hash.writeU32(&sink, descriptor.format) catch unreachable;
    sink.writeAll(&descriptor.session) catch unreachable;
    aggregation_hash.writeU32(&sink, descriptor.shard_index) catch unreachable;
    aggregation_hash.writeU32(&sink, descriptor.shard_count) catch unreachable;
    aggregation_hash.writeU64(&sink, descriptor.first_call) catch unreachable;
    aggregation_hash.writeU32(&sink, descriptor.call_count) catch unreachable;
    sink.writeAll(&descriptor.global_call_list_commitment) catch unreachable;
    sink.writeAll(&descriptor.shard_call_list_commitment) catch unreachable;
    sink.writeAll(&.{@intFromEnum(descriptor.mode)}) catch unreachable;
    aggregation_hash.writeU32(&sink, descriptor.expected_log_size) catch unreachable;
    aggregation_hash.writeU16(&sink, descriptor.main_columns) catch unreachable;
    aggregation_hash.writeU16(&sink, descriptor.interaction_columns) catch unreachable;
    return sink.finalize();
}

fn planIdentity(plan: *const ProviderShardPlanV1) Digest {
    var sink = aggregation_hash.HashSink.init(plan_domain);
    aggregation_hash.writeU32(&sink, plan.format) catch unreachable;
    sink.writeAll(&plan.session) catch unreachable;
    aggregation_hash.writeU64(&sink, plan.total_call_count) catch unreachable;
    aggregation_hash.writeU32(&sink, plan.shard_count) catch unreachable;
    sink.writeAll(&plan.residency.result.request_identity) catch unreachable;
    sink.writeAll(&plan.residency.result.plan_identity) catch unreachable;
    sink.writeAll(&plan.call_list_commitment) catch unreachable;
    aggregation_hash.writeU64(&sink, plan.shards.len) catch unreachable;
    for (plan.shards) |shard| sink.writeAll(&shard.identity) catch unreachable;
    return sink.finalize();
}

fn relationContextIdentity(context: PoseidonRelationContextV1) Digest {
    var sink = aggregation_hash.HashSink.init(relation_context_domain);
    aggregation_hash.writeU32(&sink, format_version) catch unreachable;
    sink.writeAll(&context.session) catch unreachable;
    writeQM31(&sink, context.z);
    writeQM31(&sink, context.alpha);
    return sink.finalize();
}

fn writeQM31(sink: anytype, value: QM31) void {
    for (value.toM31Array()) |limb|
        aggregation_hash.writeU32(sink, limb.v) catch unreachable;
}

fn expectedLogSize(call_count: u32) u32 {
    return @max(
        minimum_shard_log_size,
        std.math.log2_int_ceil(u32, call_count),
    );
}

const global_calls_domain =
    "stwo-zig/riscv/narrow-memory-poseidon2/calls/v1\x00";
const shard_calls_domain =
    "stwo-zig/riscv/narrow-memory-poseidon2/shard-calls/v1\x00";
const descriptor_domain =
    "stwo-zig/riscv/narrow-memory-poseidon2/shard-descriptor/v1\x00";
const plan_domain =
    "stwo-zig/riscv/narrow-memory-poseidon2/shard-plan/v1\x00";
const relation_context_domain =
    "stwo-zig/riscv/narrow-memory-poseidon2/relation-context/v1\x00";
