// Generated by src/tests/riscv/blake3_interaction_aot_test.zig
pub const entries = .{
    .{ .name = "stwo_zig_framework_interaction_block_scan_v1", .declaration_sha256 = "3608a8b50040f109034fcbffa92ac40dc30cc352324b417d5dcae75ac3f2fb4e" },
    .{ .name = "stwo_zig_framework_interaction_scan_blocks_v1", .declaration_sha256 = "047b3d68b7c06bae4a8dfc4d719fdf5e234cb1ecb09a635049984d276854e3df" },
    .{ .name = "stwo_zig_framework_interaction_finalize_v1", .declaration_sha256 = "c6aaf8c98c7291de1bac3db1a5721fc5549e8ccbb5738d728d2fadffed0cd6a1" },
    .{ .name = "stwo_zig_framework_interaction_cumulative_block_scan_v1", .declaration_sha256 = "607c195fe694e64a240c282d9c8ab3683de892d918b74687134cb4b0b8d5594f" },
    .{ .name = "stwo_zig_framework_interaction_cumulative_scan_blocks_v1", .declaration_sha256 = "4437e6024432587fe95f932aaf2150279a08f88f40092ecce72d8b5b29e10ffa" },
    .{ .name = "stwo_zig_framework_interaction_cumulative_finalize_v1", .declaration_sha256 = "a10a7ebb3868ec872a8198aa10ccb7e1095eeae0e0cb2d2f5bfd4624d9e0751d" },
    .{ .name = "stwo_zig_framework_interaction_v1_df04defc9536efcd619156bbc6c07a5d6c06822458ab36807ad26fbe10ac18a6", .declaration_sha256 = "cbdc372ef3b4735dd076f2cde0c7f5ddaf9a14954d41bc5e8a0d4ba140005225" },
    .{ .name = "stwo_zig_framework_interaction_v1_3189e0f57241480608d508e3d36064f73c53ad19b6bea003e6b7dc0d14cc975b", .declaration_sha256 = "77ed2a9f991e11791e3ccad22b51a9321eb166c53aa2fb6ef434d18b06f42a5b" },
    .{ .name = "stwo_zig_framework_interaction_v1_1da43de062b46ceaa5e04a77f429f3466050cfca52f6b1830a1133298130c20f", .declaration_sha256 = "2d18691edf3ba7565f53f228690accce2c0cb63de46ec6465c56de55e76ff008" },
    .{ .name = "stwo_zig_framework_interaction_v1_ace96d9a45c208b9f233bb27ac73ce6147a91ad9df4301b9f1aff166fef6c9c4", .declaration_sha256 = "dcd746b9aefa241d8a70a5e70d947c96154279c92a9f1ed124d6133487b111c3" },
    .{ .name = "stwo_zig_framework_interaction_v1_91d5fa87688b8c993ffca44fbb0679d02b25139fd1f538482c23d08bbfa7dec7", .declaration_sha256 = "5f1bb74d4da27251e9a882c756502b76cb3daaa3aaa0e0dbc1a0559124bf61d1" },
    .{ .name = "stwo_zig_framework_interaction_v1_a20d43085e9946c62dae85cfd655f90cfd044884b022408cc301aad58f77d860", .declaration_sha256 = "dc700a8c31955dd3d0941cf5de4b45afe58f7eced986d7fdcee6d351b0071310" },
    .{ .name = "stwo_zig_framework_interaction_v1_f3062cacdbdc4475a2eb63fe1632cdea209bea7f6b52826d0373f4281b5e0f69", .declaration_sha256 = "7a540f8839ef250760baee311eaa5a1610925f1cb4ab8436a59100c4dc114761" },
    .{ .name = "stwo_zig_framework_interaction_v1_75a8d6628aa611590f73e1140e4d07eb773e0a4b856497959812210fd52bfdb1", .declaration_sha256 = "d6484f0cd02731a60fb938fb9e9db6543793a09bf5d6841e34bbf08d0b85a147" },
};
