/-! Generated by scripts/s31_formal.py from S31 relation IR v1. -/
namespace S31

inductive Op where
  | constant
  | cast_m31
  | add
  | mul
  | add_const
  | mul_const
  | repeat
  | hash_blake2s
  | hash_blake2s_leaf
  | hash_blake2s_pair
  | select
  | hash_poseidon2_leaf
  | hash_poseidon2_pair
  | sum_lanes
  | u256_add
  | u256_le
  | u256_add_checked
  | hash_sha256d_header
  | bitcoin_target_mainnet
  | bitcoin_prev_hash
  | bitcoin_header_bits
  | bitcoin_genesis_hash_mainnet
  | bitcoin_header_time
  | u32_lt
  | inv
  | is_zero
  | u256_sub
  | u256_sub_checked
  | array_get
  | array_concat
  | array_slice
  | bool_not
  | bool_and
  | bool_or
  | bool_xor
  | bool_select
  | bitcoin_block_work
  | int_view
  | int_add_checked
  | int_add_wrapping
  | int_sub_checked
  | int_sub_wrapping
  | int_le
deriving DecidableEq, Repr, BEq

def Op.wireName : Op → String
  | .constant => "constant"
  | .cast_m31 => "cast_m31"
  | .add => "add"
  | .mul => "mul"
  | .add_const => "add_const"
  | .mul_const => "mul_const"
  | .repeat => "repeat"
  | .hash_blake2s => "hash_blake2s"
  | .hash_blake2s_leaf => "hash_blake2s_leaf"
  | .hash_blake2s_pair => "hash_blake2s_pair"
  | .select => "select"
  | .hash_poseidon2_leaf => "hash_poseidon2_leaf"
  | .hash_poseidon2_pair => "hash_poseidon2_pair"
  | .sum_lanes => "sum_lanes"
  | .u256_add => "u256_add"
  | .u256_le => "u256_le"
  | .u256_add_checked => "u256_add_checked"
  | .hash_sha256d_header => "hash_sha256d_header"
  | .bitcoin_target_mainnet => "bitcoin_target_mainnet"
  | .bitcoin_prev_hash => "bitcoin_prev_hash"
  | .bitcoin_header_bits => "bitcoin_header_bits"
  | .bitcoin_genesis_hash_mainnet => "bitcoin_genesis_hash_mainnet"
  | .bitcoin_header_time => "bitcoin_header_time"
  | .u32_lt => "u32_lt"
  | .inv => "inv"
  | .is_zero => "is_zero"
  | .u256_sub => "u256_sub"
  | .u256_sub_checked => "u256_sub_checked"
  | .array_get => "array_get"
  | .array_concat => "array_concat"
  | .array_slice => "array_slice"
  | .bool_not => "bool_not"
  | .bool_and => "bool_and"
  | .bool_or => "bool_or"
  | .bool_xor => "bool_xor"
  | .bool_select => "bool_select"
  | .bitcoin_block_work => "bitcoin_block_work"
  | .int_view => "int_view"
  | .int_add_checked => "int_add_checked"
  | .int_add_wrapping => "int_add_wrapping"
  | .int_sub_checked => "int_sub_checked"
  | .int_sub_wrapping => "int_sub_wrapping"
  | .int_le => "int_le"

def Op.ofWireName : String → Option Op
  | "constant" => some .constant
  | "cast_m31" => some .cast_m31
  | "add" => some .add
  | "mul" => some .mul
  | "add_const" => some .add_const
  | "mul_const" => some .mul_const
  | "repeat" => some .repeat
  | "hash_blake2s" => some .hash_blake2s
  | "hash_blake2s_leaf" => some .hash_blake2s_leaf
  | "hash_blake2s_pair" => some .hash_blake2s_pair
  | "select" => some .select
  | "hash_poseidon2_leaf" => some .hash_poseidon2_leaf
  | "hash_poseidon2_pair" => some .hash_poseidon2_pair
  | "sum_lanes" => some .sum_lanes
  | "u256_add" => some .u256_add
  | "u256_le" => some .u256_le
  | "u256_add_checked" => some .u256_add_checked
  | "hash_sha256d_header" => some .hash_sha256d_header
  | "bitcoin_target_mainnet" => some .bitcoin_target_mainnet
  | "bitcoin_prev_hash" => some .bitcoin_prev_hash
  | "bitcoin_header_bits" => some .bitcoin_header_bits
  | "bitcoin_genesis_hash_mainnet" => some .bitcoin_genesis_hash_mainnet
  | "bitcoin_header_time" => some .bitcoin_header_time
  | "u32_lt" => some .u32_lt
  | "inv" => some .inv
  | "is_zero" => some .is_zero
  | "u256_sub" => some .u256_sub
  | "u256_sub_checked" => some .u256_sub_checked
  | "array_get" => some .array_get
  | "array_concat" => some .array_concat
  | "array_slice" => some .array_slice
  | "bool_not" => some .bool_not
  | "bool_and" => some .bool_and
  | "bool_or" => some .bool_or
  | "bool_xor" => some .bool_xor
  | "bool_select" => some .bool_select
  | "bitcoin_block_work" => some .bitcoin_block_work
  | "int_view" => some .int_view
  | "int_add_checked" => some .int_add_checked
  | "int_add_wrapping" => some .int_add_wrapping
  | "int_sub_checked" => some .int_sub_checked
  | "int_sub_wrapping" => some .int_sub_wrapping
  | "int_le" => some .int_le
  | _ => none

def allOps : List Op := [
  .constant,
  .cast_m31,
  .add,
  .mul,
  .add_const,
  .mul_const,
  .repeat,
  .hash_blake2s,
  .hash_blake2s_leaf,
  .hash_blake2s_pair,
  .select,
  .hash_poseidon2_leaf,
  .hash_poseidon2_pair,
  .sum_lanes,
  .u256_add,
  .u256_le,
  .u256_add_checked,
  .hash_sha256d_header,
  .bitcoin_target_mainnet,
  .bitcoin_prev_hash,
  .bitcoin_header_bits,
  .bitcoin_genesis_hash_mainnet,
  .bitcoin_header_time,
  .u32_lt,
  .inv,
  .is_zero,
  .u256_sub,
  .u256_sub_checked,
  .array_get,
  .array_concat,
  .array_slice,
  .bool_not,
  .bool_and,
  .bool_or,
  .bool_xor,
  .bool_select,
  .bitcoin_block_work,
  .int_view,
  .int_add_checked,
  .int_add_wrapping,
  .int_sub_checked,
  .int_sub_wrapping,
  .int_le]

end S31
