//! OPEN same-parent global tuple equations. Inputs are original public claim
//! bytes, independently derived PUBLIC preimage bytes, and exact B5SS draws.
//! Source-image/initial/endpoint completeness remains a required obligation.
const std = @import("std");
const Arena = @import("stable_graph_arena_v1.zig").Owned;
const core = @import("stwo_core");
const M = core.fields.m31.M31;
const Q = core.fields.qm31.QM31;
const R = @import("composition_graph_recorder.zig");
const Raw = @import("block_v5_global_join_source_values_v1.zig");
const Semantic = @import("../block_v5_global_join_semantic_plan_v1.zig");
const Public = @import("../block_v5_global_public_export_policy_v1.zig");
const Bus = @import("../block_v5_global_public_export_bus_v1.zig");
const Tuple = @import("block_v5_global_public_tuple_algebra_v1.zig");
const Join = @import("../../prover/block_v5_global_join_algebra_v1.zig");
const U = @import("universal_challenges.zig");
const Budget = @import("stwo_prover_engine").host_budget_allocator.SharedHostBudget;
pub const VERSION: u32 = 1;
pub const Source = union(enum) { public: Bus.Source, challenge: u32 };
pub const Prepared = struct {
    budget: *Budget,
    arena: Arena,
    circuit: R.Circuit,
    inputs: []Q,
    values: []Q,
    sources: []Source,
    relations: U.UniversalRelations,
    semantic_identity: [32]u8,
    pub const complete_source_authority = false;
    pub fn deinit(self: *Prepared) void {
        self.circuit.deinit();
        self.arena.deinit();
        self.budget.destroy();
        self.* = undefined;
    }
};
const Sink = struct {
    builder: *R.Builder,
    pub fn zero(self: *@This(), value: R.Scalar, _: anyerror) !void {
        try self.builder.check();
        try self.builder.constrainZero(value);
    }
};
const ChallengeView = struct {
    set: R.ChallengeSet,
    pub fn getExact(self: *const @This(), domain: @import("../../air/lang/relation.zig").Domain) !*const R.ChallengeSet.Element {
        return self.set.get(domain);
    }
};
const Inputs = struct {
    a: std.mem.Allocator,
    builder: *R.Builder,
    values: std.ArrayList(Q) = .empty,
    sources: std.ArrayList(Source) = .empty,
    fn add(self: *@This(), value: Q, source: Source) !R.Scalar {
        const symbol = (try self.builder.input()).value;
        try self.values.append(self.a, value);
        try self.sources.append(self.a, source);
        return symbol;
    }
    fn word(self: *@This(), owner: *const Public.Owner, window: u32, coordinate: u32) !Tuple.Word(R.Scalar) {
        const bytes = try owner.fields[window].bytes(coordinate);
        var result: Tuple.Word(R.Scalar) = undefined;
        for (&result, bytes, 0..) |*symbol, byte, part| symbol.* = try self.add(Q.fromBase(byte), .{ .public = .{ .public_byte = .{ .window = window, .word = coordinate, .part = @intCast(part) } } });
        return result;
    }
};
fn selected(comptime S: type, derived: *const Semantic.Derived, claims: []const S, role: Semantic.Role, owner: ?u32, coordinate: ?u32) S {
    var result = S.zero();
    for (derived.exports, claims) |entry, claim| if (entry.role == role and (owner == null or entry.owner == owner.?) and (coordinate == null or entry.coordinate == coordinate.?)) {
        result = result.add(claim);
    };
    return result;
}
fn claimFromBytes(bytes: []const R.Scalar) R.Scalar {
    std.debug.assert(bytes.len == 16);
    var result = R.Scalar.zero();
    for (0..4) |component| {
        var basis: [4]M = @splat(M.zero());
        basis[component] = M.one();
        for (0..4) |part| {
            const weight = Q.fromM31Array(basis).mul(Q.fromBase(M.fromU64(@as(u64, 1) << @as(u6, @intCast(8 * part)))));
            result = result.add(bytes[4 * component + part].mul(R.Scalar.fromSecure(weight)));
        }
    }
    return result;
}
/// Every selector is regenerated by Semantic.derive. No caller-selected role,
/// count, zero claim or repeated unrelated coordinate supplies an equation.
pub fn prepare(backing: std.mem.Allocator, owner: *const Public.Owner, derived: *const Semantic.Derived, max_bytes: usize) !Prepared {
    if (max_bytes == 0) return error.GlobalPublicExportResourceLimit;
    try owner.validate();
    try derived.validateAgainst(owner.policy.original);
    if (derived.execution_count != owner.fields.len) return error.UntrustedGlobalPublicWindows;
    const budget = try Budget.create(backing, max_bytes);
    errdefer budget.destroy();
    var arena = try Arena.init(budget.allocator());
    errdefer arena.deinit();
    const a = arena.allocator();
    var builder = R.Builder.init(a);
    defer builder.deinit();
    var input = Inputs{ .a = a, .builder = &builder };
    const views = try a.alloc(Raw.View, owner.policy.original.children.len);
    for (views, owner.policy.original.children) |*view, child| view.* = .{ .frames = child.frames, .cells = child.cells };
    const raw_claims = try a.alloc([16]R.Scalar, derived.exports.len);
    for (raw_claims, derived.exports) |*symbols, entry| {
        const read = try Raw.read(views, entry.field);
        for (symbols, read.inputs, read.sources) |*symbol, value, source| symbol.* = try input.add(value, .{ .public = .{ .original = .{ .child = source.child, .kind = .pairing_coordinate, .coordinate = source.cell, .part = source.part } } });
    }
    const data = try a.alloc(Tuple.Data(R.Scalar), owner.fields.len);
    const original_digest = try a.alloc([32]R.Scalar, owner.fields.len);
    const expected_digest = try a.alloc([32]R.Scalar, owner.fields.len);
    for (data, owner.fields, original_digest, expected_digest, 0..) |*window, field, *actual, *expected, ordinal| {
        const index: u32 = @intCast(ordinal);
        const l = field.layout;
        window.initial_pc = try input.word(owner, index, l.pc_clock);
        window.final_pc = try input.word(owner, index, l.pc_clock + 1);
        window.clock = try input.word(owner, index, l.pc_clock + 2);
        for (0..32) |register| {
            const offset: u32 = @intCast(register);
            window.initial[register] = try input.word(owner, index, l.initial + offset);
            window.final[register] = try input.word(owner, index, l.final + offset);
            window.clocks[register] = try input.word(owner, index, l.clocks + offset);
        }
        window.completion_address = try input.word(owner, index, l.completion + 2);
        for (&window.decoded, 0..) |*symbol, part| symbol.* = try input.word(owner, index, l.decoded + @as(u32, @intCast(part)));
        for (0..2) |limb| {
            const first = try input.word(owner, index, l.cycles + @as(u32, @intCast(limb)));
            const last = try input.word(owner, index, l.cycles + 2 + @as(u32, @intCast(limb)));
            @memcpy(window.first_cycle[4 * limb ..][0..4], &first);
            @memcpy(window.last_cycle[4 * limb ..][0..4], &last);
        }
        const native = try owner.policy.native(index);
        const digest_first = try owner.policy.digestCells(index);
        for (0..32) |part| {
            const cell = digest_first + @as(u32, @intCast(part / 4));
            const byte: u2 = @intCast(part % 4);
            const value = owner.policy.original.children[native.child].cells[cell][byte];
            actual[part] = try input.add(Q.fromBase(value), .{ .public = .{ .original = .{ .child = native.child, .kind = .pairing_coordinate, .coordinate = cell, .part = byte } } });
            expected[part] = try input.add(Q.fromBase(M.fromCanonical(field.source_digest[part])), .{ .public = .{ .public_digest = .{ .window = index, .word = @intCast(part / 4), .part = byte } } });
        }
    }
    var outer_initial: [32]Tuple.Word(R.Scalar) = undefined;
    var outer_final: [32]Tuple.Word(R.Scalar) = undefined;
    const public_values = Bus.Values{ .public = owner };
    for (&outer_initial, &outer_final, 0..) |*first, *last, register| {
        for (first, last, 0..) |*before, *after, part| {
            const initial_source = Bus.Source{ .outer_register_byte = .{ .final = false, .register = @intCast(register), .part = @intCast(part) } };
            const final_source = Bus.Source{ .outer_register_byte = .{ .final = true, .register = @intCast(register), .part = @intCast(part) } };
            before.* = try input.add(Q.fromM31Array(try public_values.at(.{ .circuit = 0, .wire = 0, .uses = 1, .source = initial_source })), .{ .public = initial_source });
            after.* = try input.add(Q.fromM31Array(try public_values.at(.{ .circuit = 0, .wire = 0, .uses = 1, .source = final_source })), .{ .public = final_source });
        }
    }
    const raw_terms = try a.alloc([3][16]R.Scalar, owner.fields.len);
    for (raw_terms, owner.terms, 0..) |*symbols, terms, window| {
        for (symbols, terms, 0..) |*bytes, claim, kind| {
            const words = claim.toM31Array();
            for (bytes, 0..) |*symbol, part| {
                const byte = (words[part / 4].v >> @as(u5, @intCast(8 * (part % 4)))) & 255;
                symbol.* = try input.add(Q.fromBase(M.fromCanonical(byte)), .{ .public = .{ .term_byte = .{ .window = @intCast(window), .kind = @enumFromInt(kind), .limb = @intCast(part / 4), .part = @intCast(part % 4) } } });
            }
        }
    }
    var channel = (try owner.policy.native(0)).admitted.sealed.sharedChannel();
    const relations = try U.UniversalRelations.draw(a, &channel);
    var symbolic_draws: [U.RELATION_COUNT][2]R.Scalar = undefined;
    for (&symbolic_draws, relations.elements, 0..) |*pair, element, ordinal| {
        pair[0] = try input.add(element.z, .{ .challenge = @intCast(2 * ordinal) });
        pair[1] = try input.add(element.alpha_powers[1], .{ .challenge = @intCast(2 * ordinal + 1) });
    }
    try builder.activate();
    defer if (builder.active) builder.deactivate();
    var sink = Sink{ .builder = &builder };
    var challenges = ChallengeView{ .set = try R.ChallengeSet.init(symbolic_draws) };
    try Tuple.registerContinuity(R.Scalar, &sink, outer_initial, data[0].initial);
    try Tuple.registerContinuity(R.Scalar, &sink, data[data.len - 1].final, outer_final);
    const claims = try a.alloc(R.Scalar, derived.exports.len);
    for (claims, raw_claims) |*claim, symbols| claim.* = claimFromBytes(&symbols);
    const local_zero = owner.policy.windows.version == @import("../../prover/block_v5_register_windows_v1.zig").LOCAL_ZERO_VERSION;
    var compensation = R.Scalar.zero();
    var boundary = R.Scalar.zero();
    for (data, owner.fields, original_digest, expected_digest, 0..) |window, field, actual, expected, index| {
        for (actual, expected) |left, right| try sink.zero(left.sub(right), error.UntrustedGlobalPublicDigestSource);
        const p = (try owner.policy.native(@intCast(index))).admitted;
        const terminal_fetch = p.shape.public_data.completion.?.kind != .halt_flag;
        const sums = try Tuple.evaluate(R.Scalar, window, &challenges, local_zero, terminal_fetch);
        try sink.zero(sums.native_compensation.sub(claimFromBytes(&raw_terms[index][0])), error.UntrustedGlobalPublicTerm);
        try sink.zero(sums.register_compensation.sub(claimFromBytes(&raw_terms[index][1])), error.UntrustedGlobalPublicTerm);
        try sink.zero(sums.program_boundary.sub(claimFromBytes(&raw_terms[index][2])), error.UntrustedGlobalPublicTerm);
        try sink.zero(sums.native_compensation.sub(selected(R.Scalar, derived, claims, .native_compensation, @intCast(index), null)), error.UntrustedGlobalNativeCompensation);
        try sink.zero(sums.register_compensation.add(selected(R.Scalar, derived, claims, .register_memory, @intCast(index), null)).add(selected(R.Scalar, derived, claims, .register_clock_memory, @intCast(index), null)), error.UnclosedV5RegisterWindow);
        if (local_zero) try Tuple.localZero(R.Scalar, &sink, window);
        if (index == 0) try Tuple.initialCycle(R.Scalar, &sink, window.first_cycle) else {
            try Tuple.registerContinuity(R.Scalar, &sink, data[index - 1].final, window.initial);
            try Tuple.nextCycle(R.Scalar, &sink, data[index - 1].last_cycle, window.first_cycle);
        }
        // Same policy revalidation covers exact last-first=clock-1 in full u64;
        // these values are deterministic public admission, not private spans.
        _ = field;
        compensation = compensation.add(sums.register_compensation);
        boundary = boundary.add(sums.program_boundary);
    }
    try sink.zero(selected(R.Scalar, derived, claims, .program_provider, null, null).add(selected(R.Scalar, derived, claims, .program_request, null, null)).add(boundary), error.UnclosedProgramRelation);
    try sink.zero(selected(R.Scalar, derived, claims, .ram_link, null, null), error.UnclosedV5RamLanesPredecessorRelation);
    // Preserve each independently admitted shard. A flattened all-range sum
    // cannot hide deficits between providers or unrelated memory instances.
    var next_instance: u32 = 0;
    var next_shard: u32 = 0;
    var ram_count: u32 = 0;
    for (owner.policy.original.expected) |typed| if (typed == .ram_lanes_v1) {
        ram_count += 1;
    };
    for (owner.policy.original.expected) |typed| if (typed == .range16_v1) {
        const shard = typed.range16_v1.admitted.shard;
        if (shard.index != next_shard or shard.first_instance != next_instance or shard.instance_count == 0) return error.UntrustedGlobalRangeCoverage;
        var sum = selected(R.Scalar, derived, claims, .range_provider, shard.index, null);
        const end = try std.math.add(u32, shard.first_instance, shard.instance_count);
        if (end > ram_count) return error.UntrustedGlobalRangeCoverage;
        for (shard.first_instance..end) |instance| sum = sum.add(selected(R.Scalar, derived, claims, .ram_range, @intCast(instance), null));
        try sink.zero(sum, error.UnclosedV5Range16Relation);
        next_instance = end;
        next_shard += 1;
    };
    if (next_instance != ram_count) return error.UntrustedGlobalRangeCoverage;
    const Part = struct { sum: R.Scalar };
    const bytes = try a.alloc(Part, derived.execution_count);
    for (bytes, 0..) |*part, index| part.* = .{ .sum = selected(R.Scalar, derived, claims, .byte_request, @intCast(index), null) };
    try Join.Algebra(R.Scalar).accounting(&sink, .{
        .native_open_sum = selected(R.Scalar, derived, claims, .native_open, null, null),
        .precompile_open_sum = selected(R.Scalar, derived, claims, .caller_open, null, null),
        .public_program_boundary_sum = boundary,
        .program_provider_sum = selected(R.Scalar, derived, claims, .program_provider, null, null),
        .table_provider_sum = selected(R.Scalar, derived, claims, .table_provider, null, null),
        .ordinary_memory_opposite = selected(R.Scalar, derived, claims, .ordinary_memory_opposite, null, null),
        .external_memory_opposite = selected(R.Scalar, derived, claims, .external_memory_opposite, null, null),
        .auxiliary_clock_memory_sum = selected(R.Scalar, derived, claims, .auxiliary_clock, null, null),
        .register_compensation_sum = compensation,
    }, bytes);
    try builder.check();
    builder.deactivate();
    var circuit = try builder.finish();
    errdefer circuit.deinit();
    const inputs = try input.values.toOwnedSlice(a);
    const sources = try input.sources.toOwnedSlice(a);
    const values = try a.alloc(Q, circuit.nodes.len);
    try circuit.evaluateInto(inputs, values);
    return .{ .budget = budget, .arena = arena, .circuit = circuit, .inputs = inputs, .values = values, .sources = sources, .relations = relations, .semantic_identity = derived.identity() };
}
