[package]
name = "s31_hash4_cairo"
version = "0.1.0"
edition = "2024_07"

[cairo]
sierra-replace-ids = true
enable-gas = false

[[target.executable]]

[dependencies]
cairo_execute = "2.18.0"

[dev-dependencies]
cairo_test = "2.18.0"
