//! Physical typed-row writes for the direct 47-row leaf cohort.
//!
//! The program/statement preprocessed tree is verifier-owned. This module
//! places already validated logical witness rows into the canonical circle
//! order and exact PlanV4 offsets; it does not select source values or mint a
//! proof. Interaction columns are generated by each authenticated AIR runtime.

const std = @import("std");
const M31 = @import("stwo_core").fields.m31.M31;
const QM31 = @import("stwo_core").fields.qm31.QM31;
const plan_mod = @import("air/segment_leaf_wrapper_roster_direct_v4.zig");
const framework = @import("air/framework_interaction.zig");
const hash_air = @import("air/vm_public_claim_hash.zig");
const hash_witness = @import("segment_leaf_wrapper_field_hash_witness_v3.zig");

pub const PRODUCTION_PROOF_ACTIVATION = false;

pub fn fillPreprocessed(
    comptime Air: type,
    plan: *const plan_mod.Plan,
    key: plan_mod.ComponentKey,
    rows: []const Air.Row,
    destination: [][]M31,
) !void {
    try fillTyped(Air, plan, key, rows, destination, .preprocessed);
}

pub fn fillMain(
    comptime Air: type,
    plan: *const plan_mod.Plan,
    key: plan_mod.ComponentKey,
    rows: []const Air.Row,
    destination: [][]M31,
) !void {
    try fillTyped(Air, plan, key, rows, destination, .main);
}

pub fn fillHashPreprocessed(
    plan: *const plan_mod.Plan,
    key: plan_mod.ComponentKey,
    witness: *const hash_witness.HashV1,
    destination: [][]M31,
) !void {
    try fillHash(plan, key, witness, destination, .preprocessed);
}

pub fn fillHashMain(
    plan: *const plan_mod.Plan,
    key: plan_mod.ComponentKey,
    witness: *const hash_witness.HashV1,
    destination: [][]M31,
) !void {
    try fillHash(plan, key, witness, destination, .main);
}

/// Writes the authenticated runtime's committed LogUp columns and returns
/// its claim. The direct cohort must still audit exact per-domain sums and
/// close all 47 rows before this claim enters a proof transcript.
pub fn fillInteraction(
    plan: *const plan_mod.Plan,
    key: plan_mod.ComponentKey,
    generated: anytype,
    destination: [][]M31,
) !QM31 {
    try plan.validate();
    const placement = try plan.placement(key);
    const size = @as(usize, 1) << @intCast(placement.geometry.log_size);
    const n = placement.geometry.interaction_columns;
    if (generated.columns.len != n or
        placement.interaction_offset > destination.len or
        n > destination.len - placement.interaction_offset)
        return error.DirectTypedInteractionGeometryMismatch;
    for (generated.columns, destination[placement.interaction_offset..][0..n]) |source, target| {
        if (source.len != size or target.len != size)
            return error.DirectTypedInteractionGeometryMismatch;
        for (target) |value| if (!value.isZero())
            return error.DirectTypedRowDestinationNotFresh;
    }
    for (generated.columns, destination[placement.interaction_offset..][0..n]) |source, target|
        @memcpy(target, source);
    return generated.claims.total();
}

const Tree = enum { preprocessed, main };

fn fillTyped(
    comptime Air: type,
    plan: *const plan_mod.Plan,
    key: plan_mod.ComponentKey,
    rows: []const Air.Row,
    destination: [][]M31,
    tree: Tree,
) !void {
    comptime {
        if (Air.LOGICAL_INPUT_COUNT < Air.PHYSICAL_MAIN_COLUMN_COUNT + Air.PREPROCESSED_COLUMN_COUNT)
            @compileError("typed row has fewer logical inputs than physical columns");
    }
    const placement = try placementFor(Air, plan, key, rows.len, destination, tree);
    for (rows, 0..) |row, logical| {
        const committed = framework.committedRow(logical, placement.geometry.log_size);
        const begin = if (tree == .main) 0 else Air.PHYSICAL_MAIN_COLUMN_COUNT;
        const n = if (tree == .main) Air.PHYSICAL_MAIN_COLUMN_COUNT else Air.PREPROCESSED_COLUMN_COUNT;
        const offset = if (tree == .main) placement.main_offset else placement.preprocessed_offset;
        for (row[begin..][0..n], 0..) |value, column|
            destination[offset + column][committed] = value;
    }
}

fn fillHash(
    plan: *const plan_mod.Plan,
    key: plan_mod.ComponentKey,
    witness: *const hash_witness.HashV1,
    destination: [][]M31,
    tree: Tree,
) !void {
    if (key != .program_hash and key != .metadata_hash and key != .link_hash)
        return error.InvalidDirectHashRow;
    const size = @as(usize, 1) << @intCast(witness.log_size);
    const placement = try placementFor(hash_air, plan, key, size, destination, tree);
    for (0..size) |logical| {
        const row = if (logical < witness.main.len)
            try witness.logicalRow(logical)
        else
            [_]M31{M31.zero()} ** hash_air.LOGICAL_INPUT_COUNT;
        const committed = framework.committedRow(logical, placement.geometry.log_size);
        const begin = if (tree == .main) 0 else hash_air.PHYSICAL_MAIN_COLUMN_COUNT;
        const n = if (tree == .main) hash_air.PHYSICAL_MAIN_COLUMN_COUNT else hash_air.PREPROCESSED_COLUMN_COUNT;
        const offset = if (tree == .main) placement.main_offset else placement.preprocessed_offset;
        for (row[begin..][0..n], 0..) |value, column|
            destination[offset + column][committed] = value;
    }
}

fn placementFor(
    comptime Air: type,
    plan: *const plan_mod.Plan,
    key: plan_mod.ComponentKey,
    row_count: usize,
    destination: [][]M31,
    tree: Tree,
) !plan_mod.Placement {
    try plan.validate();
    const placement = try plan.placement(key);
    const geometry = placement.geometry;
    const size = @as(usize, 1) << @intCast(geometry.log_size);
    if (row_count != size or
        geometry.main_columns != Air.PHYSICAL_MAIN_COLUMN_COUNT or
        geometry.preprocessed_columns != Air.PREPROCESSED_COLUMN_COUNT)
        return error.DirectTypedRowGeometryMismatch;
    const offset = if (tree == .main) placement.main_offset else placement.preprocessed_offset;
    const n = if (tree == .main) Air.PHYSICAL_MAIN_COLUMN_COUNT else Air.PREPROCESSED_COLUMN_COUNT;
    if (offset > destination.len or n > destination.len - offset)
        return error.DirectTypedRowDestinationMismatch;
    for (destination[offset..][0..n]) |column| {
        if (column.len != size) return error.DirectTypedRowDestinationMismatch;
        for (column) |value| if (!value.isZero())
            return error.DirectTypedRowDestinationNotFresh;
    }
    return placement;
}
