//! Native generator for `abi_declaration_digests.zig`.
//!
//! Run through `zig build update-abi-declaration-digests` in
//! `src/backends/metal` after any change to a Native kernel declaration. The
//! ABI contract refuses to compile when the export list and this table drift
//! apart, and a runtime test recomputes every digest.

const std = @import("std");
const manifest = @import("shaders/manifest.zig");
const digest = @import("shaders/abi_declaration_digest.zig");

pub fn main() !void {
    var arena = std.heap.ArenaAllocator.init(std.heap.page_allocator);
    defer arena.deinit();
    const allocator = arena.allocator();
    const arguments = try std.process.argsAlloc(allocator);
    if (arguments.len != 2) {
        std.debug.print("usage: abi_declaration_digests_update <output.zig>\n", .{});
        return error.InvalidArguments;
    }

    var rendered: std.ArrayListUnmanaged(u8) = .empty;
    const writer = rendered.writer(allocator);
    try writer.writeAll(
        \\//! GENERATED by `zig build update-abi-declaration-digests` in
        \\//! `src/backends/metal`. Do not edit by hand.
        \\//!
        \\//! One canonical declaration digest per Native export, in manifest order.
        \\//! `abi_contract.zig` refuses to compile if the names drift from
        \\//! `manifest.native_exports`, and its runtime test recomputes every digest
        \\//! from the amalgamated shader source.
        \\
        \\pub const Entry = struct {
        \\    name: []const u8,
        \\    declaration_sha256: [64]u8,
        \\};
        \\
        \\
    );
    try writer.print("pub const entries = [{d}]Entry{{\n", .{manifest.native_exports.len});
    for (manifest.native_exports) |entry| {
        const hex = digest.declarationDigestHex(manifest.native_amalgamated_source, entry.name) catch |err| {
            std.debug.print("export {s}: {s}\n", .{ entry.name, @errorName(err) });
            return err;
        };
        try writer.print(
            "    .{{ .name = \"{s}\", .declaration_sha256 = \"{s}\".* }},\n",
            .{ entry.name, hex },
        );
    }
    try writer.writeAll("};\n");

    const file = try std.fs.cwd().createFile(arguments[1], .{});
    defer file.close();
    try file.writeAll(rendered.items);
}
