//! Two real Ethereum segments, full-memory custody and an independently verified root.
const std = @import("std");
const Cpu = @import("stwo_cpu_backend").CpuBackend;
const runner = @import("../runner/mod.zig");
const Owner = @import("blake3_ethereum_witness.zig").Owner;
const Api = @import("blake3_ethereum_proof.zig").ForBackend(Cpu);
const Pipeline = @import("blake3_segment_parent.zig").ForEthereumBackend(Cpu);
const parent = @import("../recursion/blake3_execution_parent_proof.zig");
const span = @import("../recursion/span_statement_blake3.zig");
const source = @import("../recursion/air/blake3_memory_snapshot.zig");
test "BLAKE3 Ethereum adjacent segments prove full custody and aggregate root" {
    try check(.diagnostic_q8_pow0);
}
test "BLAKE3 Ethereum canonical segments prove full custody and aggregate root" {
    try check(.csp_q70_pow26);
}
fn check(comptime profile: parent.protocol.Profile) !void {
    const config = profile.config();
    const a = std.testing.allocator;
    const pool_mod = @import("stwo_prover_engine").work_pool;
    var pool: pool_mod.WorkPool = undefined;
    try pool.initInPlaceWithOptions(.{ .worker_count = 4, .backing_allocator = a });
    defer pool.deinit();
    var binding = try pool_mod.ScopedPoolBinding.init(&pool);
    var binding_alive = true;
    defer if (binding_alive) binding.deinit();
    const elf = @import("../runner/guest_precompile/test_elf.zig").buildEthereumWithCompletion(.self_loop);
    var session = try runner.EthereumExecutionSession.init(a, &elf, .{ .trace_retention = .segment_owned, .clock_frame = .leaf_local });
    defer session.deinit();
    var first = try session.startSegment(3);
    defer first.deinit();
    var second = try session.resumeSegment(first.base.continuation.?, 100);
    defer second.deinit();
    try std.testing.expectEqual(@as(usize, 1), first.signer_recovery_calls.len());
    try std.testing.expectEqual(@as(usize, 0), first.keccakf_calls.len());
    try std.testing.expectEqual(@as(usize, 1), second.keccakf_calls.len());
    try std.testing.expectEqual(@as(usize, 0), second.signer_recovery_calls.len());
    try std.testing.expectEqual(@as(u64, 4), second.base.global_first_cycle);
    var left = try Owner.initSegment(a, &first);
    var left_alive = true;
    defer if (left_alive) left.deinit();
    var right = try Owner.initSegment(a, &second);
    var right_alive = true;
    defer if (right_alive) right.deinit();
    try std.testing.expectEqualDeep(left.memory.program.root, right.memory.program.root);
    var entry = try source.fromSnapshot(a, &first.base.rw_memory, .entry, .continuation);
    defer entry.deinit();
    var middle = try source.fromSnapshot(a, &first.base.rw_memory, .exit, .continuation);
    defer middle.deinit();
    var resumed = try source.fromSnapshot(a, &second.base.rw_memory, .entry, .continuation);
    defer resumed.deinit();
    var final = try source.fromSnapshot(a, &second.base.rw_memory, .exit, .continuation);
    defer final.deinit();
    try std.testing.expectEqualDeep(middle.root, resumed.root);
    const zero = span.Digest{ .bytes = @splat(0) };
    const initial = try span.MachineState.init(first.base.entry_cpu.pc, first.base.entry_cpu.regs, entry.root, zero);
    const shared = try span.MachineState.init(first.base.exit_cpu.pc, first.base.exit_cpu.regs, middle.root, zero);
    const ended = try span.MachineState.init(second.base.exit_cpu.pc, second.base.exit_cpu.regs, final.root, zero);
    const input = try parent.public_io.input(&left.native.statement.public_data);
    const output = try parent.public_io.output(&right.native.statement.public_data);
    const job = try span.JobContext.init(try span.CompleteExecution.init(parent.spans.protocolIdentity(config), left.memory.program.root, initial, ended, input, output, first.base.cycle_count + second.base.cycle_count), 2);
    const statements = [2]span.SpanStatement{
        try span.SpanStatement.segmentLeaf(job, 0, try span.ExecutedSpan.init(0, 1, 0, first.base.cycle_count, initial, shared, .{ .digest = input }, .{ .digest = null })),
        try span.SpanStatement.segmentLeaf(job, 1, try span.ExecutedSpan.init(1, 1, first.base.cycle_count, second.base.cycle_count, shared, ended, .{ .digest = null }, .{ .digest = output })),
    };
    const lkey = try Api.PreparedVerifier.init(a, &left.native.statement, left.statement, try left.admission(), config);
    defer lkey.deinit();
    const rkey = try Api.PreparedVerifier.init(a, &right.native.statement, right.statement, try right.admission(), config);
    defer rkey.deinit();
    var wrong = rkey.id;
    wrong[0] ^= 1;
    try std.testing.expectError(error.UntrustedExecutionKey, Pipeline.preparePairWithPool(a, .{ &left, &right }, .{ lkey, rkey }, .{ lkey.id, wrong }, statements, 2, &pool));
    try std.testing.expect(!left.native.interaction_ready and !right.native.interaction_ready);
    try std.testing.expectError(error.AliasedAggregateChildren, Pipeline.preparePairWithPool(a, .{ &left, &left }, .{ lkey, lkey }, .{ lkey.id, lkey.id }, statements, 2, &pool));
    // A bad second witness must not consume the valid first child.
    right.native.interaction_ready = true;
    try std.testing.expectError(error.InvalidExecutionPhase, Pipeline.preparePairWithPool(a, .{ &left, &right }, .{ lkey, rkey }, .{ lkey.id, rkey.id }, statements, 2, &pool));
    right.native.interaction_ready = false;
    try std.testing.expect(!left.native.interaction_ready);
    right.hashes.plan_id[0] ^= 1;
    try std.testing.expectError(error.UntrustedExecutionKey, Pipeline.preparePairWithPool(a, .{ &left, &right }, .{ lkey, rkey }, .{ lkey.id, rkey.id }, statements, 2, &pool));
    right.hashes.plan_id[0] ^= 1;
    try std.testing.expect(!left.native.interaction_ready and !right.native.interaction_ready);
    var fold = try Pipeline.preparePairWithPool(a, .{ &left, &right }, .{ lkey, rkey }, .{ lkey.id, rkey.id }, statements, 2, &pool);
    var fold_alive = true;
    defer if (fold_alive) fold.deinit();
    left.deinit();
    left_alive = false;
    right.deinit();
    right_alive = false;
    binding.deinit();
    binding_alive = false;
    const retained = try fold.prepared.rows.retainedBytes();
    const statement = fold.statement;
    _ = try span.RootStatement.init(statement);
    std.debug.print("BLAKE3_ETHEREUM_SEGMENTS_PREPARED segments=2 cycles={d} retained_bytes={d}\n", .{ statement.body.executed.cycle_count, retained });
    const key = try parent.ForBackend(Cpu).deriveKeyWithProfileAndPool(a, &fold.prepared, profile, &pool);
    const expected = try key.identity();
    const admission = try parent.protocol.Admission.init(key, expected);
    const Worker = parent.pipeline.ForBackend(Cpu).Worker;
    const worker = try Worker.init(a, &fold.prepared.rows, admission, .{ .worker_count = 4, .host_byte_limit = @as(usize, if (profile == .csp_q70_pow26) 48 else 24) * 1024 * 1024 * 1024, .retained_scratch_limit = 64 * 1024 * 1024 });
    var worker_alive = true;
    defer if (worker_alive) worker.deinit();
    var proof = try worker.prove(&fold.prepared.rows);
    defer proof.deinit();
    const usage = worker.budget.snapshot();
    worker.deinit();
    worker_alive = false;
    fold.deinit();
    fold_alive = false;
    const bytes = try parent.codec.encode(a, &proof, &admission);
    defer a.free(bytes);
    var decoded = try parent.codec.decode(a, bytes, &admission);
    defer decoded.deinit();
    var verified = try parent.tree.Node.verifyOwned(&decoded, admission, expected, statement);
    defer verified.deinit();
    _ = try verified.root();
    try std.testing.expectEqual(@as(usize, config.fri_config.n_queries), verified.verified.capture.queries.raw.len);
    std.debug.print("BLAKE3_ETHEREUM_SEGMENTS verified=true segments=2 signer=1 keccak=1 full_memory_custody=true queries={d} pow_bits={d} artifact_bytes={d} worker_peak_bytes={d} worker_limit_bytes={d} witnesses_and_worker_released=true\n", .{ config.fri_config.n_queries, config.pow_bits, bytes.len, usage.peak_live_bytes, usage.limit });
}
