//! Ordered standalone frontend test catalog; build.zig owns module construction.
//! Roots, filters and count floors stay together for focused edit loops.

pub const Spec = struct {
    step: []const u8,
    description: []const u8,
    root: []const u8,
    imports_prover_engine: bool = false,
    imports_typed_air_artifacts: bool = false,
    filters: []const []const u8 = &.{},
    minimum: usize = 0,
    strip: ?bool = null,
};

pub const specs = [_]Spec{
    .{
        .step = "test-recursion-v6-program-template",
        .description = "Pin proof-independent ProgramV2 words and leave leaf identities dynamic",
        .root = "v6_program_template_test_root.zig",
        .imports_prover_engine = true,
        .filters = &.{"ProgramV2 template changes only"},
        .minimum = 1,
    },
    .{
        .step = "test-recursion-v5-direct-roster",
        .description = "Pin the 50-row direct wrapper geometry and VPR6/VPK6 key namespace",
        .root = "v5_direct_roster_test_root.zig",
        .imports_prover_engine = true,
        .filters = &.{ "direct V5 roster pins", "VPR6 rejects", "VPR6 and VPK6" },
        .minimum = 3,
    },
    .{
        .step = "test-recursion-v5-statement-source",
        .description = "Check exact extra source fan-out for local identity routing",
        .root = "segment_leaf_wrapper_source_projection_v3_test_root.zig",
        .imports_prover_engine = true,
        .filters = &.{"direct V5 Statement"},
        .minimum = 2,
    },
    .{
        .step = "test-recursion-v5-local-identities",
        .description = "Prove exact local-ID router/hash tuples and ordered Poseidon calls",
        .root = "segment_leaf_wrapper_source_projection_v3_test_root.zig",
        .imports_prover_engine = true,
        .filters = &.{ "V5 local identity", "V5 keeps the existing row39 PPR1", "V5 router and two hashes" },
        .minimum = 4,
    },
    .{
        .step = "test-recursion-v4-las2-boundary",
        .description = "Bind direct wrapper LAS2 words to verifier-owned expected public identities",
        .root = "segment_leaf_wrapper_source_projection_v3_test_root.zig",
        .imports_prover_engine = true,
        .filters = &.{"LAS2 public boundary consumes exact expected words and rejects changed identity"},
        .minimum = 1,
    },
    .{
        .step = "test-recursion-v4-program-bridge",
        .description = "Reject missing or changed native ProgramV2 word exports before direct hashing",
        .root = "segment_leaf_wrapper_source_projection_v3_test_root.zig",
        .imports_prover_engine = true,
        .filters = &.{"direct ProgramV2 bridge requires an independent native producer"},
        .minimum = 1,
    },
    .{
        .step = "test-recursion-v4-direct-rows",
        .description = "Write and audit all eight appended direct-wrapper rows under one relation draw",
        .root = "v3_cohort_direct_rows_test_root.zig",
        .imports_prover_engine = true,
        .filters = &.{"direct"},
        .minimum = 15,
    },
    .{
        .step = "test-recursion-direct-npv2-source",
        .description = "Audit dormant native ProgramV2 word sources, fixed bridge, and row4 descriptor routes",
        .root = "direct_npv2_source_test_root.zig",
        .imports_prover_engine = true,
        .filters = &.{"NPV2"},
        .minimum = 15,
    },
    .{
        .step = "test-recursion-direct-wrapper-kernel",
        .description = "Reject unqualified direct 47-row wrapper proofs and validate fixed roster storage",
        .root = "direct_wrapper_kernel_test_root.zig",
        .imports_prover_engine = true,
        .filters = &.{ "direct V3 wrapper kernel rejects fake cohort", "direct fixed roster storage", "direct detached admission" },
        .minimum = 3,
    },
    .{
        .step = "test-recursion-v4-direct-roster",
        .description = "Pin the 47-row direct native verifier wrapper without PFD1 provider rows",
        .root = "direct_wrapper_roster_test_root.zig",
        .imports_prover_engine = true,
        .filters = &.{"direct 47-row wrapper roster excludes post-challenge provider input"},
        .minimum = 1,
    },
    .{
        .step = "test-recursion-v4-direct-row34",
        .description = "Check direct leaf ordered Poseidon calls and enlarged row-34 trace writer",
        .root = "v3_cohort_calls_test_root.zig",
        .imports_prover_engine = true,
        .filters = &.{"direct leaf row34 writes exact ordered Poseidon calls"},
        .minimum = 1,
    },
    .{
        .step = "test-recursion-v3-wrapper-kernel",
        .description = "Reject fake 49-row wrapper cohorts and detached artifacts before qualification",
        .root = "v3_wrapper_kernel_test_root.zig",
        .imports_prover_engine = true,
        .filters = &.{"V3 wrapper kernel rejects fake cohort"},
        .minimum = 1,
    },
    .{
        .step = "test-recursion-v3-extra-rows",
        .description = "Check V3 wrapper rows 41-48 shared word and hash-state closure",
        .root = "v3_extra_rows_test.zig",
        .filters = &.{"V3 extra row exact tuple gate"},
        .minimum = 1,
    },
    .{
        .step = "test-recursion-v3-production-security-policy",
        .description = "Reject weak native and outer child profiles before V3 publication",
        .root = "v3_production_security_policy_test.zig",
        .imports_prover_engine = true,
        .filters = &.{"V3 production security policy"},
        .minimum = 1,
    },
    .{
        .step = "test-recursion-v3-wrapper-roster",
        .description = "Check complete 49-row V3 wrapper geometry and fail-closed proof boundary",
        .root = "wrapper_roster_v3_test_root.zig",
        .imports_prover_engine = true,
        .filters = &.{ "V3 wrapper roster", "V3 production profile" },
        .minimum = 3,
    },
    .{
        .step = "test-recursion-v3-field-manifest",
        .description = "Pin staged ProgramV2/provider source and hash typed adapters without V3 publication",
        .root = "field_manifest_v3_test_root.zig",
        .imports_prover_engine = true,
        .filters = &.{"V3 field extension"},
        .minimum = 1,
    },
    .{
        .step = "test-recursion-v3-link-manifest",
        .description = "Pin the three typed V3 leaf-link adapter geometries without enabling a wrapper proof",
        .root = "link_manifest_v3_test_root.zig",
        .imports_prover_engine = true,
        .filters = &.{"V3 link extension manifest"},
        .minimum = 1,
    },
    .{
        .step = "test-legacy-interaction-oracle",
        .description = "Check retired interaction generation and retained memory layouts",
        .root = "air_semantics_test_root.zig",
        .filters = &.{ "interaction_gen:", "opcode memory:" },
        .minimum = 5,
    },
    .{
        .step = "test-infrastructure-component",
        .description = "Check program/memory work profiles, prepared evaluation and allocation rollback",
        .root = "infrastructure_component_test_root.zig",
        .imports_prover_engine = true,
        .filters = &.{ "component:", "RISC-V component keeps legacy" },
        .minimum = 7,
    },
    .{
        .step = "test-execution-session",
        .description = "Check typed execution, host handling and continuation contracts",
        .root = "runner_test_root.zig",
        .imports_prover_engine = true,
        .filters = &.{ "runner:", "generated retirement registry", "singular production authorities", "production source is singular", "HostRuntime:", "SyscallNr known values" },
        .minimum = 12,
    },
    .{
        .step = "test-vm-air-profile-authority-v2",
        .description = "Check VM profile identity and authority without composition-program or provider-shard tests",
        .root = "vm_air_profile_authority_v2_test_root.zig",
        .imports_prover_engine = true,
        .filters = &.{"authenticated VM AIR ProfileV2"},
        .minimum = 6, // Three authority checks plus three import-discovery tests.
    },
    .{
        .step = "test-isa",
        .description = "Run only RISC-V ISA authority and decoder tests",
        .root = "isa_test_root.zig",
    },
    .{
        .step = "test-runner",
        .description = "Run only RISC-V execution-runner tests",
        .root = "runner_test_root.zig",
        .imports_prover_engine = true,
    },
    .{
        .step = "test-minimal-trace-parallel-replay",
        .description = "Run only the bounded parallel minimal-trace replay gate",
        .root = "runner_test_root.zig",
        .imports_prover_engine = true,
        .filters = &.{"minimal trace: bounded parallel replay preserves canonical leaf order"},
        .minimum = 1,
    },
    .{
        .step = "benchmark-minimal-trace-parallel-replay",
        .description = "Measure bounded parallel minimal-trace replay scaling",
        .root = "runner_test_root.zig",
        .imports_prover_engine = true,
        .filters = &.{"minimal trace: parallel replay reports bounded scaling"},
        .minimum = 1,
    },
    .{
        .step = "test-ethereum-runner",
        .description = "Run the combined Ethereum profile and signer-recovery runner tests",
        .root = "ethereum_runner_test_root.zig",
        .minimum = 11,
    },
    .{
        .step = "test-ethereum-minimal-trace",
        .description = "Run compact Ethereum minimal-trace capture and replay tests",
        .root = "ethereum_minimal_trace_test_root.zig",
        .filters = &.{"Ethereum minimal trace compacts and independently replays both native calls"},
        .minimum = 1,
    },
    .{
        .step = "test-main-trace-plan-execution",
        .description = "Run only bounded main-trace plan and production execution tests",
        .root = "main_trace_plan_execution_test_root.zig",
        .imports_prover_engine = true,
    },
    .{
        .step = "test-poseidon-witness-work",
        .description = "Run exact sparse-memory and guest-Poseidon work-receipt tests",
        .root = "poseidon_witness_work_test_root.zig",
        .imports_prover_engine = true,
        .minimum = 8,
    },
    .{
        .step = "test-interaction-witness-work",
        .description = "Run exact relation-challenge and Tree-2 work-receipt tests",
        .root = "interaction_witness_work_test_root.zig",
        .imports_prover_engine = true,
        .minimum = 3,
    },
    .{
        .step = "test-compact-poseidon-authority",
        .description = "Run compact typed lowering, specialization identity and allocation checks",
        .root = "compact_poseidon_authority_test_root.zig",
        .imports_prover_engine = true,
        .minimum = 8,
    },
    .{
        .step = "test-polynomial-compiler",
        .description = "Check shared polynomial lowering, fixed shells and degree-bounded consumers",
        .root = "polynomial_compiler_test_root.zig",
        .imports_prover_engine = true,
        .minimum = 5,
    },
    .{
        .step = "test-wide-poseidon-authority",
        .description = "Check all typed wide Poseidon equations, events and shared witness authority",
        .root = "wide_poseidon_authority_test_root.zig",
        .imports_prover_engine = true,
        .minimum = 3,
    },
    .{
        .step = "test-native-boundary-authority",
        .description = "Check typed program, memory, clock and lookup policy equations and admission",
        .root = "native_boundary_authority_test_root.zig",
        .imports_prover_engine = true,
        .minimum = 4,
    },
    .{
        .step = "test-merkle-authority",
        .description = "Check typed native Merkle equations, lookup order and specialization rejection",
        .root = "merkle_authority_test_root.zig",
        .imports_prover_engine = true,
        .minimum = 3,
    },
    .{
        .step = "test-parent-canonical-admission",
        .description = "Run parent canonical AIR admission, rejection and protocol identity checks",
        .root = "poseidon2_protocol_identity_test_root.zig",
        .imports_prover_engine = true,
        .minimum = 6,
    },
    .{
        .step = "test-trace-authority",
        .description = "Run trace admission, typed ownership and retired-oracle differential checks",
        .root = "trace_authority_test_root.zig",
        .minimum = 25,
    },
    .{
        .step = "test-air-semantics",
        .description = "Run only RISC-V instruction-family AIR tests",
        .root = "air_semantics_test_root.zig",
        .imports_prover_engine = true,
    },
    .{
        .step = "test-load-store-private",
        .description = "Run focused load/store AIR authority and retirement tests",
        .root = "load_store_private_test_root.zig",
        .minimum = 19,
    },
    .{
        .step = "test-register-read-alias-private",
        .description = "Run nonproduction register-read alias candidate tests",
        .root = "register_read_alias_test_root.zig",
        .minimum = 4,
    },
    .{
        .step = "test-two-read-register-alias-private",
        .description = "Run nonproduction two-read register alias candidate tests",
        .root = "two_read_register_alias_test_root.zig",
        .minimum = 5,
    },
    .{
        .step = "test-semantic-component",
        .description = "Run only semantic-component prepared-domain and resource tests",
        .root = "semantic_component_test_root.zig",
        .imports_prover_engine = true,
        .filters = &.{ "semantic component", "semantic prepared" },
        .minimum = 8,
    },
    .{
        .step = "test-hash-component-prepared",
        .description = "Run only memory-hash prepared-domain and stack-certificate tests",
        .root = "hash_component_prepared_test_root.zig",
        .imports_prover_engine = true,
        .minimum = 9,
    },
    .{
        .step = "test-air-static-profile",
        .description = "Run only typed-AIR static profiler tests",
        .root = "air_static_profile_test_root.zig",
    },
    .{
        .step = "test-air-static-profile-registry",
        .description = "Run the complete native typed-AIR static profile registry",
        .root = "air_static_profile_registry_test_root.zig",
        .imports_typed_air_artifacts = true,
    },
    .{
        .step = "test-air-runtime-profile",
        .description = "Run the authenticated typed-AIR/runtime profile join tests",
        .root = "air_runtime_profile_test_root.zig",
    },
    .{
        .step = "test-proof-phase-meter",
        .description = "Run the exact five-region witness/proving phase-meter state machine",
        .root = "proof_phase_meter_test_root.zig",
    },
    .{
        .step = "test-air-function-frames",
        .description = "Run Cairo-style frame isolation and activation-relation tests",
        .root = "air_function_frames_test_root.zig",
    },
    .{
        .step = "test-air-function-body-lowering",
        .description = "Run bounded authenticated inline-function body lowering tests",
        .root = "air_function_body_lowering_test_root.zig",
    },
    .{
        .step = "test-air-function-body-ownership",
        .description = "Run sealed per-function body ownership and lowering tests",
        .root = "air_function_body_ownership_test_root.zig",
    },
    .{
        .step = "test-air-function-activation-logup",
        .description = "Run live compiler-owned function activation LogUp tests",
        .root = "air_function_activation_logup_test_root.zig",
        .imports_prover_engine = true,
    },
    .{
        .step = "test-lookup-batching",
        .description = "Run compiler-selected LogUp planning and row execution tests",
        .root = "lookup_batch_test_root.zig",
        .imports_prover_engine = true,
        // A-014 cannot advance on an empty shadow-planner binary. Keep the
        // authority, collision, differential, and execution inventory wired.
        .minimum = 16,
    },
    .{
        .step = "test-lookup-source-ingest",
        .description = "Run exact opcode-source ingestion and rollback tests",
        .root = "lookup_source_ingest_test_root.zig",
        .imports_prover_engine = true,
        .minimum = 5,
    },
    .{
        .step = "test-lookup-table-framework-export",
        .description = "Check native fixed-table backend export and ownership without proving",
        .root = "lookup_table_interaction_test_root.zig",
        .filters = &.{"native table framework"},
        .imports_prover_engine = true,
        .minimum = 4,
    },
    .{
        .step = "test-lookup-table-interaction",
        .description = "Run lookup-table interaction parity and rollback tests",
        .root = "lookup_table_interaction_test_root.zig",
        .imports_prover_engine = true,
        .minimum = 9,
    },
    .{
        .step = "test-opcode-interaction",
        .description = "Run scalar/packed opcode interaction parity and rollback tests",
        .root = "opcode_interaction_test_root.zig",
        .imports_prover_engine = true,
        .minimum = 11,
    },
    .{
        .step = "test-lookup-batching-edit",
        .description = "Run the lightweight authenticated lookup-batch planner edit loop",
        .root = "lookup_batch_edit_test_root.zig",
        .filters = &.{"lookup batch planner:"},
        .minimum = 7,
    },
    .{
        .step = "test-lookup-polynomial-v2-edit",
        .description = "Run the lightweight variable-partition polynomial-authority edit loop",
        .root = "lookup_polynomial_v2_edit_test_root.zig",
        .imports_prover_engine = true,
        .filters = &.{"lookup polynomial v2:"},
        .minimum = 4,
    },
    .{
        .step = "test-row-windows",
        .description = "Run compiler-owned row-window, mask, and ownership tests",
        .root = "row_window_test_root.zig",
        .imports_prover_engine = true,
        // A-013 spans both row-window authority and its production component
        // consumer; losing either half invalidates the focused closure gate.
        .minimum = 16,
    },
    .{
        .step = "test-row-windows-edit",
        .description = "Run the lightweight typed row-window authority edit loop",
        .root = "row_window_edit_test_root.zig",
        .filters = &.{"row-window v1:"},
        .minimum = 10,
    },
    .{
        .step = "test-row-window-expressions-v2-edit",
        .description = "Run the lightweight shifted-expression authority edit loop",
        .root = "row_window_expression_v2_edit_test_root.zig",
        .filters = &.{"row-window expression v2:"},
        .minimum = 5,
    },
    .{
        .step = "test-guest-proof-artifact",
        .description = "Check guest proof suite versions, bounded codecs and allocation ownership",
        .root = "guest_precompile_test_root.zig",
        .imports_prover_engine = true,
        .filters = &.{ "guest proof artifact", "guest artifact header", "legacy v3 header bytes" },
        .minimum = 7,
    },
    .{
        .step = "test-guest-precompile",
        .description = "Run only proof-side guest-precompile protocol tests",
        .root = "guest_precompile_test_root.zig",
        .imports_prover_engine = true,
    },
    .{
        .step = "test-bulk-memcpy-candidate",
        .description = "Run the nonproduction word-granular memcpy AIR candidate tests",
        .root = "bulk_memcpy_candidate_test_root.zig",
        .minimum = 6,
    },
    .{
        .step = "test-stack-swap-candidate",
        .description = "Run the nonproduction SWAP1..SWAP16 semantic and AIR candidate tests",
        .root = "stack_swap_candidate_test_root.zig",
        .minimum = 7,
    },
    .{
        .step = "test-sha256-pair-candidate",
        .description = "Run the nonproduction fixed64 SHA-256 pair AIR and caller tests",
        .root = "sha256_pair_candidate_test_root.zig",
        .minimum = 8,
    },
    .{
        .step = "test-poseidon-merkle",
        .description = "Check canonical Poseidon transcript and scalar/SIMD Merkle parity",
        .root = "poseidon_merkle_test_root.zig",
        .imports_prover_engine = true,
        .filters = &.{ "recursion Poseidon2:", "memory Poseidon2:" },
        .minimum = 19,
    },
    .{
        .step = "test-keccakf-row",
        .description = "Run only the shared Keccak row scalar parity and lazy-error regression",
        .root = "keccakf_precompile_test_root.zig",
        .imports_prover_engine = true,
        .filters = &.{"Keccak shared row preserves scalar constraint values degrees and lazy errors"},
        .minimum = 2, // One named check plus the unnamed import root.
    },
    .{
        .step = "test-keccakf-precompile",
        .description = "Run the Keccak-f semantic and paired-witness authority tests",
        .root = "keccakf_precompile_test_root.zig",
        .imports_prover_engine = true,
        .minimum = 4,
    },
    .{
        .step = "test-secp256k1-precompile",
        .description = "Run compact secp256k1 field and precompile authority tests",
        .root = "secp256k1_precompile_test_root.zig",
        .imports_prover_engine = true,
        .minimum = 34,
    },
    .{
        .step = "test-interaction-trace-plan",
        .description = "Run the prepared Tree-2 planning and execution tests",
        .root = "interaction_trace_plan_execution_test_root.zig",
        .imports_prover_engine = true,
    },
    .{
        .step = "test-recursion-transcript-v2",
        .description = "Run exact generic-channel V2 scheduled transcript parity tests",
        .root = "transcript_v2_test_root.zig",
        .imports_prover_engine = true,
    },
    .{
        .step = "test-recursion-v3-tree0-link",
        .description = "Run the non-activating verifier-owned V3 Tree0 field-link tests",
        .root = "tree0_field_link_v3_test.zig",
        .imports_prover_engine = true,
        .filters = &.{"Tree0"},
        .minimum = 6,
    },
    .{
        .step = "test-recursion-pair-node",
        .description = "Run the authenticated native R-009 pair-node boundary tests",
        .root = "pair_node_test_root.zig",
        .imports_prover_engine = true,
    },
    .{
        .step = "test-recursion-temporal-pair",
        .description = "Run the V2 adjacent-span temporal pair authority tests",
        .root = "temporal_pair_node_test_root.zig",
        .imports_prover_engine = true,
    },
    .{
        .step = "test-recursion-vm-composition",
        .description = "Run only the row-18 VM AIR authority and composition graph tests",
        .root = "recursion_vm_composition_test_root.zig",
        .imports_prover_engine = true,
    },
    .{
        .step = "test-recursion-composition-recorder",
        .description = "Run the compile-isolated authenticated AIR graph recorder tests",
        .root = "recursion_air_r012_composition_circuit_dev_test_root.zig",
        .imports_prover_engine = true,
    },
    .{
        .step = "test-recursion-segment-leaf-outer-v2",
        .description = "Run the authenticated V2 segment-leaf outer authority tests",
        .root = "segment_leaf_outer_authority_v2_test_root.zig",
        .imports_prover_engine = true,
    },
    .{
        .step = "test-recursion-segment-transcript-source-v2",
        .description = "Run the V2 scheduled-transcript outer source tests",
        .root = "segment_transcript_outer_source_v2_test_root.zig",
        .imports_prover_engine = true,
    },
    .{
        .step = "test-recursion-segment-transcript-components-v2",
        .description = "Run the V2 rows 0 through 9 component and tree-writer gates",
        .root = "segment_transcript_outer_components_v2_test_root.zig",
        .imports_prover_engine = true,
    },
    .{
        .step = "test-segment-statement-v2",
        .description = "Run only SegmentV2 boundary and continuation-root tests",
        .root = "segment_statement_v2_test_root.zig",
        .filters = &.{ "segment statement V2", "V2 transcript layout", "native authority preimage", "access clock:" },
        .minimum = 23,
    },
    .{
        .step = "test-recursion-segment-statement-source-v2",
        .description = "Run the V2 rows 10 and 11 statement authority gates",
        .root = "segment_statement_outer_source_v2_test_root.zig",
        .imports_prover_engine = true,
        .filters = &.{"V2 row-11"},
        .minimum = 3,
    },
    .{
        .step = "test-recursion-segment-public-source-v2",
        .description = "Run the V2 rows 12 through 17 public-spine source gates",
        .root = "segment_public_outer_source_v2_test_root.zig",
        .imports_prover_engine = true,
        .filters = &.{ "V2 public spine", "V2 public-spine" },
        .minimum = 5,
    },
    .{
        .step = "test-recursion-segment-claim-hash-v2",
        .description = "Check dynamic statement-authority hashing and fixed preprocessing",
        .root = "vm_public_claim_hash_authority_v2_test_root.zig",
        .imports_prover_engine = true,
        .filters = &.{"isolated row13 V2"},
        .minimum = 2,
    },
    .{
        .step = "test-recursion-segment-native-sum-v2",
        .description = "Run the SegmentV2 native-sum graph and register-input authority gates",
        .root = "segment_public_native_sum_authority_v2_test_root.zig",
        .imports_prover_engine = true,
        .filters = &.{ "SegmentV2 native-sum", "SegmentV2 publication provider plan" },
        .minimum = 9,
    },
    .{
        .step = "test-recursion-segment-public-components-v2",
        .description = "Run the V2 public-spine typed AIR and component gates",
        .root = "segment_public_outer_components_v2_test_root.zig",
        .imports_prover_engine = true,
    },
    .{
        .step = "test-recursion-segment-publication-provider-v2",
        .description = "Run the committed SegmentV2 verifier-input provider authority tests",
        .root = "segment_publication_input_provider_authority_v2_test_root.zig",
        .imports_prover_engine = true,
        .filters = &.{ "publication-input provider", "capture-backed provider", "committed provider", "both authenticated inputs", "publication provider" },
        .minimum = 10,
    },
    .{
        .step = "test-recursion-segment-outer-manifest-v2",
        .description = "Run the versioned 38-component segment outer manifest tests",
        .root = "segment_outer_adapter_manifest_v2_test_root.zig",
        .imports_prover_engine = true,
    },
    .{
        .step = "test-recursion-segment-outer-cohort-v2",
        .description = "Run the strict 38-row SegmentV2 cohort and shared-schedule gates",
        .root = "segment_outer_cohort_v2_test_root.zig",
        .imports_prover_engine = true,
    },
    .{
        .step = "test-recursion-segment-outer-noncore-audits-v2",
        .description = "Run exact-domain custody for SegmentV2 non-core Tree-2 rows",
        .root = "segment_outer_noncore_audits_v2_test_root.zig",
        .imports_prover_engine = true,
        .filters = &.{ "non-core custody", "family and domain mutations" },
        .minimum = 5,
    },
    .{
        .step = "test-recursion-segment-boundary-components-v2",
        .description = "Run the concrete V2 boundary source component adapter tests",
        .root = "segment_boundary_components_v2_test_root.zig",
        .imports_prover_engine = true,
    },
    .{
        .step = "test-recursion-fri-profile-measurements",
        .description = "Run exact receipt-backed frozen-V1 to V1.1 FRI profile comparisons",
        .root = "fri_profile_frontier_measurement_test_root.zig",
    },
    .{
        .step = "test-recursion-parent-transcript-source",
        .description = "Run the authenticated two-child parent transcript source tests",
        .root = "outer_parent_transcript_source_test_root.zig",
        .imports_prover_engine = true,
    },
    .{
        .step = "test-recursion-parent-statement-source",
        .description = "Run the authenticated two-child parent statement source tests",
        .root = "outer_parent_statement_source_test_root.zig",
        .imports_prover_engine = true,
    },
    .{
        .step = "test-recursion-binary-closure",
        .description = "Run only the binary-parent all-row global LogUp closure",
        .root = "binary_global_closure_outer_source_test_root.zig",
        .imports_prover_engine = true,
    },
    .{
        .step = "test-recursion-framework-interaction",
        .description = "Run interaction column/domain parity, workspace and failure-atomicity checks",
        .root = "framework_interaction_test_root.zig",
        .imports_prover_engine = true,
        .filters = &.{"R-012 framework"},
        .minimum = 3,
    },
    .{
        .step = "test-recursion-framework-export",
        .description = "Compare backend polynomial export with authenticated recursive AIR plans",
        .root = "recursion_framework_export_test_root.zig",
        .imports_prover_engine = true,
    },
    .{
        .step = "test-recursion-arithmetic-fusion",
        .description = "Check fused verifier arithmetic and authenticated graph lowering",
        .root = "recursion_arithmetic_fusion_test_root.zig",
        .imports_prover_engine = true,
    },
    .{
        .step = "test-recursion-opening-accumulation",
        .description = "Check fused opening accumulation and exact wire fanout",
        .root = "recursion_opening_accumulation_test_root.zig",
        .imports_prover_engine = true,
    },
    .{
        .step = "test-poseidon-universal-degree3",
        .description = "Check compact universal Poseidon AIR against the retained permutation",
        .root = "poseidon2_universal_degree3_test_root.zig",
        .imports_prover_engine = true,
    },
};
