//! Ordered standalone frontend test catalog; build.zig owns module construction.
//! Roots, filters and count floors stay together for focused edit loops.

pub const Spec = struct {
    step: []const u8,
    description: []const u8,
    root: []const u8,
    imports_prover_engine: bool = false,
    imports_typed_air_artifacts: bool = false,
    filters: []const []const u8 = &.{},
    minimum: usize = 0,
    strip: ?bool = null,
};

pub const specs = [_]Spec{
    .{
        .step = "test-legacy-interaction-oracle",
        .description = "Check retired interaction generation and retained memory layouts",
        .root = "air_semantics_test_root.zig",
        .filters = &.{ "interaction_gen:", "opcode memory:" },
        .minimum = 5,
    },
    .{
        .step = "test-infrastructure-component",
        .description = "Check program/memory work profiles, prepared evaluation and allocation rollback",
        .root = "infrastructure_component_test_root.zig",
        .imports_prover_engine = true,
        .filters = &.{ "component:", "RISC-V component keeps legacy" },
        .minimum = 7,
    },
    .{
        .step = "test-execution-session",
        .description = "Check typed execution, host handling and continuation contracts",
        .root = "runner_test_root.zig",
        .filters = &.{ "runner:", "generated retirement registry", "singular production authorities", "production source is singular", "HostRuntime:", "SyscallNr known values" },
        .minimum = 12,
    },
    .{
        .step = "test-detached-boundary",
        .description = "Check detached boundary identities, memory roots, clock ordering and witness mutations",
        .root = "detached_boundary_test_root.zig",
        .imports_prover_engine = true,
        .filters = &.{"detached boundary arithmetic"},
        .minimum = 3, // Arithmetic/mutation check plus import discovery.
    },
    .{
        .step = "test-vm-air-profile-authority-v2",
        .description = "Check VM profile identity and authority without composition-program or provider-shard tests",
        .root = "vm_air_profile_authority_v2_test_root.zig",
        .imports_prover_engine = true,
        .filters = &.{"authenticated VM AIR ProfileV2"},
        .minimum = 6, // Three authority checks plus three import-discovery tests.
    },
    .{
        .step = "test-isa",
        .description = "Run only RISC-V ISA authority and decoder tests",
        .root = "isa_test_root.zig",
    },
    .{
        .step = "test-runner",
        .description = "Run only RISC-V execution-runner tests",
        .root = "runner_test_root.zig",
    },
    .{
        .step = "test-minimal-trace-parallel-replay",
        .description = "Run only the bounded parallel minimal-trace replay gate",
        .root = "runner_test_root.zig",
        .filters = &.{"minimal trace: bounded parallel replay preserves canonical leaf order"},
        .minimum = 1,
    },
    .{
        .step = "benchmark-minimal-trace-parallel-replay",
        .description = "Measure bounded parallel minimal-trace replay scaling",
        .root = "runner_test_root.zig",
        .filters = &.{"minimal trace: parallel replay reports bounded scaling"},
        .minimum = 1,
    },
    .{
        .step = "test-ethereum-runner",
        .description = "Run the combined Ethereum profile and signer-recovery runner tests",
        .root = "ethereum_runner_test_root.zig",
        .minimum = 11,
    },
    .{
        .step = "test-ethereum-minimal-trace",
        .description = "Run compact Ethereum minimal-trace capture and replay tests",
        .root = "ethereum_minimal_trace_test_root.zig",
        .filters = &.{"Ethereum minimal trace compacts and independently replays both native calls"},
        .minimum = 1,
    },
    .{
        .step = "test-main-trace-plan-execution",
        .description = "Run only bounded main-trace plan and production execution tests",
        .root = "main_trace_plan_execution_test_root.zig",
        .imports_prover_engine = true,
    },
    .{
        .step = "test-poseidon-witness-work",
        .description = "Run exact sparse-memory and guest-Poseidon work-receipt tests",
        .root = "poseidon_witness_work_test_root.zig",
        .imports_prover_engine = true,
        .minimum = 8,
    },
    .{
        .step = "test-interaction-witness-work",
        .description = "Run exact relation-challenge and Tree-2 work-receipt tests",
        .root = "interaction_witness_work_test_root.zig",
        .imports_prover_engine = true,
        .minimum = 3,
    },
    .{
        .step = "test-compact-poseidon-authority",
        .description = "Run compact typed lowering, specialization identity and allocation checks",
        .root = "compact_poseidon_authority_test_root.zig",
        .imports_prover_engine = true,
        .minimum = 8,
    },
    .{
        .step = "test-polynomial-compiler",
        .description = "Check shared polynomial lowering, fixed shells and degree-bounded consumers",
        .root = "polynomial_compiler_test_root.zig",
        .imports_prover_engine = true,
        .minimum = 5,
    },
    .{
        .step = "test-wide-poseidon-authority",
        .description = "Check all typed wide Poseidon equations, events and shared witness authority",
        .root = "wide_poseidon_authority_test_root.zig",
        .imports_prover_engine = true,
        .minimum = 3,
    },
    .{
        .step = "test-native-boundary-authority",
        .description = "Check typed program, memory, clock and lookup policy equations and admission",
        .root = "native_boundary_authority_test_root.zig",
        .imports_prover_engine = true,
        .minimum = 4,
    },
    .{
        .step = "test-merkle-authority",
        .description = "Check typed native Merkle equations, lookup order and specialization rejection",
        .root = "merkle_authority_test_root.zig",
        .imports_prover_engine = true,
        .minimum = 3,
    },
    .{
        .step = "test-parent-canonical-admission",
        .description = "Run parent canonical AIR admission, rejection and protocol identity checks",
        .root = "poseidon2_protocol_identity_test_root.zig",
        .imports_prover_engine = true,
        .minimum = 6,
    },
    .{
        .step = "test-trace-authority",
        .description = "Run trace admission, typed ownership and retired-oracle differential checks",
        .root = "trace_authority_test_root.zig",
        .minimum = 25,
    },
    .{
        .step = "test-air-semantics",
        .description = "Run only RISC-V instruction-family AIR tests",
        .root = "air_semantics_test_root.zig",
        .imports_prover_engine = true,
    },
    .{
        .step = "test-load-store-private",
        .description = "Run focused load/store AIR authority and retirement tests",
        .root = "load_store_private_test_root.zig",
        .minimum = 19,
    },
    .{
        .step = "test-register-read-alias-private",
        .description = "Run nonproduction register-read alias candidate tests",
        .root = "register_read_alias_test_root.zig",
        .minimum = 4,
    },
    .{
        .step = "test-two-read-register-alias-private",
        .description = "Run nonproduction two-read register alias candidate tests",
        .root = "two_read_register_alias_test_root.zig",
        .minimum = 5,
    },
    .{
        .step = "test-vm-public-claim",
        .description = "Check canonical claim geometry, witness parity, transport binding and allocation cleanup",
        .root = "recursion_protocol_test_root.zig",
        .imports_prover_engine = true,
        .filters = &.{ "R-012 VM public claim", "R-012 direct transport", "R-012 clock-free transport" },
        .minimum = 6,
    },
    .{
        .step = "test-recursion-native-parity",
        .description = "Check native/recursive memory and PCS parity plus claim mutations",
        .root = "recursion_protocol_test_root.zig",
        .imports_prover_engine = true,
        .filters = &.{ "RISC-V component keeps legacy", "R-012 PCS-DEEP", "R-012 claim semantics", "R-012 continuation IO" },
        .minimum = 15,
    },
    .{
        .step = "test-semantic-component",
        .description = "Run only semantic-component prepared-domain and resource tests",
        .root = "semantic_component_test_root.zig",
        .imports_prover_engine = true,
        .filters = &.{ "semantic component", "semantic prepared" },
        .minimum = 8,
    },
    .{
        .step = "test-hash-component-prepared",
        .description = "Run only memory-hash prepared-domain and stack-certificate tests",
        .root = "hash_component_prepared_test_root.zig",
        .imports_prover_engine = true,
        .minimum = 9,
    },
    .{
        .step = "test-air-static-profile",
        .description = "Run only typed-AIR static profiler tests",
        .root = "air_static_profile_test_root.zig",
    },
    .{
        .step = "test-air-static-profile-registry",
        .description = "Run the complete native typed-AIR static profile registry",
        .root = "air_static_profile_registry_test_root.zig",
        .imports_typed_air_artifacts = true,
    },
    .{
        .step = "test-air-runtime-profile",
        .description = "Run the authenticated typed-AIR/runtime profile join tests",
        .root = "air_runtime_profile_test_root.zig",
    },
    .{
        .step = "test-proof-phase-meter",
        .description = "Run the exact five-region witness/proving phase-meter state machine",
        .root = "proof_phase_meter_test_root.zig",
    },
    .{
        .step = "test-air-function-frames",
        .description = "Run Cairo-style frame isolation and activation-relation tests",
        .root = "air_function_frames_test_root.zig",
    },
    .{
        .step = "test-air-function-body-lowering",
        .description = "Run bounded authenticated inline-function body lowering tests",
        .root = "air_function_body_lowering_test_root.zig",
    },
    .{
        .step = "test-air-function-body-ownership",
        .description = "Run sealed per-function body ownership and lowering tests",
        .root = "air_function_body_ownership_test_root.zig",
    },
    .{
        .step = "test-air-function-activation-logup",
        .description = "Run live compiler-owned function activation LogUp tests",
        .root = "air_function_activation_logup_test_root.zig",
        .imports_prover_engine = true,
    },
    .{
        .step = "test-lookup-batching",
        .description = "Run compiler-selected LogUp planning and row execution tests",
        .root = "lookup_batch_test_root.zig",
        .imports_prover_engine = true,
        // A-014 cannot advance on an empty shadow-planner binary. Keep the
        // authority, collision, differential, and execution inventory wired.
        .minimum = 16,
    },
    .{
        .step = "test-lookup-source-ingest",
        .description = "Run exact opcode-source ingestion and rollback tests",
        .root = "lookup_source_ingest_test_root.zig",
        .imports_prover_engine = true,
        .minimum = 5,
    },
    .{
        .step = "test-lookup-table-framework-export",
        .description = "Check native fixed-table backend export and ownership without proving",
        .root = "lookup_table_interaction_test_root.zig",
        .filters = &.{"native table framework"},
        .imports_prover_engine = true,
        .minimum = 4,
    },
    .{
        .step = "test-lookup-table-interaction",
        .description = "Run lookup-table interaction parity and rollback tests",
        .root = "lookup_table_interaction_test_root.zig",
        .imports_prover_engine = true,
        .minimum = 9,
    },
    .{
        .step = "test-opcode-interaction",
        .description = "Run scalar/packed opcode interaction parity and rollback tests",
        .root = "opcode_interaction_test_root.zig",
        .imports_prover_engine = true,
        .minimum = 11,
    },
    .{
        .step = "test-lookup-batching-edit",
        .description = "Run the lightweight authenticated lookup-batch planner edit loop",
        .root = "lookup_batch_edit_test_root.zig",
        .filters = &.{"lookup batch planner:"},
        .minimum = 7,
    },
    .{
        .step = "test-lookup-polynomial-v2-edit",
        .description = "Run the lightweight variable-partition polynomial-authority edit loop",
        .root = "lookup_polynomial_v2_edit_test_root.zig",
        .imports_prover_engine = true,
        .filters = &.{"lookup polynomial v2:"},
        .minimum = 4,
    },
    .{
        .step = "test-row-windows",
        .description = "Run compiler-owned row-window, mask, and ownership tests",
        .root = "row_window_test_root.zig",
        .imports_prover_engine = true,
        // A-013 spans both row-window authority and its production component
        // consumer; losing either half invalidates the focused closure gate.
        .minimum = 16,
    },
    .{
        .step = "test-row-windows-edit",
        .description = "Run the lightweight typed row-window authority edit loop",
        .root = "row_window_edit_test_root.zig",
        .filters = &.{"row-window v1:"},
        .minimum = 10,
    },
    .{
        .step = "test-row-window-expressions-v2-edit",
        .description = "Run the lightweight shifted-expression authority edit loop",
        .root = "row_window_expression_v2_edit_test_root.zig",
        .filters = &.{"row-window expression v2:"},
        .minimum = 5,
    },
    .{
        .step = "test-guest-precompile",
        .description = "Run only proof-side guest-precompile protocol tests",
        .root = "guest_precompile_test_root.zig",
        .imports_prover_engine = true,
    },
    .{
        .step = "test-bulk-memcpy-candidate",
        .description = "Run the nonproduction word-granular memcpy AIR candidate tests",
        .root = "bulk_memcpy_candidate_test_root.zig",
        .minimum = 6,
    },
    .{
        .step = "test-stack-swap-candidate",
        .description = "Run the nonproduction SWAP1..SWAP16 semantic and AIR candidate tests",
        .root = "stack_swap_candidate_test_root.zig",
        .minimum = 7,
    },
    .{
        .step = "test-ethereum-candidate-execution-contract",
        .description = "Run combined candidate registry, capability, journal, and product tests",
        .root = "ethereum_candidate_execution_contract_test_root.zig",
        .filters = &.{"combined candidate contract v1:"},
        .minimum = 5,
    },
    .{
        .step = "test-ethereum-candidate-leaf",
        .description = "Run candidate leaf profile, tree, and admission authority tests",
        .root = "ethereum_candidate_leaf_test_root.zig",
        .imports_prover_engine = true,
        .minimum = 5,
    },
    .{
        .step = "test-ethereum-candidate-provider",
        .description = "Run candidate shared-transcript and degree-five provider adapter tests",
        .root = "ethereum_candidate_provider_test_root.zig",
        .imports_prover_engine = true,
        .minimum = 2,
    },
    .{
        .step = "test-ethereum-omit-validated-parity",
        .description = "Run validated-vs-unvalidated omission-path parity tests",
        .root = "ethereum_omit_validated_parity_test_root.zig",
        .imports_prover_engine = true,
        .minimum = 5,
    },
    .{
        .step = "test-incremental-ethereum-omit-protocol-v4",
        .description = "Run the omitted-provider V4 route pin, frame, and leaf authority tests",
        .root = "incremental_ethereum_omit_protocol_v4_test_root.zig",
        .imports_prover_engine = true,
        .filters = &.{"incremental omission route v4:"},
        .minimum = 7,
    },
    .{
        .step = "test-incremental-ethereum-omit-orchestration-v4",
        .description = "Run the omitted-provider V4 orchestration prologue, geometry, transcript, and binding tests",
        .root = "incremental_ethereum_omit_orchestration_v4_test_root.zig",
        .imports_prover_engine = true,
        .filters = &.{"incremental omitted orchestration v4:"},
        .minimum = 6,
    },
    .{
        .step = "test-ethereum-matched-ab-omitted-provider-policy",
        .description = "Run matched omitted-provider geometry, plan, and fresh-closure authority tests",
        .root = "ethereum_matched_ab_omitted_provider_policy_test_root.zig",
        .imports_prover_engine = true,
        .minimum = 3,
    },
    .{
        .step = "test-sha256-pair-candidate",
        .description = "Run the nonproduction fixed64 SHA-256 pair AIR and caller tests",
        .root = "sha256_pair_candidate_test_root.zig",
        .minimum = 8,
    },
    .{
        .step = "test-poseidon-merkle",
        .description = "Check canonical Poseidon transcript and scalar/SIMD Merkle parity",
        .root = "poseidon_merkle_test_root.zig",
        .imports_prover_engine = true,
        .filters = &.{ "recursion Poseidon2:", "memory Poseidon2:" },
        .minimum = 19,
    },
    .{
        .step = "test-keccakf-row",
        .description = "Run only the shared Keccak row scalar parity and lazy-error regression",
        .root = "keccakf_precompile_test_root.zig",
        .imports_prover_engine = true,
        .filters = &.{"Keccak shared row preserves scalar constraint values degrees and lazy errors"},
        .minimum = 2, // One named check plus the unnamed import root.
    },
    .{
        .step = "test-keccakf-precompile",
        .description = "Run the Keccak-f semantic and paired-witness authority tests",
        .root = "keccakf_precompile_test_root.zig",
        .imports_prover_engine = true,
        .minimum = 4,
    },
    .{
        .step = "test-secp256k1-precompile",
        .description = "Run compact secp256k1 field and precompile authority tests",
        .root = "secp256k1_precompile_test_root.zig",
        .imports_prover_engine = true,
        .minimum = 34,
    },
    .{
        .step = "test-interaction-trace-plan",
        .description = "Run the prepared Tree-2 planning and execution tests",
        .root = "interaction_trace_plan_execution_test_root.zig",
        .imports_prover_engine = true,
    },
    .{
        .step = "test-recursion-protocol",
        .description = "Run the frozen recursion protocol and native boundary tests",
        .root = "recursion_protocol_test_root.zig",
        .imports_prover_engine = true,
    },
    .{
        .step = "test-ethereum-native-root-claim",
        .description = "Check native-root claim semantics and exact row11/row15 source ownership",
        .root = "recursion_protocol_test_root.zig",
        .imports_prover_engine = true,
        .filters = &.{
            "Ethereum native root claim semantics separates snapshot digests and requires row11 wires",
            "R-012 claim semantics SegmentV2 keeps continuation IO in statement relations",
            "Ethereum statement arithmetic owns admitted graphs and rejects stale evaluations",
        },
        .minimum = 3,
    },
    .{
        .step = "test-ethereum-initial-manifest",
        .description = "Check initial input component admission and preserve legacy claim and adapter protocol",
        .root = "recursion_air_core_test_root.zig",
        .imports_prover_engine = true,
        .filters = &.{
            "Ethereum initial manifest",
            "R-012 universal manifest pins roster order offsets claims and transcript",
            "R-012 generic adapter exposes a sealed outer proof gate",
        },
        .minimum = 4,
    },
    .{
        .step = "test-recursion-transcript-v2",
        .description = "Run exact generic-channel V2 scheduled transcript parity tests",
        .root = "transcript_v2_test_root.zig",
        .imports_prover_engine = true,
    },
    .{
        .step = "test-recursion-pair-node",
        .description = "Run the authenticated native R-009 pair-node boundary tests",
        .root = "pair_node_test_root.zig",
        .imports_prover_engine = true,
    },
    .{
        .step = "test-ethereum-cold-wire-admission",
        .description = "Authenticate fresh Ethereum canonical wire once with immutable ownership and hostile input checks",
        .root = "temporal_pair_node_test_root.zig",
        .imports_prover_engine = true,
        .filters = &.{"public data V2"},
        .minimum = 7,
    },
    .{
        .step = "test-recursion-temporal-pair",
        .description = "Run the V2 adjacent-span temporal pair authority tests",
        .root = "temporal_pair_node_test_root.zig",
        .imports_prover_engine = true,
    },
    .{
        .step = "test-recursion-vm-composition",
        .description = "Run only the row-18 VM AIR authority and composition graph tests",
        .root = "recursion_vm_composition_test_root.zig",
        .imports_prover_engine = true,
    },
    .{
        .step = "test-recursion-preparation",
        .description = "Check composition ownership, statement routing closure and legacy provider compatibility",
        .root = "recursion_preparation_test_root.zig",
        .imports_prover_engine = true,
        .filters = &.{
            "ethereum row12",
            "ethereum publication hash",
            "Ethereum publication control",
            "Ethereum native publication",
            "Ethereum role input",
            "composition ownership separates immutable structure inputs and consumer views",
            "Ethereum statement arithmetic owns admitted graphs and rejects stale evaluations",
            "composition finalization frees every allocation on rejection and OOM",
            "composition borrowed admission retains mutation checks and matches frozen data",
            "VM statement root profile preserves legacy ordering and rejects ambiguous admission",
            "VM statement root rows consume the canonical statement relation",
            "VM field binding publishers preserve V1 words and reject root profile before writing",
            "statement root routing authenticates fixed multiplicities without changing V2",
            "statement root routing closes actual AIR consumers and rejects missing duplicate altered roots",
            "R-012 statement input",
            "R-012 statement semantics",
            "R-012 canonical statement integer",
            "R-012 row-10 scoped emission",
            "statement root physical admission matches native and recursive evaluation",
            "statement root catalog derives the full physical manifest without changing legacy rows",
        },
        .minimum = 41,
    },
    .{
        .step = "test-recursion-composition-recorder",
        .description = "Run the compile-isolated authenticated AIR graph recorder tests",
        .root = "recursion_air_r012_composition_circuit_dev_test_root.zig",
        .imports_prover_engine = true,
    },
    .{
        .step = "test-recursion-composition-v3",
        .description = "Run the versioned 39+2 shared recursion composition authority tests",
        .root = "recursion_air_composition_v3_test_root.zig",
        .imports_prover_engine = true,
    },
    .{
        .step = "test-recursion-composition-v3-session",
        .description = "Run only the V3 universal orchestration and heterogeneous-session tests",
        .root = "recursion_air_composition_v3_test_root.zig",
        .imports_prover_engine = true,
        // A child-only filter can exclude the root test that imports the child
        // modules, so those named tests are never discovered. One shared V3
        // prefix selects the root compile gate, six authority/session tests,
        // and the V3.1 active-empty E2E. The floor makes import/filter drift
        // fail instead of running zero.
        .filters = &.{"V3"},
        .minimum = 8,
    },
    .{
        .step = "test-recursion-outer-sources",
        .description = "Run only segment outer-proof sources for rows 0 through 17 and 35",
        .root = "recursion_outer_sources_test_root.zig",
        .imports_prover_engine = true,
    },
    .{
        .step = "test-recursion-binary-transcript-source",
        .description = "Run only the binary-node rows 0 through 9 source tests",
        .root = "binary_transcript_outer_source_test_root.zig",
        .imports_prover_engine = true,
    },
    .{
        .step = "test-recursion-segment-leaf-bundle",
        .description = "Run only the composed segment-leaf outer bundle",
        .root = "segment_leaf_outer_bundle_test_root.zig",
        .imports_prover_engine = true,
        .filters = &.{"R-012 segment-leaf bundle"},
        .minimum = 4,
    },
    .{
        .step = "test-recursion-segment-leaf-outer-v2",
        .description = "Run the authenticated V2 segment-leaf outer authority tests",
        .root = "segment_leaf_outer_authority_v2_test_root.zig",
        .imports_prover_engine = true,
    },
    .{
        .step = "test-recursion-segment-transcript-source-v2",
        .description = "Run the V2 scheduled-transcript outer source tests",
        .root = "segment_transcript_outer_source_v2_test_root.zig",
        .imports_prover_engine = true,
    },
    .{
        .step = "test-recursion-segment-transcript-components-v2",
        .description = "Run the V2 rows 0 through 9 component and tree-writer gates",
        .root = "segment_transcript_outer_components_v2_test_root.zig",
        .imports_prover_engine = true,
    },
    .{
        .step = "test-segment-statement-v2",
        .description = "Run only SegmentV2 boundary and continuation-root tests",
        .root = "segment_statement_v2_test_root.zig",
        .filters = &.{ "segment statement V2", "V2 transcript layout", "native authority preimage", "access clock:" },
        .minimum = 23,
    },
    .{
        .step = "test-recursion-segment-statement-source-v2",
        .description = "Run the V2 rows 10 and 11 statement authority gates",
        .root = "segment_statement_outer_source_v2_test_root.zig",
        .imports_prover_engine = true,
        .filters = &.{"V2 row-11"},
        .minimum = 3,
    },
    .{
        .step = "test-recursion-segment-public-source-v2",
        .description = "Run the V2 rows 12 through 17 public-spine source gates",
        .root = "segment_public_outer_source_v2_test_root.zig",
        .imports_prover_engine = true,
        .filters = &.{ "V2 public spine", "V2 public-spine" },
        .minimum = 5,
    },
    .{
        .step = "test-recursion-segment-claim-hash-v2",
        .description = "Check dynamic statement-authority hashing and fixed preprocessing",
        .root = "vm_public_claim_hash_authority_v2_test_root.zig",
        .imports_prover_engine = true,
        .filters = &.{"isolated row13 V2"},
        .minimum = 2,
    },
    .{
        .step = "test-recursion-segment-native-sum-v2",
        .description = "Run the SegmentV2 native-sum graph and register-input authority gates",
        .root = "segment_public_native_sum_authority_v2_test_root.zig",
        .imports_prover_engine = true,
        .filters = &.{ "SegmentV2 native-sum", "SegmentV2 publication provider plan" },
        .minimum = 9,
    },
    .{
        .step = "test-recursion-segment-public-components-v2",
        .description = "Run the V2 public-spine typed AIR and component gates",
        .root = "segment_public_outer_components_v2_test_root.zig",
        .imports_prover_engine = true,
    },
    .{
        .step = "test-recursion-segment-publication-provider-v2",
        .description = "Run the committed SegmentV2 verifier-input provider authority tests",
        .root = "segment_publication_input_provider_authority_v2_test_root.zig",
        .imports_prover_engine = true,
        .filters = &.{ "publication-input provider", "capture-backed provider", "committed provider", "both authenticated inputs", "publication provider" },
        .minimum = 10,
    },
    .{
        .step = "test-recursion-segment-outer-manifest-v2",
        .description = "Run the versioned 38-component segment outer manifest tests",
        .root = "segment_outer_adapter_manifest_v2_test_root.zig",
        .imports_prover_engine = true,
    },
    .{
        .step = "test-recursion-segment-outer-cohort-v2",
        .description = "Run the strict 38-row SegmentV2 cohort and shared-schedule gates",
        .root = "segment_outer_cohort_v2_test_root.zig",
        .imports_prover_engine = true,
    },
    .{
        .step = "test-recursion-segment-outer-noncore-audits-v2",
        .description = "Run exact-domain custody for SegmentV2 non-core Tree-2 rows",
        .root = "segment_outer_noncore_audits_v2_test_root.zig",
        .imports_prover_engine = true,
        .filters = &.{ "non-core custody", "family and domain mutations" },
        .minimum = 5,
    },
    .{
        .step = "test-recursion-segment-boundary-components-v2",
        .description = "Run the concrete V2 boundary source component adapter tests",
        .root = "segment_boundary_components_v2_test_root.zig",
        .imports_prover_engine = true,
    },
    .{
        .step = "test-recursion-fri-profile-measurements",
        .description = "Run exact receipt-backed frozen-V1 to V1.1 FRI profile comparisons",
        .root = "fri_profile_frontier_measurement_test_root.zig",
    },
    .{
        .step = "test-recursion-parent-transcript-source",
        .description = "Run the authenticated two-child parent transcript source tests",
        .root = "outer_parent_transcript_source_test_root.zig",
        .imports_prover_engine = true,
    },
    .{
        .step = "test-recursion-parent-statement-source",
        .description = "Run the authenticated two-child parent statement source tests",
        .root = "outer_parent_statement_source_test_root.zig",
        .imports_prover_engine = true,
    },
    .{
        .step = "test-recursion-binary-nonfri",
        .description = "Run only the binary-parent rows 0 through 17 and row 35 bundle",
        .root = "binary_pair_nonfri_outer_bundle_test_root.zig",
        .imports_prover_engine = true,
    },
    .{
        .step = "test-recursion-binary-fri",
        .description = "Run only the binary-parent rows 18 through 34 authority",
        .root = "binary_fri_outer_source_test_root.zig",
        .imports_prover_engine = true,
    },
    .{
        .step = "test-riscv-recursion-binary-fri-outer-bundle-v2",
        .description = "Run the binary-pair V2 rows 18 through 34 shared-provider gates",
        .root = "binary_fri_outer_bundle_v2_test_root.zig",
        .imports_prover_engine = true,
        .filters = &.{
            "V2 rows 18 through 34 bind",
            "native schedule receipt completes",
            "V2 bundle public contract",
            "V2 binary-pair owner",
        },
        .minimum = 4,
    },
    .{
        .step = "test-recursion-binary-fri-row18",
        .description = "Run only row 18/19 committed-layout and composition custody",
        .root = "binary_fri_outer_source_test_root.zig",
        .imports_prover_engine = true,
        .filters = &.{ "R-015 binary FRI rows 18--19 use the admitted composition graph", "retained relation rows preserve little-endian digest bytes" },
        .minimum = 2,
    },
    .{
        .step = "test-recursion-binary-closure",
        .description = "Run only the binary-parent all-row global LogUp closure",
        .root = "binary_global_closure_outer_source_test_root.zig",
        .imports_prover_engine = true,
    },
    .{
        .step = "test-recursion-quotient-domains",
        .description = "Check typed AIR quotient domains against retained PCS sources",
        .root = "recursion_air_core_test_root.zig",
        .imports_prover_engine = true,
        .filters = &.{ "R-012 generic adapter", "Ethereum typed quotient domains" },
        .minimum = 5,
    },
    .{
        .step = "test-recursion-schedule-admission",
        .description = "Check admitted verifier schedules and FRI control ownership",
        .root = "recursion_air_core_test_root.zig",
        .imports_prover_engine = true,
        .filters = &.{ "R-012 verifier schedule", "R-012 verifier plan", "R-012 frozen verifier programs", "R-012 candidate schedule", "R-012 FRI verifier control" },
        .minimum = 14,
    },
    .{
        .step = "test-recursion-air-edit",
        .description = "Run only named R-012 recursion tests for the shortest edit loop",
        .root = "recursion_air_core_test_root.zig",
        .imports_prover_engine = true,
        .filters = &.{"R-012"},
        .minimum = 1,
    },
    .{
        .step = "test-recursion-framework-interaction",
        .description = "Run interaction column/domain parity, workspace and failure-atomicity checks",
        .root = "framework_interaction_test_root.zig",
        .filters = &.{"R-012 framework"},
        .minimum = 2,
    },
    .{
        .step = "test-recursion-air-row18",
        .description = "Run only row-18 VM AIR composition-input identity and witness tests",
        .root = "recursion_air_core_test_root.zig",
        .imports_prover_engine = true,
        .filters = &.{"R-012 VM AIR composition"},
        .minimum = 1,
    },
    .{
        .step = "test-recursion-temporal-packed-relation",
        .description = "Run only the temporal V2 packed relation-challenge ABI gate",
        .root = "recursion_air_core_test_root.zig",
        .imports_prover_engine = true,
        .filters = &.{"temporal packed relation-challenge V2"},
        .minimum = 1,
    },
    .{
        .step = "test-recursion-air-roster",
        .description = "Run only universal recursion inventory and manifest pin tests",
        .root = "recursion_air_core_test_root.zig",
        .imports_prover_engine = true,
        .filters = &.{
            "R-012 recursion typed-AIR inventory",
            "R-012 universal manifest",
        },
        .minimum = 2,
    },
    .{
        .step = "test-recursion-direct-execution",
        .description = "Compare pruned direct execution with canonical parent AIR programs",
        .root = "recursion_air_core_test_root.zig",
        .imports_prover_engine = true,
        .filters = &.{ "R-012 direct", "R-012 universal challenge" },
        .minimum = 6,
    },
    .{
        .step = "test-recursion-selected-lane-writers",
        .description = "Compare selected-lane recursive witness materialization with the complete native writers",
        .root = "recursion_air_core_test_root.zig",
        .imports_prover_engine = true,
        .filters = &.{ "R-012 trace Merkle direct writers", "R-012 FRI Merkle leaf writers", "R-012 FRI Merkle node writers", "R-012 FRI Merkle anchor writers" },
        .minimum = 4,
    },
    .{
        .step = "test-recursion-framework-export",
        .description = "Compare backend polynomial export with authenticated recursive AIR plans",
        .root = "recursion_framework_export_test_root.zig",
        .imports_prover_engine = true,
    },
    .{
        .step = "test-recursion-arithmetic-fusion",
        .description = "Check fused verifier arithmetic and authenticated graph lowering",
        .root = "recursion_arithmetic_fusion_test_root.zig",
        .imports_prover_engine = true,
    },
    .{
        .step = "test-recursion-opening-accumulation",
        .description = "Check fused opening accumulation and exact wire fanout",
        .root = "recursion_opening_accumulation_test_root.zig",
        .imports_prover_engine = true,
    },
    .{
        .step = "test-poseidon-universal-degree3",
        .description = "Check compact universal Poseidon AIR against the retained permutation",
        .root = "poseidon2_universal_degree3_test_root.zig",
        .imports_prover_engine = true,
    },
    .{
        .step = "test-recursion-structural-hashes",
        .description = "Check canonical hash byte parity and FRI parameter extraction",
        .root = "recursion_air_core_test_root.zig",
        .imports_prover_engine = true,
        .filters = &.{ "R-012 canonical tuple hash", "structural SHA256", "R-012 FRI Merkle node writers" },
        .minimum = 3,
    },
    .{
        .step = "test-recursion-air-core",
        .description = "Run recursion-local typed-AIR tests without shared VM-provider bridges",
        .root = "recursion_air_core_test_root.zig",
        .imports_prover_engine = true,
    },
    .{
        .step = "test-recursion-air",
        .description = "Run recursion-local typed-AIR compiler and witness tests",
        .root = "recursion_air_test_root.zig",
        .imports_prover_engine = true,
    },
};
