//! Explicit q70/PoW26 from a real execution leaf through one recursive parent.
const std = @import("std");
const Cpu = @import("stwo_cpu_backend").CpuBackend;
const parent = @import("../recursion/blake3_execution_parent_proof.zig");
const span = @import("../recursion/span_statement_blake3.zig");
const config = parent.protocol.CSP_CONFIG;
test "BLAKE3 canonical leaf and recursive parent use q70 pow26" {
    const a = std.testing.allocator;
    var prepared = try prepareLeaf(a);
    var prepared_alive = true;
    defer if (prepared_alive) prepared.deinit();
    const statement = prepared.statement;
    try std.testing.expectEqualDeep(config, prepared.prepared.context.child_config);
    const retained = try prepared.prepared.rows.retainedBytes();
    std.debug.print("BLAKE3_CANONICAL_CHAIN_PREPARED leaf_queries=70 leaf_pow_bits=26 inputs={d} retained_bytes={d}\n", .{ prepared.prepared.rows.input_count, retained });
    const Api = parent.ForBackend(Cpu);
    const key = try Api.deriveKeyWithProfile(a, &prepared.prepared, .csp_q70_pow26);
    const expected = try key.identity();
    const admission = try parent.protocol.Admission.init(key, expected);
    const Worker = parent.pipeline.ForBackend(Cpu).Worker;
    const worker = try Worker.init(a, &prepared.prepared.rows, admission, .{ .worker_count = 4, .host_byte_limit = 24 * 1024 * 1024 * 1024, .retained_scratch_limit = 64 * 1024 * 1024 });
    var worker_alive = true;
    defer if (worker_alive) worker.deinit();
    var proof = try worker.prove(&prepared.prepared.rows);
    defer proof.deinit();
    const usage = worker.budget.snapshot();
    worker.deinit();
    worker_alive = false;
    prepared.deinit();
    prepared_alive = false;
    const bytes = try parent.codec.encode(a, &proof, &admission);
    defer a.free(bytes);
    var decoded = try parent.codec.decode(a, bytes, &admission);
    defer decoded.deinit();
    var copy = try parent.tree.Node.verifyOwned(&decoded, admission, expected, statement);
    defer copy.deinit();
    _ = try copy.root();
    try std.testing.expectEqual(@as(usize, 70), copy.verified.capture.queries.raw.len);
    var original = try parent.tree.Node.verifyOwned(&proof, admission, expected, statement);
    defer original.deinit();
    _ = try original.root();
    try std.testing.expect(original.verified.allocation_budget != null);
    std.debug.print("BLAKE3_CANONICAL_CHAIN verified=true leaf_queries=70 leaf_pow_bits=26 parent_queries=70 parent_pow_bits=26 artifact_bytes={d} prepared_bytes={d} worker_peak_bytes={d} worker_limit_bytes={d} plans_and_witnesses_released=true\n", .{ bytes.len, retained, usage.peak_live_bytes, usage.limit });
}
fn prepareLeaf(a: std.mem.Allocator) !parent.aggregation.Fold {
    const runner = @import("../runner/mod.zig");
    const instructions = [_]u32{ 0x00500093, 0x00708093, 0x00100137, 0x00100193, 0x00312223, 0x00312423, 0x0000006f };
    const elf = @import("../runner/guest_precompile/test_elf.zig").buildProgram(instructions.len, &instructions, 0, .rv32im_zkvm_v1);
    var session = try runner.BaseExecutionSession.init(a, &elf, .{ .trace_retention = .segment_owned, .clock_frame = .leaf_local });
    defer session.deinit();
    var segment = try session.startSegment(100);
    defer segment.deinit();
    var owner = try @import("blake3_segment_execution.zig").Owner.init(a, &segment);
    defer owner.deinit();
    const source = @import("../recursion/air/blake3_memory_snapshot.zig");
    var entry = try source.fromSnapshot(a, &segment.rw_memory, .entry, .continuation);
    defer entry.deinit();
    var exit = try source.fromSnapshot(a, &segment.rw_memory, .exit, .continuation);
    defer exit.deinit();
    const zero = span.Digest{ .bytes = @splat(0) };
    const initial = try span.MachineState.init(segment.entry_cpu.pc, segment.entry_cpu.regs, entry.root, zero);
    const final = try span.MachineState.init(segment.exit_cpu.pc, segment.exit_cpu.regs, exit.root, zero);
    const io = parent.public_io;
    const input = try io.input(&owner.native.statement.public_data);
    const output = try io.output(&owner.native.statement.public_data);
    const job = try span.JobContext.init(try span.CompleteExecution.init(parent.spans.protocolIdentity(config), owner.memory.program.root, initial, final, input, output, segment.cycle_count), 1);
    const statement = try span.SpanStatement.segmentLeaf(job, 0, try span.ExecutedSpan.init(0, 1, 0, segment.cycle_count, initial, final, .{ .digest = input }, .{ .digest = output }));
    const Api = @import("blake3_execution_proof.zig").ForBackend(Cpu);
    const verifier = try Api.PreparedVerifier.init(a, &owner.native.statement, try owner.admission(), config);
    defer verifier.deinit();
    const prepared = try @import("blake3_segment_parent.zig").ForBackend(Cpu).prepare(a, &owner, verifier, verifier.id, statement, 2);
    return .{ .prepared = prepared, .statement = statement };
}
