//! Bounded immutable inverse entries. Metadata locks never span factories or
//! device completion. Reader leases keep old entries alive; private proposals
//! become reusable only after checked completion. Failed factories are terminal.
const std = @import("std");
const external = @import("stwo_prover_engine").shared_external_memory;
pub const Key = struct {
    pub const Kind = enum { circle, line };
    runtime: usize,
    count: u32,
    layers: u32,
    initial: u32,
    step: u32,
    kind: Kind,
    pub fn bytes(self: Key) !usize {
        if (self.runtime == 0 or self.count == 0 or !std.math.isPowerOfTwo(self.count) or self.count > 1 << 30 or self.layers == 0 or (self.kind == .line and self.layers > std.math.log2_int(u32, self.count)) or (self.kind == .circle and self.layers != 1)) return error.InvalidFriInverseCacheKey;
        try @import("fri_domain_admission_v1.zig").requireDomain(self.initial, self.step, self.count, self.layers, self.kind == .circle);
        const values = if (self.kind == .circle) self.count else self.count - (self.count >> @intCast(self.layers));
        return std.math.mul(usize, values, 4);
    }
};

pub const Limits = struct {
    pub const max_entries = 8;
    pub const max_transactions = 16;
    pub const max_idle_bytes = 256 * 1024 * 1024;
    pub const idle_budget_divisor = 8;
    pub fn idleBytesForOwner(limit: usize) usize {
        return @min(max_idle_bytes, limit / idle_budget_divisor);
    }
};
pub fn Cache(comptime Resource: type) type {
    return struct {
        const Self = @This();
        const Entry = struct {
            key: Key,
            resource: Resource,
            reservation: external.Reservation,
            readers: usize = 0,
            lru_rank: u8 = 0,
            fn deinit(self: *Entry) void {
                std.debug.assert(self.readers == 0);
                self.resource.deinit();
                self.reservation.deinit();
            }
            fn take(self: *Entry) Entry {
                const moved_resource = self.resource;
                self.resource = undefined;
                return .{ .key = self.key, .resource = moved_resource, .reservation = self.reservation.take() };
            }
        };
        mutex: std.Thread.Mutex = .{},
        entries: [Limits.max_entries]?Entry = @splat(null),
        active_transactions: usize = 0,
        bound_owner: ?*external.SharedBudget = null,
        bound_runtime: ?usize = null,

        pub const Transaction = struct {
            cache: ?*Self,
            owner: ?*external.SharedBudget,
            requested: [2]?Key,
            borrowed: [2]?usize = .{ null, null },
            proposals: [2]?Entry = .{ null, null },
            completion: external.Completion = .joined,
            pub fn bindCompletion(self: *Transaction, completion: external.Completion) !void {
                if (self.cache == null or !self.completion.isCompleted()) return error.InvalidFriCompletionBinding;
                self.completion = completion;
            }
            /// Consuming transfer; raw copies would duplicate reader ownership.
            pub fn take(self: *Transaction) Transaction {
                var moved = Transaction{ .cache = self.cache, .owner = self.owner, .requested = self.requested, .borrowed = self.borrowed, .completion = self.completion };
                self.cache = null;
                self.owner = null;
                self.borrowed = .{ null, null };
                self.completion = .joined;
                for (&self.proposals, &moved.proposals) |*source, *destination| if (source.*) |*entry| {
                    destination.* = entry.take();
                    source.* = null;
                };
                return moved;
            }
            /// Cached resources are immutable: only unpublished proposals may
            /// be generated by the dispatch identified by needsGeneration.
            pub fn resource(self: *Transaction, kind: Key.Kind) ?*const Resource {
                const cache = self.cache orelse return null;
                const index = kindIndex(kind);
                if (self.proposals[index]) |*entry| return &entry.resource;
                if (self.borrowed[index]) |slot| return &cache.entries[slot].?.resource;
                return null;
            }
            pub fn needsGeneration(self: *const Transaction, kind: Key.Kind) bool {
                return self.cache != null and self.proposals[kindIndex(kind)] != null;
            }
            /// Must follow successful status/transcript checks. No metadata lock
            /// is held while waiting for the caller's checked completion.
            pub fn complete(self: *Transaction) !void {
                const cache = self.cache orelse return;
                if (self.completion == .in_flight) {
                    const pending = self.completion.in_flight;
                    self.completion = .joined;
                    pending.join(pending.context) catch |err| {
                        self.abort();
                        return err;
                    };
                }
                cache.mutex.lock();
                for (&self.proposals) |*proposal| if (proposal.*) |*entry| {
                    // Checked duplicate work may borrow the existing immutable
                    // entry on future calls; discard our terminal private copy.
                    if (cache.find(entry.key)) |slot| {
                        cache.touch(slot);
                    } else if (cache.admitIdle(entry.reservation.bytes)) |slot| {
                        const rank: u8 = @intCast(Limits.max_entries - cache.emptyCount());
                        cache.entries[slot] = entry.take();
                        cache.entries[slot].?.lru_rank = rank;
                        cache.touch(slot);
                        proposal.* = null;
                    }
                    // Oversized or all-leased cache: valid work finishes without
                    // promoting a buffer or evicting a live reader.
                };
                cache.mutex.unlock();
                // Keep the transaction active through duplicate/private cleanup,
                // so drain cannot report success before terminal destruction.
                self.destroyProposals();
                cache.mutex.lock();
                self.releaseReadersLocked(cache);
                cache.mutex.unlock();
                self.releaseOwner();
            }
            pub fn abort(self: *Transaction) void {
                const cache = self.cache orelse return;
                if (self.completion == .in_flight) {
                    const pending = self.completion.in_flight;
                    self.completion = .joined;
                    const join = pending.cancel_and_join orelse pending.join;
                    // Even a failure is terminal before buffer destruction.
                    join(pending.context) catch {};
                }
                self.destroyProposals();
                cache.mutex.lock();
                self.releaseReadersLocked(cache);
                cache.mutex.unlock();
                self.releaseOwner();
            }
            fn releaseReadersLocked(self: *Transaction, cache: *Self) void {
                for (&self.borrowed) |*slot| if (slot.*) |index| {
                    const entry = &cache.entries[index].?;
                    std.debug.assert(entry.readers > 0);
                    entry.readers -= 1;
                    slot.* = null;
                };
                std.debug.assert(cache.active_transactions > 0);
                cache.active_transactions -= 1;
                cache.trimIdle();
                cache.resetEmptyBinding();
                self.cache = null;
            }
            fn destroyProposals(self: *Transaction) void {
                for (&self.proposals) |*entry| if (entry.*) |*value| {
                    value.deinit();
                    entry.* = null;
                };
            }
            fn releaseOwner(self: *Transaction) void {
                if (self.owner) |owner| {
                    self.owner = null;
                    owner.destroy();
                }
            }
        };

        pub fn begin(self: *Self, a: std.mem.Allocator, keys: [2]?Key, factory: anytype) !Transaction {
            const budget = external.SharedBudget.fromAllocator(a) orelse return error.SharedExternalBudgetRequired;
            var requested_runtime: ?usize = null;
            for (keys, 0..) |key, index| if (key) |wanted| {
                if (kindIndex(wanted.kind) != index) return error.InvalidFriInverseCacheKey;
                _ = try wanted.bytes();
                if (requested_runtime) |id| {
                    if (wanted.runtime != id) return error.InvalidFriInverseCacheRuntime;
                } else requested_runtime = wanted.runtime;
            };
            const runtime_id = requested_runtime orelse return error.EmptyFriInverseCacheRequest;
            self.mutex.lock();
            var locked = true;
            defer if (locked) self.mutex.unlock();
            if (self.bound_owner) |owner| if (owner != budget) return error.FriInverseCacheBudgetConflict;
            if (self.bound_runtime) |id| if (id != runtime_id) return error.InvalidFriInverseCacheRuntime;
            if (self.active_transactions == Limits.max_transactions) return error.FriInverseCacheCapacityExceeded;
            // All hits are pinned atomically before any factory can fail.
            var transaction = Transaction{ .cache = self, .owner = budget.retain(), .requested = keys };
            self.bound_owner = budget;
            self.bound_runtime = runtime_id;
            self.active_transactions += 1;
            for (keys, 0..) |key, index| if (key) |wanted| {
                if (self.find(wanted)) |slot| {
                    self.entries[slot].?.readers += 1;
                    self.touch(slot);
                    transaction.borrowed[index] = slot;
                }
            };
            self.mutex.unlock();
            locked = false;
            errdefer transaction.abort();
            // Private misses allocate/generate concurrently. Active old/new
            // overlap is always charged. Only unused idle entries may be evicted
            // under reservation pressure, even if a later factory fails.
            for (keys, 0..) |key, index| if (key) |wanted| {
                if (transaction.borrowed[index] != null) continue;
                var reservation = try self.reserveMiss(a, try wanted.bytes());
                defer reservation.deinit();
                const created_resource = try factory.create(wanted, reservation.bytes);
                transaction.proposals[index] = .{ .key = wanted, .resource = created_resource, .reservation = reservation.take() };
            };
            return transaction.take();
        }
        /// Drain is nonblocking and all-or-nothing if any proof/factory is live.
        pub fn drain(self: *Self, a: std.mem.Allocator) !void {
            const budget = external.SharedBudget.fromAllocator(a) orelse return error.SharedExternalBudgetRequired;
            if (!self.mutex.tryLock()) return error.RuntimeBusy;
            defer self.mutex.unlock();
            if (self.bound_owner) |owner| if (owner != budget) return error.FriInverseCacheBudgetConflict;
            if (self.active_transactions != 0) return error.RuntimeBusy;
            for (&self.entries) |*entry| if (entry.*) |*current| {
                current.deinit();
                entry.* = null;
            };
            self.resetEmptyBinding();
        }
        pub fn isEmpty(self: *Self) bool {
            self.mutex.lock();
            defer self.mutex.unlock();
            return self.active_transactions == 0 and self.emptyCount() == Limits.max_entries;
        }
        fn find(self: *const Self, key: Key) ?usize {
            for (&self.entries, 0..) |*entry, index| if (entry.*) |*value| {
                if (std.meta.eql(value.key, key)) return index;
            };
            return null;
        }
        fn emptySlot(self: *const Self) ?usize {
            for (&self.entries, 0..) |*entry, index| if (entry.* == null) return index;
            return null;
        }
        fn emptyCount(self: *const Self) usize {
            var count: usize = 0;
            for (&self.entries) |*entry| if (entry.* == null) {
                count += 1;
            };
            return count;
        }
        /// Fraction is per bank; all four runtime banks together retain at
        /// most half an owner's cap as idle inverse buffers, and at most 1GiB.
        fn idleLimit(self: *const Self) usize {
            const owner = self.bound_owner orelse return 0;
            return Limits.idleBytesForOwner(owner.snapshot().limit);
        }
        fn idleBytes(self: *const Self) usize {
            var bytes: usize = 0;
            for (&self.entries) |*entry| if (entry.*) |*value| {
                if (value.readers == 0) bytes += value.reservation.bytes;
            };
            return bytes; // All tokens already fit the same combined owner cap.
        }
        fn touch(self: *Self, slot: usize) void {
            const prior_rank = self.entries[slot].?.lru_rank;
            for (&self.entries, 0..) |*entry, index| if (entry.*) |*value| {
                if (index != slot and value.lru_rank < prior_rank) value.lru_rank += 1;
            };
            self.entries[slot].?.lru_rank = 0;
        }
        fn evictIdle(self: *Self) bool {
            var selected: ?usize = null;
            for (&self.entries, 0..) |*entry, index| if (entry.*) |*value| {
                if (value.readers != 0) continue;
                if (selected == null or value.lru_rank > self.entries[selected.?].?.lru_rank) selected = index;
            };
            const slot = selected orelse return false;
            const rank = self.entries[slot].?.lru_rank;
            self.entries[slot].?.deinit();
            self.entries[slot] = null;
            for (&self.entries) |*entry| if (entry.*) |*value| {
                if (value.lru_rank > rank) value.lru_rank -= 1;
            };
            return true;
        }
        fn trimIdle(self: *Self) void {
            const limit = self.idleLimit();
            while (self.idleBytes() > limit) {
                if (!self.evictIdle()) break;
            }
        }
        fn admitIdle(self: *Self, bytes: usize) ?usize {
            const limit = self.idleLimit();
            if (bytes > limit) return null;
            while (self.idleBytes() > limit - bytes or self.emptySlot() == null) {
                if (!self.evictIdle()) return null;
            }
            return self.emptySlot();
        }
        fn reserveMiss(self: *Self, a: std.mem.Allocator, bytes: usize) !external.Reservation {
            const owner = external.SharedBudget.fromAllocator(a).?;
            while (true) {
                // Evict known idle pressure before the authoritative admission,
                // avoiding a denied attempt when idle bytes alone are the cause.
                // Snapshot is only an optimization; reserve remains synchronized.
                self.mutex.lock();
                const state = owner.snapshot();
                const freed = bytes <= state.limit and bytes > state.limit - state.live_bytes and self.evictIdle();
                self.mutex.unlock();
                if (freed) continue;
                const reservation = external.reserve(a, bytes, .require_shared_budget) catch |err| {
                    if (err != error.OutOfMemory or bytes > state.limit) return err;
                    self.mutex.lock();
                    const retried_eviction = self.evictIdle();
                    self.mutex.unlock();
                    if (!retried_eviction) return err;
                    continue;
                };
                return reservation;
            }
        }
        fn resetEmptyBinding(self: *Self) void {
            if (self.active_transactions == 0 and self.emptyCount() == Limits.max_entries) {
                self.bound_owner = null;
                self.bound_runtime = null;
            }
        }
        fn kindIndex(kind: Key.Kind) usize {
            return if (kind == .circle) 0 else 1;
        }
    };
}
