//! Private allocator-bearing sampled dispatch ABI. Legacy ABI stays intact.
const ffi = @import("bindings.zig");
const budget = @import("sampled_dispatch_budget_v1.zig");
const SampledBarycentricPointPlanV1 = ffi.SampledBarycentricPointPlanV1;
const SampledBarycentricColumnGroupV1 = ffi.SampledBarycentricColumnGroupV1;
const SampledBarycentricReceiptV1 = ffi.SampledBarycentricReceiptV1;
pub const Admit = *const fn (*anyopaque, usize, u32) callconv(.c) bool;

pub extern fn stwo_zig_metal_eval_polynomials_budgeted_v2(
    runtime: *anyopaque,
    coefficients: [*]const [*]const u32,
    coefficient_lengths: [*]const usize,
    coefficient_column_count: u32,
    coefficient_count: usize,
    factors: [*]const u32,
    factor_word_count: usize,
    basis_tasks: *const anyopaque,
    basis_task_count: u32,
    basis_count: u32,
    tasks: *const anyopaque,
    task_columns: [*]const u32,
    task_count: u32,
    output_count: u32,
    output: [*]u32,
    basis_threadgroup_width: *u32,
    evaluation_threadgroup_width: *u32,
    gpu_milliseconds: *f64,
    error_message: [*]u8,
    error_message_len: usize,
    budget_context: *anyopaque,
    budget_admit: Admit,
    budget_receipt: *budget.Receipt,
    allow_unowned_aliases: bool,
    stream_policy: *const budget.StreamPolicy,
) bool;
pub extern fn stwo_zig_metal_eval_barycentric_resident_v1_budgeted_v2(
    runtime: *anyopaque,
    resident_trees: [*]const ?*anyopaque,
    tree_count: u32,
    columns: [*]const [*]const u32,
    column_lengths: [*]const usize,
    output_indices: [*]const u32,
    column_count: u32,
    point_plans: [*]const SampledBarycentricPointPlanV1,
    point_plan_count: u32,
    groups: [*]const SampledBarycentricColumnGroupV1,
    group_count: u32,
    output_count: u32,
    output: [*]u32,
    receipt: *SampledBarycentricReceiptV1,
    gpu_milliseconds: *f64,
    error_message: [*]u8,
    error_message_len: usize,
    budget_context: *anyopaque,
    budget_admit: Admit,
    budget_receipt: *budget.Receipt,
) bool;
pub extern fn stwo_zig_metal_eval_barycentric_host_v1_budgeted_v2(
    runtime: *anyopaque,
    resident_trees: [*]const ?*anyopaque,
    tree_count: u32,
    columns: [*]const [*]const u32,
    column_lengths: [*]const usize,
    output_indices: [*]const u32,
    column_count: u32,
    point_plans: [*]const SampledBarycentricPointPlanV1,
    point_plan_count: u32,
    groups: [*]const SampledBarycentricColumnGroupV1,
    group_count: u32,
    output_count: u32,
    output: [*]u32,
    receipt: *SampledBarycentricReceiptV1,
    gpu_milliseconds: *f64,
    error_message: [*]u8,
    error_message_len: usize,
    budget_context: *anyopaque,
    budget_admit: Admit,
    budget_receipt: *budget.Receipt,
) bool;
