from pathlib import Path
r=Path('src/frontends/riscv/recursion')
backup=Path('/tmp/pr198-parent-retirement-originals');backup.mkdir(exist_ok=True)
files=['detached_parent_contract_v1.zig','detached_parent_components_v1.zig','detached_parent_verifier_components_v1.zig','detached_parent_definitions_v1.zig','detached_parent_prepared_v1.zig']
for n in files:(backup/n).write_bytes((r/n).read_bytes())
p=r/files[0];s=p.read_text().replace('    const qm31_mul_full = @import("air/qm31_mul_full.zig");\n','').replace('const WideGeometry = shared.PoseidonForManifest(manifest_mod, false, .canonical_only);\n','').replace('.allow_reviewed_legacy','.canonical_only');a=s.index('// Retained proofs');b=s.index('pub const ParametersV1',a);s=s[:a]+'// Detached parents admit only the current catalog and canonical provider identity.\n// Historical keys selecting different AIR must be reproved under current admission.\n'+s[b:];s=s.replace('(!usesLegacyPoseidon(manifest) and !CompactGeometry.acceptsGeometry(poseidon.geometry))','!CompactGeometry.acceptsGeometry(poseidon.geometry)');s=s.replace('        const legacy = row == 30 and usesLegacyMul(manifest);\n','').replace('if (legacy) geometry.manifestGeometryForAir(legacy_mul_entry.Air, manifest_mod, .qm31_mul, placement.geometry.log_size) else ','').replace('if (legacy) geometry.parameterColumnCount(legacy_mul_entry.Air) else ','');p.write_text(s)
for n in files[1:3]:
 p=r/n;s=p.read_text();s=s.replace('    const qm31_mul_full = @import("air/qm31_mul_full.zig");\n','');s=s.replace('provider.Poseidon2Degree3AdapterWithCompatibility(manifest_mod, .allow_reviewed_legacy)','provider.Poseidon2Degree3AdapterForManifest(manifest_mod)')
 for line in ['const legacy_mul_entry = contract.legacy_mul_entry;','const usesLegacyMul = contract.usesLegacyMul;','const usesLegacyPoseidon = contract.usesLegacyPoseidon;','const Wide = poseidon.Component(@import("../air/memory_commitment/poseidon2_wide_equations.zig"));','        legacy_mul: Component(legacy_mul_entry),','        legacy_poseidon: provider.Poseidon2Adapter,','        legacy_poseidon: Wide,','            .legacy_mul = undefined,','            .legacy_poseidon = undefined,']:
  s=s.replace(line+'\n','')
 a=s.index('        if (usesLegacyPoseidon(manifest)) {');b=s.index('        try storage.definitions.initRange();',a)
 if 'verifier_components' in n:
  new='        storage.poseidon = try initPoseidon(storage, parameters, claims);\n        try append(storage, 34, storage.poseidon.asVerifierComponent());\n'
 else:
  new='        storage.poseidon = try PoseidonAdapter.initWithAllocator(allocator, &storage.manifest, storage.manifest.placements[34].?.geometry.log_size, parameters.poseidon_active_rows, &storage.providers, &storage.relations, claims.poseidon_partials);\n        try storage.gate.append(&storage.manifest, try storage.poseidon.binding(&storage.manifest));\n'
 s=s[:a]+new+s[b:]
 a=s.index('        if (comptime row == 30) {');b=s.index('        try storage.definitions.initLogical(index);',a);s=s[:a]+s[b:]
 if 'verifier_components' in n:
  s=s.replace('fn initPoseidon(comptime compact: bool, storage: *Storage, parameters: ParametersV1, claims: ClaimsV1) !if (compact) Compact else Wide','fn initPoseidon(storage: *Storage, parameters: ParametersV1, claims: ClaimsV1) !Compact').replace('manifest_mod, compact, .allow_reviewed_legacy','manifest_mod, true, .canonical_only').replace('(if (compact) Compact else Wide){','Compact{')
 else:
  a=s.index('                if (@intFromEnum(entry.row) == 30');b=s.index('\n            }',a);s=s[:a]+'                _ = try program.recordTypedComponent(entry.row, &storage.logical[index]);'+s[b:]
  a=s.index('        if (usesLegacyPoseidon(&storage.manifest)) {');b=s.index('        _ = try program.recordRangeCheck8x8Provider',a);s=s[:a]+'        _ = try program.recordPoseidonProvider(&storage.poseidon);\n'+s[b:]
 p.write_text(s)
p=r/files[3];s=p.read_text();s='\n'.join(line for line in s.split('\n') if not any(x in line for x in ['const legacy_mul =','legacy_mul_definition:','legacy_mul_initialized:','if (self.legacy_mul_initialized)']));a=s.index('    pub fn initLegacyMul');b=s.index('    pub fn initRange',a);s=s[:a]+s[b:];p.write_text(s)
p=r/files[4];s=p.read_text().replace('var poseidon_geometry =','const poseidon_geometry =').replace('            const Compatible = provider.Poseidon2Degree3AdapterWithCompatibility(manifest_mod, .allow_reviewed_legacy);\n','').replace('!Compatible.acceptsGeometry(admitted.geometry)','!PoseidonAdapter.acceptsGeometry(admitted.geometry)').replace('            poseidon_geometry.semantic_digest = admitted.geometry.semantic_digest;\n','');s=s.replace('// Independently sealed retained geometry selects only the reviewed identity.','// Canonical admission roundtrips exactly; independently resealed retired identity fails.');s=s.replace('    const retained = try PreparedV1.initForManifest(allocator, rows, &.{}, &retained_manifest);','    try std.testing.expectError(error.DetachedParentManifestMismatch, PreparedV1.initForManifest(allocator, rows, &.{}, &retained_manifest));\n    const retained = try PreparedV1.initForManifest(allocator, rows, &.{}, prepared.manifest());').replace('&retained_manifest.seal, &retained.manifest().seal','&prepared.manifest().seal, &retained.manifest().seal').replace('for (retained_manifest.roster_rows[0..retained_manifest.roster_count]) |row| {\n        var geometry = retained_manifest.placements[row].?.geometry;','for (prepared.manifest().roster_rows[0..prepared.manifest().roster_count]) |row| {\n        var geometry = prepared.manifest().placements[row].?.geometry;');p.write_text(s)
