//! Typed non-product scopes and compatibility steps for the build catalog.

const std = @import("std");
const construction_observer = @import("../graph/construction_observer.zig");
pub const package_dependencies = @import("package_dependencies.zig");

pub const Scope = enum {
    aggregate,
    architecture,
    cairo_cpu,
    cairo_metal,
    compatibility_tools,
    core,
    cairo_cuda,
    cuda_tools,
    deferred,
    metal_tools,
    native_cpu,
    native_cuda,
    native_metal,
    package,
    policy,
    prover,
    release,
    riscv_cpu,
    riscv_cpu_compat,
    riscv_metal,
    verification,
};

pub const Step = struct {
    name: []const u8,
    description: []const u8,
    scope: Scope,
};

pub const ScopeRole = enum {
    product,
    package_exports,
    compatibility_tools,
    backend_tools,
    gates,
    unavailable,
};

pub const Configure = struct {
    scope: Scope,
    role: ScopeRole,
    inherited_product_scope: ?Scope = null,
    product_ids: []const []const u8 = &.{},
    module_roots: []const []const u8 = &.{},
    generated_module_roots: []const []const u8 = &.{},
    dependency_module_roots: []const []const u8 = &.{},
    allowed_module_files: []const []const u8 = &.{},
    allowed_module_prefixes: []const []const u8 = &.{},
    external_tools: []const []const u8 = &.{},
    runtime_probes: []const []const u8 = &.{},
    constructors: []const []const u8,
    constructed_products: []const construction_observer.ProductIdentity = &.{},
};

/// Steps which are not the primary build/test/benchmark/identity steps already
/// carried by a product descriptor. Root dispatch and closure validation both
/// consume this exact list.
pub const steps = [_]Step{
    .{ .name = "check-cairo-cuda-local", .description = "Compile the full Cairo CUDA product without a GPU or CUDA runtime", .scope = .cairo_cuda },
    .{ .name = "test-cairo-cuda-local", .description = "Test canonical CUDA source admission and table geometry without a GPU", .scope = .cairo_cuda },
    .{ .name = "test-stwo-prover-fft", .description = "Test circle transforms, radix scheduling and coefficient parity", .scope = .prover },
    .{ .name = "test-stwo-prover-sampling", .description = "Test sampled values and independent circle polynomial evaluation", .scope = .prover },
    .{ .name = "test-stwo-core-blake2s", .description = "Test BLAKE2s streams and SIMD lifted leaves", .scope = .core },
    .{ .name = "test-stwo-core-m31", .description = "Test scalar and packed M31 arithmetic and butterfly parity", .scope = .core },
    .{ .name = "test-stwo-prover-merkle", .description = "Test lifted Merkle commitment paths and allocation custody", .scope = .prover },
    .{ .name = "test-stwo-prover-coefficient-storage", .description = "Qualify compact polynomial commitments, quotients, openings and failure custody", .scope = .prover },
    .{ .name = "test-stwo-prover-preparation", .description = "Test prepared column cache and asynchronous publication", .scope = .prover },
    .{ .name = "test-stwo-prover-pool", .description = "Test proof-scoped pool lifetimes and concurrent borrowed coordinators", .scope = .prover },
    .{ .name = "architecture-gate", .description = "Produce one host-local BG-15 architecture receipt", .scope = .architecture },
    .{ .name = "architecture-verify", .description = "Verify Linux and macOS BG-15 receipts in the trusted workflow", .scope = .architecture },
    .{ .name = "build-monorepo-baseline", .description = "Validate the immutable pre-migration build-architecture baseline", .scope = .architecture },
    .{ .name = "test-downstream-modules", .description = "Compile and run a clean external consumer of stwo_core, stwo_prover, and stwo", .scope = .package },
    .{ .name = "interop-cli", .description = "Build the proof interoperability CLI", .scope = .compatibility_tools },
    .{ .name = "metal-core-aot", .description = "Build the deterministic, fail-closed core Metal AOT tool", .scope = .metal_tools },
    .{ .name = "test-metal-core-aot", .description = "Run deterministic core Metal AOT tooling tests without compiling shaders", .scope = .metal_tools },
    .{ .name = "test-metal-polynomial-runtime", .description = "Run focused resident-polynomial codegen and quotient tests", .scope = .metal_tools },
    .{ .name = "metal-core-aot-probe", .description = "Build the authenticated Native core metallib acceptance probe", .scope = .metal_tools },
    .{ .name = "test-metal-core-aot-probe", .description = "Run Native core metallib probe contract tests without compiling shaders", .scope = .metal_tools },
    .{ .name = "metal-core-aot-acceptance", .description = "Build, authenticate, and inspect the linked Native core metallib", .scope = .metal_tools },
    .{ .name = "cairo-preprocessed-export", .description = "Build the bounded canonical coefficient exporter", .scope = .cairo_cpu },
    .{ .name = "cuda-source-closure", .description = "Verify the exact pinned CUDA/C++ source authority", .scope = .cuda_tools },
    .{ .name = "cuda-authority-materialize", .description = "Fetch and authenticate the audit-only upstream CUDA workspace", .scope = .cuda_tools },
    .{ .name = "cuda-cumetal-ledger", .description = "Validate the checked CuMetal compatibility ledger", .scope = .cuda_tools },
    .{ .name = "cuda-cumetal-portability", .description = "Translate the maintained CUDA device-code portability floor with CuMetal", .scope = .cuda_tools },
    .{ .name = "cuda-cumetal-audit", .description = "Ratchet CUDA translation and Apple-GPU execution evidence with CuMetal", .scope = .cuda_tools },
    .{ .name = "cuda-cumetal-native-archive", .description = "Build the authenticated Native CuMetal provider archive", .scope = .cuda_tools },
    .{ .name = "run-native-cumetal-smoke", .description = "Prove and verify Native wide Fibonacci on the Apple GPU", .scope = .cuda_tools },
    .{ .name = "cuda-native-aot", .description = "Generate authenticated Native CUDA AOT sources in Zig's build cache", .scope = .cuda_tools },
    .{ .name = "cuda-cairo-witness-aot", .description = "Generate all current upstream Cairo CUDA witness programs", .scope = .cuda_tools },
    .{ .name = "cuda-cairo-local-parity", .description = "Generate the CUDA scalar and register-rewrite differential", .scope = .cuda_tools },
    .{ .name = "cuda-cairo-witness-parity", .description = "Generate the long deduction-chain CUDA differential", .scope = .cuda_tools },
    .{ .name = "cuda-cairo-eval-aot", .description = "Generate authenticated Cairo CUDA eval sources in Zig's build cache", .scope = .cuda_tools },
    .{ .name = "cuda-build-plan", .description = "Validate and print the isolated native CUDA archive build plan", .scope = .cuda_tools },
    .{ .name = "test-cuda-build-plan", .description = "Test CUDA source, AOT, toolchain, and build-plan contracts without a GPU", .scope = .cuda_tools },
    .{ .name = "test-cuda-runtime-contract", .description = "Test proof-owned CUDA context, residency, and strict-AOT contracts", .scope = .cuda_tools },
    .{ .name = "cuda-native-ec-composite-oracle", .description = "Emit the canonical Zig SIMD receipt for the native EC consumer", .scope = .cuda_tools },
    .{ .name = "test-cuda-plonk-logup-contract", .description = "Test activation-disabled exact Plonk/LogUp CUDA contracts", .scope = .cuda_tools },
    .{ .name = "test-cuda-xor-logup-contract", .description = "Test exact XOR/LogUp CUDA contracts without a GPU", .scope = .cuda_tools },
    .{ .name = "test-cuda-state-machine-contract", .description = "Test activation-disabled exact State Machine v2 CUDA contracts", .scope = .cuda_tools },
    .{ .name = "test-cuda-poseidon-arena-contract", .description = "Test exact Poseidon CUDA arena contracts without a GPU", .scope = .cuda_tools },
    .{ .name = "test-cuda-blake-exact-structure", .description = "Test exact mixed-height Blake CUDA contracts without a GPU", .scope = .cuda_tools },
    .{ .name = "test-cuda-adapter", .description = "Compile and test the external-authority Native proof adapter", .scope = .cuda_tools },
    .{ .name = "cuda-native-archive", .description = "Build the exact static CUDA runtime and generated AOT pack", .scope = .cuda_tools },
    .{ .name = "cuda-native-adapter", .description = "Build the external-authority Native CUDA proof adapter", .scope = .cuda_tools },
    .{ .name = "cairo-input", .description = "Build adapted Cairo input inspector", .scope = .compatibility_tools },
    .{ .name = "cairo-air-bundle-inspector", .description = "Build official Cairo AIR bundle inspector", .scope = .compatibility_tools },
    .{ .name = "cairo-zkvm-fixtures", .description = "Derive the zkvm basket ProverInputs through the pinned Cairo VM adapter", .scope = .cairo_cpu },
    .{ .name = "cairo-csp-fixtures", .description = "Validate exact Cairo CSP sources and derive review candidates", .scope = .cairo_cpu },
    .{ .name = "cairo-csp-runnable", .description = "Require cryptographically linked exact Cairo CSP proof fixtures", .scope = .cairo_cpu },
    .{ .name = "test-cairo-witness-storage", .description = "Qualify final witness placement and borrowed storage custody", .scope = .cairo_cpu },
    .{ .name = "test-cairo-incremental-multiplicities", .description = "Qualify streamed multiplicities and last-consumer feed retirement", .scope = .cairo_cpu },
    .{ .name = "test-cairo-trace-lease", .description = "Qualify scoped coefficient reconstruction, parallel parity and allocation failure custody", .scope = .cairo_cpu },
    .{ .name = "test-cairo-composition-lifetime", .description = "Qualify device composition staging release and failure custody", .scope = .cairo_cpu },
    .{ .name = "test-cairo-preprocessed-cache", .description = "Qualify preprocessing cache identity, integrity and fallback", .scope = .cairo_cpu },
    .{ .name = "test-cairo-cpu-native-composition", .description = "Compare every authenticated native CPU AIR kernel with SIMD", .scope = .cairo_cpu },
    .{ .name = "test-cairo-cpu-oracle", .description = "Prove through the CPU CLI and require official Rust acceptance", .scope = .cairo_cpu },
    .{ .name = "test-cairo-metal-codegen", .description = "Test typed Metal composition generation and fusion", .scope = .cairo_metal },
    .{ .name = "test-cairo-metal-oracle", .description = "Require exact Cairo CPU/Metal parity and official Rust acceptance", .scope = .cairo_metal },
    .{ .name = "test-cairo-frontend", .description = "Run focused backend-neutral Cairo conformance tests", .scope = .compatibility_tools },
    .{ .name = "test-circuit-cairo-statement", .description = "Test the in-circuit Cairo statement port through a recording builder facade", .scope = .compatibility_tools },
    .{ .name = "test-circuit-leaf-cairo-roots", .description = "Commit the canonical_small preprocessed trace to the leaf circuit's Cairo roots (R10b)", .scope = .compatibility_tools },
    .{ .name = "test-cairo-cpu-air", .description = "Run Cairo CPU AIR integration tests", .scope = .compatibility_tools },
    .{ .name = "test-cairo-cpu-proof", .description = "Run the complete official Cairo CPU proof gate", .scope = .compatibility_tools },
    .{ .name = "riscv-opcode-manifest", .description = "Dump the Sail-authoritative opcode and proof-family policy as JSON", .scope = .compatibility_tools },
    .{ .name = "riscv-opcode-manifest-check", .description = "Validate stable RV32IM protocol IDs and proof classifications", .scope = .compatibility_tools },
    .{ .name = "test-riscv", .description = "Run RISC-V runner tests (trace_dump)", .scope = .riscv_cpu_compat },
    .{ .name = "test-block-memory-range-v2", .description = "Check block-v2 range and RW initial-provider witnesses", .scope = .riscv_cpu },
    .{ .name = "test-block-memory-size-plan", .description = "Check count-first sorted-memory AIR sizing and exact partition replay", .scope = .riscv_cpu },
    .{ .name = "test-block-v5-source-seal", .description = "Check versioned block-v5 first-round transcript binding", .scope = .riscv_cpu },
    .{ .name = "test-block-v5-mixed-queue", .description = "Check bounded exact mixed-radix parent scheduling and cancellation", .scope = .riscv_cpu },
    .{ .name = "test-block-v5-global", .description = "Freshly verify native-v3 globals and complete ordinary recursive bundle", .scope = .riscv_cpu },
    .{ .name = "test-block-v5-canonical", .description = "Freshly verify a complete ordinary detached bundle at q70/PoW26", .scope = .riscv_cpu },
    .{ .name = "test-block-v5-caller-global", .description = "Freshly verify a complete caller bundle with native framing and exact recursion", .scope = .riscv_cpu },
    .{ .name = "test-block-v5-precompile-family", .description = "Freshly verify independently sized typed precompile arithmetic", .scope = .riscv_cpu },
    .{ .name = "test-block-v5-native-lookup", .description = "Freshly verify global native bitwise and range providers", .scope = .riscv_cpu },
    .{ .name = "test-block-v5-program-census", .description = "Check exact block-wide ROM fetch aggregation", .scope = .riscv_cpu },
    .{ .name = "test-block-v4-parallel-families", .description = "Freshly verify the small real-I/O block with concurrent memory and execution proving", .scope = .riscv_cpu },
    .{ .name = "test-block-execution-sidecar-v2", .description = "Check block-v2 same-root typed execution sidecar PCS proof", .scope = .riscv_cpu },
    .{ .name = "test-block-execution-native-root-v2", .description = "Check sidecar roots against a freshly verified native RISC-V execution proof", .scope = .riscv_cpu },
    .{ .name = "test-block-rw-initial-joint-v2", .description = "Prove and freshly verify block-v2 RW initial source with shared BLAKE3 paths", .scope = .riscv_cpu },
    .{ .name = "test-blake3-exact-frontier", .description = "Check exact-count recursive forest ownership and coverage", .scope = .riscv_cpu },
    .{ .name = "test-blake3-exact-root", .description = "Prove a canonical ragged exact-count recursive root", .scope = .riscv_cpu },
    .{ .name = "test-block-v3-recursive", .description = "Prove linked block-v3 dyadic and exact-count diagnostic roots", .scope = .riscv_cpu },
    .{ .name = "test-block-v4-bundle-manifest", .description = "Check staged block-v4 bundle serialization and hash-pinned reopening", .scope = .riscv_cpu },
    .{ .name = "test-block-v4-detached-bundle", .description = "Freshly verify a canonical detached block-v4 bundle with independent SHA pins", .scope = .riscv_cpu },
    .{ .name = "test-riscv-prover", .description = "Run RISC-V prover tests (prove+verify)", .scope = .riscv_cpu_compat },
    .{ .name = "riscv-bench", .description = "Build RISC-V benchmark CLI", .scope = .compatibility_tools },
    .{ .name = "test-riscv-bench", .description = "Run focused RISC-V benchmark CLI contract tests", .scope = .compatibility_tools },
    .{ .name = "native-proof-bench-cpu", .description = "Build the machine-readable native CPU full-proof benchmark with SIMD hot paths", .scope = .compatibility_tools },
    .{ .name = "riscv-trace-dump", .description = "Build RISC-V trace dumper CLI", .scope = .riscv_cpu },
    .{ .name = "riscv-pc-hotspot-observer", .description = "Build the bounded RISC-V retirement PC-hotspot observer", .scope = .riscv_cpu },
    .{ .name = "riscv-function-value-observer", .description = "Build the bounded RISC-V function-load value observer", .scope = .riscv_cpu },
    .{ .name = "riscv-analyze-legacy-semantic-observer", .description = "Build the bounded Revm-42 analyze_legacy semantic observer", .scope = .riscv_cpu },
    .{ .name = "riscv-memcpy-hotspot-observer", .description = "Build the bounded RISC-V memcpy-call hotspot observer", .scope = .riscv_cpu },
    .{ .name = "riscv-memcpy-admission-observer", .description = "Build the exact RISC-V bulk-memcpy admission observer", .scope = .riscv_cpu },
    .{ .name = "riscv-poseidon2-pair-check", .description = "Build the C-013 software/precompile semantic checker", .scope = .riscv_cpu },
    .{ .name = "check-c013-poseidon2-pair", .description = "Build and semantically validate the exact C-013 guest pair", .scope = .riscv_cpu },
    .{ .name = "riscv-poseidon2-pair-proof", .description = "Build the one-shot C-013 CPU proof comparison", .scope = .riscv_cpu },
    .{ .name = "check-c013-poseidon2-cpu-proof", .description = "Run one verified CPU proof for each exact C-013 arm", .scope = .riscv_cpu },
    .{ .name = "riscv-poseidon2-proof-child", .description = "Build the fresh-process single-arm C-013 CPU proof child", .scope = .riscv_cpu },
    .{ .name = "check-c013-poseidon2-proof-child", .description = "Run one fresh functional CPU child for each exact C-013 arm", .scope = .riscv_cpu },
    .{ .name = "riscv-c013-aa-proof-child", .description = "Build the fresh-process C-013 A/A admission child", .scope = .riscv_cpu },
    .{ .name = "check-c013-aa-proof-child", .description = "Run one fresh functional C-013 A/A child diagnostic", .scope = .riscv_cpu },
    .{ .name = "riscv-c013-corpus-manifest", .description = "Build exact C-013 host-native corpus manifest generator", .scope = .riscv_cpu },
    .{ .name = "check-c013-corpus-manifest", .description = "Generate all frozen C-013 input/output identities", .scope = .riscv_cpu },
    .{ .name = "stwo-zig-riscv-cpu-static", .description = "Build the static x86_64-linux-musl RISC-V CPU challenge executable", .scope = .riscv_cpu },
    .{ .name = "test-riscv-prover-core", .description = "Run the RISC-V prover corpus without the separately retained committed-witness mutation suites", .scope = .riscv_cpu },
    .{ .name = "test-riscv-planned-tree1", .description = "Run exact predecessor versus N=1/2/4 full-proof pool parity", .scope = .riscv_cpu },
    .{ .name = "test-riscv-proof-pool-parity", .description = "Run exact Tree-1/Tree-2/quotient/opening pool parity and recovery", .scope = .riscv_cpu },
    .{ .name = "test-riscv-profile-partition", .description = "Run exact five-region witness/proving partition and report custody", .scope = .riscv_cpu },
    .{ .name = "test-riscv-memory-provider-shard", .description = "Prove and freshly verify research-only base Poseidon provider shards", .scope = .riscv_cpu },
    .{ .name = "test-riscv-degree-bounded-poseidon-proof", .description = "Prove and cold fresh-verify the degree-six Poseidon candidate", .scope = .riscv_cpu },
    .{ .name = "benchmark-riscv-degree-bounded-poseidon", .description = "Benchmark legacy 445-column versus degree-six 161-column Poseidon proofs", .scope = .riscv_cpu },
    .{ .name = "test-riscv-degree5-poseidon-proof", .description = "Prove and cold fresh-verify the degree-five Poseidon candidate", .scope = .riscv_cpu },
    .{ .name = "test-riscv-degree5-provider-proof", .description = "Prove and cold fresh-verify one retained degree-five provider shard", .scope = .riscv_cpu },
    .{ .name = "benchmark-riscv-degree5-poseidon", .description = "Benchmark legacy 445-column versus degree-five 239-column Poseidon proofs", .scope = .riscv_cpu },
    .{ .name = "riscv-memory-provider-shard-log18", .description = "Compile the research log18 provider benchmark boundary without running it", .scope = .riscv_cpu },
    .{ .name = "test-riscv-recursion-poseidon-leaf", .description = "Prove and verify one RISC-V leaf under the recursion Poseidon2 protocol", .scope = .riscv_cpu },
    .{ .name = "test-riscv-statement-wire", .description = "Check shared statement metadata and guest artifact compatibility", .scope = .riscv_cpu },
    .{ .name = "test-riscv-blake3-tree-pipeline", .description = "Qualify bounded persistent preparation and proving on a native four-leaf tree", .scope = .riscv_cpu },
    .{ .name = "test-riscv-blake3-aggregation", .description = "Prove adjacent BLAKE3 execution segments and their recursive aggregate", .scope = .riscv_cpu },
    .{ .name = "test-riscv-blake3-ethereum-canonical-aggregation", .description = "Prove full-width Ethereum segments and their aggregate at 70 queries and 26 PoW bits", .scope = .riscv_cpu },
    .{ .name = "test-riscv-blake3-canonical-chain", .description = "Prove a BLAKE3 execution leaf and parent at 70 queries and 26 PoW bits", .scope = .riscv_cpu },
    .{ .name = "test-riscv-blake3-execution-commitments", .description = "Validate joined native execution and BLAKE3 commitment component preparation", .scope = .riscv_cpu },
    .{ .name = "test-riscv-blake3-memory-update", .description = "Prove BLAKE3 memory updates and validate public-I/O continuation conversions", .scope = .riscv_cpu },
    .{ .name = "test-riscv-blake3-memory-path", .description = "Prove a full-depth BLAKE3 byte-memory opening", .scope = .riscv_cpu },
    .{ .name = "test-riscv-blake3-identities", .description = "Prove paired BLAKE3 Span identities with trusted preprocessing", .scope = .riscv_cpu },
    .{ .name = "test-riscv-statement-codecs", .description = "Validate legacy and full-digest BLAKE3 Span encoding and folding", .scope = .riscv_cpu },
    .{ .name = "test-riscv-recursion-ingress", .description = "Validate production-derived recursive public ingress without proving", .scope = .riscv_cpu },
    .{ .name = "test-riscv-recursion-typed-control", .description = "Prove and independently verify the typed universal-control adapter", .scope = .riscv_cpu },
    .{ .name = "test-riscv-release-exhaustive", .description = "Run the exhaustive RISC-V proof and adversarial release suites", .scope = .riscv_cpu },
    .{ .name = "test-riscv-sail-oracle", .description = "Run the sail_oracle self-check and forged-trace rejection against the pinned Sail oracle", .scope = .riscv_cpu },
    .{ .name = "test-riscv-rigidity", .description = "Run the full witness-rigidity sweep over every committed opcode column", .scope = .riscv_cpu },
    .{ .name = "test-riscv-air-satisfaction-export", .description = "Export committed traces for the independent AIR satisfaction checker", .scope = .riscv_cpu },
    .{ .name = "test-riscv-air-satisfaction", .description = "Export and independently check all RISC-V AIR main-trace components", .scope = .riscv_cpu },
    .{ .name = "riscv-refinement-ir", .description = "Export symbolic AIR and production AIR IR v2 for Lean refinement", .scope = .riscv_cpu },
    .{ .name = "riscv-refinement-pilot", .description = "Verify the 46-opcode FV-1/FV-2 publication evidence", .scope = .riscv_cpu },
    .{ .name = "riscv-csp-bench", .description = "Run the pinned EthProofs CSP benchmark matrix", .scope = .riscv_cpu },
    .{ .name = "riscv-recursion-csp-producer", .description = "Build the canonical one-workload recursive CSP producer", .scope = .riscv_cpu },
    .{ .name = "riscv-recursion-shape-inspector", .description = "Build the proof-independent canonical workload shape inspector", .scope = .riscv_cpu },
    .{ .name = "stwo-ethereum-block-proof", .description = "Build the streamed Ethereum segment proof producer/verifier", .scope = .riscv_cpu },
    .{ .name = "stwo-ethereum-block-stream", .description = "Build canonical BLAKE3 Ethereum execution and recursive root proving", .scope = .riscv_cpu },
    .{ .name = "stwo-ethereum-block-verify", .description = "Build canonical Ethereum root verification with a receiver-owned key pin", .scope = .riscv_cpu },
    .{ .name = "stwo-ethereum-block-exact-verify", .description = "Build canonical exact-count forest verification with a receiver-owned roster pin", .scope = .riscv_cpu },
    .{ .name = "stwo-ethereum-block-v4-cpu-produce", .description = "Build staged canonical CPU block-v4 proof bundle producer", .scope = .riscv_cpu },
    .{ .name = "stwo-ethereum-block-v4-cpu-verify", .description = "Build detached canonical CPU block-v4 proof bundle verifier", .scope = .riscv_cpu },
    .{ .name = "stwo-ethereum-block-v5-cpu-produce", .description = "Build streaming complete CPU block-v5 proof bundle producer", .scope = .riscv_cpu },
    .{ .name = "stwo-ethereum-block-v5-cpu-verify", .description = "Build fresh standalone complete CPU block-v5 bundle verifier", .scope = .riscv_cpu },
    .{ .name = "stwo-ethereum-block-v4-candidate-roster", .description = "Build read-only candidate native-key roster proposal tool", .scope = .riscv_cpu },
    .{ .name = "stwo-ethereum-block-v4-geometry-gate", .description = "Build read-only actual first-round CPU block-v4 geometry scanner", .scope = .riscv_cpu },
    .{ .name = "stwo-ethereum-block-v4-smoke-fixture", .description = "Build small real-I/O and Keccak CPU block-v4 smoke fixture writer", .scope = .riscv_cpu },
    .{ .name = "riscv-csp-bench-metal", .description = "Run the pinned EthProofs CSP benchmark matrix on Metal", .scope = .riscv_metal },
    .{ .name = "test-riscv-metal-recursive-aot", .description = "Check or regenerate the exact recursive typed AIR AOT catalog without proving", .scope = .riscv_metal },
    .{ .name = "test-riscv-metal-recursive-resident", .description = "Check admitted recursive AOT dispatch against native AIR and hostile bindings", .scope = .riscv_metal },
    .{ .name = "test-riscv-metal-guest-poseidon2-aot", .description = "Prove and independently verify the exact guest Poseidon2 profile on authenticated Metal AOT", .scope = .riscv_metal },
    .{ .name = "metal-arena-plan", .description = "Build sparse Metal arena planner", .scope = .metal_tools },
    .{ .name = "metal-arena-session", .description = "Build persistent Metal SN PIE prover session", .scope = .metal_tools },
    .{ .name = "metal-prover-session-test", .description = "Run persistent Metal prover-session unit tests", .scope = .metal_tools },
    .{ .name = "metal-recovery-bench", .description = "Build Metal recovery storage benchmark", .scope = .metal_tools },
    .{ .name = "metal-ec-op-bench", .description = "Build resident Metal EC-op benchmark", .scope = .metal_tools },
    .{ .name = "metal-compact-bench", .description = "Build resident Metal compaction benchmark", .scope = .metal_tools },
    .{ .name = "cairo-streaming-commitment-bench", .description = "Build bounded production-callsite Cairo Metal commitment benchmark", .scope = .metal_tools },
    .{ .name = "cairo-streaming-commitment-test", .description = "Run bounded production-callsite Cairo Metal commitment parity test", .scope = .metal_tools },
    .{ .name = "metal-eval-prepare", .description = "Compile exact SN Cairo AIR programs for Metal", .scope = .metal_tools },
    .{ .name = "metal-eval-source", .description = "Build the exact Cairo AIR Metal source generator", .scope = .metal_tools },
    .{ .name = "metal-witness-source", .description = "Build the exact Cairo witness Metal source generator", .scope = .metal_tools },
    .{ .name = "metal-test", .description = "Run resident Metal backend parity tests", .scope = .metal_tools },
    .{ .name = "metal-check", .description = "Compile and link resident Metal backend tests without executing them", .scope = .metal_tools },
    .{ .name = "test-metal-resident-decommit", .description = "Run focused resident Metal Merkle decommit parity tests", .scope = .metal_tools },
    .{ .name = "metal-bench", .description = "Build resident Metal commitment benchmark", .scope = .metal_tools },
    .{ .name = "metal-circle-lde-bench", .description = "Build isolated Metal circle-LDE benchmark", .scope = .metal_tools },
    .{ .name = "cuda-test", .description = "Unavailable compatibility alias; CUDA now requires an explicit product toolchain", .scope = .deferred },
    .{ .name = "riscv-release-gate", .description = "Run the staged CLI and validate committed Sail/Spike evidence", .scope = .verification },
    .{ .name = "deep-gate", .description = "Run expanded deep graph coverage", .scope = .verification },
    .{ .name = "vectors", .description = "Validate committed parity vectors", .scope = .verification },
    .{ .name = "interop", .description = "Run interoperability harness (Rust <-> Zig proof exchange)", .scope = .verification },
    .{ .name = "prove-checkpoints", .description = "Run prove/prove_ex checkpoint harness (Rust -> Zig/Rust verification)", .scope = .verification },
    .{ .name = "bench-native-holistic-smoke", .description = "Run cheap non-headline CPU/Metal parity over the holistic native suite", .scope = .verification },
    .{ .name = "bench-smoke", .description = "Run benchmark smoke harness and emit report", .scope = .verification },
    .{ .name = "bench-kernels", .description = "Run targeted kernel benchmark harness", .scope = .verification },
    .{ .name = "bench-strict", .description = "Run strict benchmark harness (base + medium workloads, stabilized samples)", .scope = .verification },
    .{ .name = "bench-opt", .description = "Run optimization-track benchmark harness (native CPU)", .scope = .verification },
    .{ .name = "bench-opt-binary-codec", .description = "Run optimization-track benchmark with binary internal proof codec (non-default)", .scope = .verification },
    .{ .name = "bench-contrast", .description = "Run heavy contrast benchmark harness", .scope = .verification },
    .{ .name = "bench-contrast-long", .description = "Run long contrast benchmark harness", .scope = .verification },
    .{ .name = "bench-targeted-families", .description = "Run the benchmark family regression gate", .scope = .verification },
    .{ .name = "bench-pages", .description = "Render static benchmark pages assets", .scope = .verification },
    .{ .name = "bench-full", .description = "Run the full benchmark suite", .scope = .verification },
    .{ .name = "bench-pages-validate", .description = "Validate static benchmark pages assets are current", .scope = .verification },
    .{ .name = "profile-smoke", .description = "Run profiling smoke harness and emit report", .scope = .verification },
    .{ .name = "profile-opt", .description = "Run optimization-track profile harness", .scope = .verification },
    .{ .name = "profile-contrast", .description = "Run larger contrast profile harness", .scope = .verification },
    .{ .name = "profile-contrast-long", .description = "Run long contrast profile harness", .scope = .verification },
    .{ .name = "merkle-worker-stress", .description = "Run deterministic Merkle worker stress checks", .scope = .verification },
    .{ .name = "opt-gate", .description = "Run optimization acceptance gate", .scope = .verification },
    .{ .name = "std-shims-smoke", .description = "Build freestanding verifier profile shim", .scope = .verification },
    .{ .name = "std-shims-behavior", .description = "Validate std-shims verifier behavior parity", .scope = .verification },
    .{ .name = "release-evidence", .description = "Generate canonical release evidence manifest", .scope = .verification },
    .{ .name = "fmt", .description = "Check formatting", .scope = .policy },
    .{ .name = "api-parity", .description = "Validate API parity ledger coverage", .scope = .policy },
    .{ .name = "upstream-pins", .description = "Validate upstream pin carriers", .scope = .policy },
    .{ .name = "source-conformance", .description = "Reject source conformance regressions", .scope = .policy },
    .{ .name = "package-workspace", .description = "Audit package ownership, API, and dependency boundaries", .scope = .policy },
    .{ .name = "upstream-surface", .description = "Validate upstream API surface", .scope = .policy },
    .{ .name = "build-configure-closure", .description = "Verify focused configure closure", .scope = .policy },
    .{ .name = "registry-parity", .description = "Compare focused and aggregate registries", .scope = .policy },
    .{ .name = "release-gate", .description = "Run the standard release gate", .scope = .release },
    .{ .name = "release-gate-strict", .description = "Run the strict release gate", .scope = .release },
};

/// Configure declarations for scopes that are not a single catalog product.
/// Product scopes are derived directly from their product descriptors.
pub const configure = [_]Configure{
    .{ .scope = .architecture, .role = .gates, .external_tools = &.{"python3"}, .constructors = &.{ "gates/architecture_receipts.addGates", "gates/baseline.addGate" } },
    .{ .scope = .riscv_cpu_compat, .role = .product, .inherited_product_scope = .riscv_cpu, .constructors = &.{ "products/matrix.construct.riscv_cpu", "compatibility aliases" } },
    .{
        .scope = .riscv_metal,
        .role = .product,
        .product_ids = &.{"stwo-riscv-metal"},
        .module_roots = &.{
            "src/products/riscv_metal/main.zig",
            "src/riscv_metal_bench_cli.zig",
            "src/products/riscv_metal/root.zig",
            "src/integrations/riscv_metal/mod.zig",
            "src/tests/riscv/metal_backend_test.zig",
            "src/tests/riscv/recursive_framework_aot_test.zig",
            "src/tests/riscv/recursive_framework_resident_test.zig",
            "src/frontends/riscv/mod.zig",
        },
        // The production CLI carries `build_identity` and `product_identity`
        // options modules, and reaches the shared engine-generic adapter and
        // the proof-wire codec through their owning packages. Both are scope
        // observations rather than declarations, so they must be listed here
        // exactly: `check_build_configure_closure.py` compares the observed
        // generated and dependency roots against this catalog for equality,
        // not containment.
        .generated_module_roots = &.{"generated:options:"},
        .dependency_module_roots = &.{
            "dependency:../src/backend:mod.zig",
            "dependency:../src/backends/metal:mod.zig",
            "dependency:../src/core:mod.zig",
            "dependency:../src/frontends/riscv:mod.zig",
            "dependency:../src/integrations/riscv_cpu:proof_adapter.zig",
            "dependency:../src/integrations/riscv_metal:mod.zig",
            "dependency:../src/interop/proof_wire:mod.zig",
            "dependency:../src/prover:mod.zig",
            "dependency:../src/prover_api:mod.zig",
        },
        .external_tools = &.{"python3"},
        .runtime_probes = &.{ "Metal.framework", "Foundation.framework", "libobjc" },
        .allowed_module_files = &.{
            "src/backends/metal/runtime.m",
            "src/interop/output_transaction.zig",
            "src/interop/postcard.zig",
            "src/interop/riscv_artifact.zig",
            "src/products/riscv_metal/app.zig",
            "src/products/riscv_metal/capabilities.zig",
            "src/products/riscv_metal/cli.zig",
            "src/products/riscv_metal/guest_poseidon2_app.zig",
            "src/products/riscv_metal/registry.zig",
            "src/products/riscv_metal/runtime_admission.zig",
            "src/products/riscv_shared/app.zig",
            "src/products/riscv_shared/cli.zig",
            "src/products/riscv_shared/registry.zig",
        },
        .constructors = &.{"products/matrix.construct.riscv_metal"},
        .constructed_products = &.{.{
            .product_id = "stwo-riscv-metal",
            .frontend = "riscv",
            .backend = "metal",
            .role = "cli",
            .protocol_manifest = "rv32im-zkvm-v1+lifted-pcs-v1+metal-runtime-v2+authenticated-core-aot-v2+rv32im-zkvm-poseidon2-v1",
        }},
    },
    .{ .scope = .package, .role = .package_exports, .product_ids = &.{ "stwo-core", "stwo-prover", "stwo" }, .module_roots = &.{ "src/products/prover/root.zig", "src/stwo.zig" }, .generated_module_roots = &.{"generated:options:"}, .dependency_module_roots = package_dependencies.protocol_package_roots, .allowed_module_files = &.{ "src/stwo.zig", "build_support/graph/identity/emitter.zig" }, .allowed_module_prefixes = &.{ "src/products/core", "src/products/prover" }, .external_tools = &.{"python3"}, .constructors = &.{"products/libraries.addProducts"}, .constructed_products = &.{
        .{ .product_id = "stwo-core", .frontend = "none", .backend = "none", .role = "library", .protocol_manifest = "stwo-core-v1" },
        .{ .product_id = "stwo-prover", .frontend = "none", .backend = "contracts", .role = "library", .protocol_manifest = "generic-prover+backend-contracts-v1" },
        .{ .product_id = "stwo", .frontend = "aggregate", .backend = "contracts", .role = "library", .protocol_manifest = "aggregate-sdk-v1" },
    } },
    .{ .scope = .metal_tools, .role = .backend_tools, .product_ids = &.{"stwo-native-metal-tools"}, .module_roots = &.{ "src/stwo.zig", "src/backends/metal/shader_manifest.zig" }, .generated_module_roots = &.{"generated:options:"}, .dependency_module_roots = package_dependencies.metal_tools_package_roots, .allowed_module_files = &.{ "src/stwo.zig", "src/tests.zig", "src/metal_arena_plan_cli.zig", "src/riscv_metal_bench_cli.zig" }, .allowed_module_prefixes = &.{ "src/backends", "src/bench", "src/examples", "src/frontends", "src/integrations", "src/interop", "src/std_shims", "src/tools", "src/tracing" }, .runtime_probes = &.{ "Metal.framework", "Foundation.framework", "libobjc" }, .constructors = &.{ "backends/metal_aot.addProducts", "benchmarks/metal.addProducts" } },
    .{
        .scope = .cuda_tools,
        .role = .backend_tools,
        .product_ids = &.{"stwo-native-cuda-tools"},
        .module_roots = &.{
            "build_support/backends/cuda.zig",
            "src/tools/cairo_cuda_eval_aot/main.zig",
            "src/tools/cairo_cuda_witness_aot/main.zig",
            "src/tools/cairo_witness_cpu_codegen/model.zig",
        },
        .dependency_module_roots = package_dependencies.frontend_cuda_metal_cpu_protocol_package_roots,
        .allowed_module_files = &.{
            "tests/cuda/cumetal/native_frontend_execution.zig",
            "src/interop/felt_json.zig",
            "src/interop/postcard.zig",
            "src/products/native_cuda/blake_route.zig",
            "src/stwo.zig",
            "src/tools/cuda_native_ec_composite_oracle/main.zig",
            "tests/native_cuda_blake_exact_structure.zig",
            "tests/native_cuda_plonk_logup.zig",
            "tests/native_cuda_poseidon_arena.zig",
            "tests/native_cuda_state_machine.zig",
            "tests/native_cuda_xor_logup.zig",
        },
        .allowed_module_prefixes = &.{
            "build_support/backends",
            "src/backends/cuda",
            "src/tools/cairo_cuda_eval_aot",
            "src/tools/cairo_cuda_witness_aot",
            "src/tools/cairo_witness_cpu_codegen",
        },
        .external_tools = &.{"python3"},
        .constructors = &.{"backends/cuda_tools.addProducts"},
    },
    .{
        .scope = .compatibility_tools,
        .role = .compatibility_tools,
        .product_ids = &.{"stwo-compatibility-tools"},
        .module_roots = &.{
            "src/tools/interop/main.zig",
            "src/tools/cairo/input_inspector.zig",
            "src/tools/cairo/air_bundle_inspector.zig",
            "src/frontends/cairo/witness/composition_bundle.zig",
            "src/frontends/cairo/tests/mod.zig",
            "src/tests/cairo/cpu_air_test.zig",
            "src/tools/riscv_opcode_manifest/main.zig",
            "src/riscv_bench_cli.zig",
            "src/tools/native_proof_bench/cpu.zig",
        },
        .dependency_module_roots = package_dependencies.compatibility_package_roots,
        .allowed_module_files = &.{"src/stwo.zig"},
        .allowed_module_prefixes = &.{
            "src/frontends/cairo",
            "src/frontends/riscv",
            "src/integrations/riscv_cpu",
            "src/integrations/cairo_cpu",
            "src/interop",
            "src/products/native_cpu",
            "src/tests/cairo",
            "src/tools",
        },
        .constructors = &.{"products/compatibility_tools.addProducts"},
    },
    .{ .scope = .verification, .role = .gates, .external_tools = &.{ "python3", "zig" }, .constructors = &.{ "gates/riscv.addGates", "gates/native.addGates", "benchmarks/native.addProducts", "gates/release_evidence.addGates" } },
    .{ .scope = .policy, .role = .gates, .external_tools = &.{ "python3", "zig" }, .constructors = &.{"internal_build.addPolicyGates"} },
    .{ .scope = .release, .role = .gates, .product_ids = &.{"stwo-zig-release"}, .external_tools = &.{ "python3", "zig" }, .constructors = &.{"gates/release.addGates"} },
};

pub fn configureFor(scope: Scope) ?Configure {
    for (configure) |spec| if (spec.scope == scope) return spec;
    return null;
}

pub fn parse(name: []const u8) ?Scope {
    return std.meta.stringToEnum(Scope, name);
}
