-- Every module in the development, imported here on purpose.
--
-- `lakefile.toml` globs the whole directory so nothing goes uncompiled, but
-- the axiom audit walks the *environment*, and the environment only contains
-- what this root module transitively imports. A file that Lake compiles but
-- this root does not import would be checked for errors and never audited for
-- axioms, which is exactly the silent gap the audit exists to close.
import RiscvRefinement.Common
import RiscvRefinement.Memory
import RiscvRefinement.Mutation
import RiscvRefinement.Arith.Division
import RiscvRefinement.Bridge.Decode
import RiscvRefinement.Bridge.DecodeBaseAlu
import RiscvRefinement.Bridge.DecodeBranches
import RiscvRefinement.Bridge.DecodeLt
import RiscvRefinement.Bridge.DecodeTeamA
import RiscvRefinement.Bridge.DecodeTeamB
import RiscvRefinement.Air.Generated.Pilot
import RiscvRefinement.Air.Family.LoadStore
import RiscvRefinement.Air.Family.Shifts
import RiscvRefinement.Air.Family.Multiply
import RiscvRefinement.Air.Family.Div
import RiscvRefinement.Air.Bridge.MulProgram
import RiscvRefinement.Air.Bridge.MulBridge
import RiscvRefinement.Air.Bridge.MulhProgram
import RiscvRefinement.Air.Bridge.MulhBridge
import RiscvRefinement.Air.Bridge.EvaluatorSpec
import RiscvRefinement.Air.Bridge.LoadStoreProgram
import RiscvRefinement.Air.Bridge.LoadStoreBridge
import RiscvRefinement.Air.Bridge.DivProgram
import RiscvRefinement.Air.Bridge.DivBridge
import RiscvRefinement.Air.Bridge.Branches
import RiscvRefinement.Air.Bridge.Auipc
import RiscvRefinement.Air.Bridge.BaseAluImm
import RiscvRefinement.Air.Bridge.BaseAluReg
import RiscvRefinement.Air.Bridge.Fence
import RiscvRefinement.Air.Bridge.Jal
import RiscvRefinement.Air.Bridge.Jalr
import RiscvRefinement.Air.Bridge.LtImm
import RiscvRefinement.Air.Bridge.LtReg
import RiscvRefinement.Sail.Generated.Pilot
import RiscvRefinement.Sail.Reviewed.LoadStore
import RiscvRefinement.Sail.Reviewed.Shifts
import RiscvRefinement.Sail.Reviewed.Multiply
import RiscvRefinement.Sail.Reviewed.Div
import RiscvRefinement.Opcodes.Lui
import RiscvRefinement.Opcodes.Addi
import RiscvRefinement.Opcodes.Fence
import RiscvRefinement.Opcodes.FenceMutation
import RiscvRefinement.Opcodes.Branches
import RiscvRefinement.Opcodes.BranchesMutation
import RiscvRefinement.Opcodes.Auipc
import RiscvRefinement.Opcodes.AuipcMutation
import RiscvRefinement.Opcodes.BaseAluImm
import RiscvRefinement.Opcodes.BaseAluReg
import RiscvRefinement.Opcodes.BaseAluMutation
import RiscvRefinement.Opcodes.Jal
import RiscvRefinement.Opcodes.JalMutation
import RiscvRefinement.Opcodes.Jalr
import RiscvRefinement.Opcodes.JalrMutation
import RiscvRefinement.Opcodes.Lt
import RiscvRefinement.Opcodes.LtMutation
import RiscvRefinement.Opcodes.LoadStore
import RiscvRefinement.Opcodes.Shifts
import RiscvRefinement.Opcodes.Multiply
import RiscvRefinement.Opcodes.MultiplyMutation
import RiscvRefinement.Opcodes.Div
import RiscvRefinement.Opcodes.LoadStoreMutation
import RiscvRefinement.Opcodes.LoadStoreMutationExtra
import RiscvRefinement.Opcodes.ShiftsMutation
import RiscvRefinement.Opcodes.ShiftsRegMutation
import RiscvRefinement.Opcodes.DivMutation
import RiscvRefinement.Opcodes.DivMutationExtra
import RiscvRefinement.Opcodes.LoadMutationByte
import RiscvRefinement.Opcodes.LoadMutationWord
import RiscvRefinement.Opcodes.MultiplyMutationExtra
import RiscvRefinement.Opcodes.SelectorNonVacuity
import RiscvRefinement.Opcodes.StoreMutation
import RiscvRefinement.NonVacuity
import RiscvRefinement.Coverage
import RiscvRefinement.Air.Tests
import RiscvRefinement.Air.Bridge.Addi
import RiscvRefinement.Air.Bridge.Lui
import RiscvRefinement.Air.Bridge.Mutations
import RiscvRefinement.Air.Generated.LuiProgram
import RiscvRefinement.Air.Generated.Programs
import RiscvRefinement.Bridge.DecodeTeamB
import RiscvRefinement.Memory
