//! Typed component construction for the complete binary FRI bundle.

const source_mod = @import("binary_fri_outer_source.zig");

pub fn init(
    self: anytype,
    manifest: anytype,
    relations: anytype,
    provider_relations: anytype,
    generated: anytype,
    comptime ManifestComponents: type,
    comptime Adapters: type,
    comptime parametersFromRows: anytype,
    comptime validateGeneratedInteractions: anytype,
    comptime bundleLogSizes: anytype,
    comptime providerCallCount: anytype,
) !ManifestComponents {
    try validateGeneratedInteractions(
        self,
        generated,
        relations,
        provider_relations,
    );
    const source = self.source;
    const composition = source.composition_rows.?;
    const arithmetic = source.arithmetic_rows.?;
    const all_logs = bundleLogSizes(self);
    const logs = all_logs[0..source_mod.TYPED_RELATION_ROW_COUNT].*;
    const rows = &self.relation_rows;
    return .{
        .composition_input = try Adapters.CompositionInput.init(
            &composition.input_definition,
            composition.input_relation,
            manifest,
            .vm_air_composition_input,
            logs[0],
            try parametersFromRows(Adapters.CompositionInput, rows.composition_input),
            relations,
            generated.claims.typed_rows[0],
        ),
        .composition_control = try Adapters.CompositionControl.init(
            &composition.control_definition,
            composition.control_relation,
            manifest,
            .vm_air_composition_control,
            logs[1],
            try parametersFromRows(Adapters.CompositionControl, rows.composition_control),
            relations,
            generated.claims.typed_rows[1],
        ),
        .query_bits = try Adapters.QueryBits.init(
            &source.fri_rows.query_bits_definition,
            source.fri_rows.query_bits_relation,
            manifest,
            .query_bits,
            logs[2],
            try parametersFromRows(Adapters.QueryBits, rows.query_bits),
            relations,
            generated.claims.typed_rows[2],
        ),
        .query_mapping = try Adapters.QueryMapping.init(
            &source.fri_rows.query_mapping_definition,
            source.fri_rows.query_mapping_relation,
            manifest,
            .query_mapping,
            logs[3],
            try parametersFromRows(Adapters.QueryMapping, rows.query_mapping),
            relations,
            generated.claims.typed_rows[3],
        ),
        .merkle_root = try Adapters.MerkleRoot.init(
            &source.fri_rows.merkle_root_definition,
            source.fri_rows.merkle_root_relation,
            manifest,
            .merkle_root,
            logs[4],
            try parametersFromRows(Adapters.MerkleRoot, rows.merkle_root),
            relations,
            generated.claims.typed_rows[4],
        ),
        .trace_merkle = try Adapters.TraceMerkle.init(
            &source.fri_rows.trace_merkle_definition,
            source.fri_rows.trace_merkle_relation,
            manifest,
            .trace_merkle,
            logs[5],
            try parametersFromRows(Adapters.TraceMerkle, rows.trace_merkle),
            relations,
            generated.claims.typed_rows[5],
        ),
        .pcs_deep = try Adapters.Pcs.init(
            &source.fri_rows.pcs_definition,
            source.fri_rows.pcs_relation,
            manifest,
            .pcs_deep_input,
            logs[6],
            try parametersFromRows(Adapters.Pcs, rows.pcs_deep),
            relations,
            generated.claims.typed_rows[6],
        ),
        .fri_leaf = try Adapters.FriLeaf.init(
            &source.fri_rows.fri_leaf_definition,
            source.fri_rows.fri_leaf_relation,
            manifest,
            .fri_merkle_leaf,
            logs[7],
            try parametersFromRows(Adapters.FriLeaf, rows.fri_leaf),
            relations,
            generated.claims.typed_rows[7],
        ),
        .fri_node = try Adapters.FriNode.init(
            &source.fri_rows.fri_node_definition,
            source.fri_rows.fri_node_relation,
            manifest,
            .fri_merkle_node,
            logs[8],
            try parametersFromRows(Adapters.FriNode, rows.fri_node),
            relations,
            generated.claims.typed_rows[8],
        ),
        .fri_anchor = try Adapters.FriAnchor.init(
            &source.fri_rows.fri_anchor_definition,
            source.fri_rows.fri_anchor_relation,
            manifest,
            .fri_merkle_anchor,
            logs[9],
            try parametersFromRows(Adapters.FriAnchor, rows.fri_anchor),
            relations,
            generated.claims.typed_rows[9],
        ),
        .fri_control = try Adapters.FriControl.init(
            &source.fri_rows.control_definition,
            source.fri_rows.control_relation,
            manifest,
            .fri_verifier_control,
            logs[10],
            try parametersFromRows(Adapters.FriControl, rows.fri_control),
            relations,
            generated.claims.typed_rows[10],
        ),
        .fri_input = try Adapters.FriInput.init(
            &source.fri_rows.input_definition,
            source.fri_rows.input_relation,
            manifest,
            .fri_verifier_input,
            logs[11],
            try parametersFromRows(Adapters.FriInput, rows.fri_input),
            relations,
            generated.claims.typed_rows[11],
        ),
        .multiply = try Adapters.Multiply.init(
            &arithmetic.multiply_definition,
            arithmetic.multiply_relation,
            manifest,
            .qm31_mul,
            logs[12],
            try parametersFromRows(Adapters.Multiply, rows.multiply),
            relations,
            generated.claims.typed_rows[12],
        ),
        .inverse = try Adapters.Inverse.init(
            &arithmetic.inverse_definition,
            arithmetic.inverse_relation,
            manifest,
            .qm31_inv,
            logs[13],
            try parametersFromRows(Adapters.Inverse, rows.inverse),
            relations,
            generated.claims.typed_rows[13],
        ),
        .linear = try Adapters.Linear.init(
            &arithmetic.linear_definition,
            arithmetic.linear_relation,
            manifest,
            .linear_ops,
            logs[14],
            try parametersFromRows(Adapters.Linear, rows.linear),
            relations,
            generated.claims.typed_rows[14],
        ),
        .merkle_path = try Adapters.MerklePath.init(
            &source.merkle_rows.definition,
            source.merkle_rows.relation,
            manifest,
            .merkle_path,
            logs[15],
            try parametersFromRows(Adapters.MerklePath, rows.merkle_path),
            relations,
            generated.claims.typed_rows[15],
        ),
        .poseidon2 = try Adapters.Poseidon2.init(
            manifest,
            self.provider_log_size,
            @intCast(providerCallCount(self)),
            provider_relations,
            relations,
            generated.claims.poseidon2_partials,
        ),
    };
}
