const std = @import("std");
const core = @import("stwo_core");
const recorder = @import("../blake3_native_recorder.zig");
const Q = core.fields.qm31.QM31;
test "BLAKE3 native recorder owns encoder temporaries and propagates allocation failures" {
    const a = std.testing.allocator;
    try run(a);
    try std.testing.checkAllAllocationFailures(a, run, .{});
}
fn run(backing: std.mem.Allocator) !void {
    var arena = std.heap.ArenaAllocator.init(backing);
    defer arena.deinit();
    const a = arena.allocator();
    var r = recorder.Recorder{ .a = a };
    var words = [_]u32{ 7, 8 };
    r.mixU32s(&words);
    try r.check();
    words[0] = 9;
    try std.testing.expectEqual(@as(u32, 7), r.operations.items[0].words[0]);
    r.private_felts = true;
    var felts = [_]Q{Q.one()};
    r.mixFelts(&felts);
    try r.check();
    felts[0] = Q.zero();
    try std.testing.expect(r.payloads.items[0].values[0].eql(Q.one()));
    const valid = r.verifyPowNonce(0, 19);
    try r.check();
    try std.testing.expect(valid);
    r.mixU64(19);
    try r.check();
    const draws = try r.drawSecureFelts(a, 2);
    defer a.free(draws);
    try std.testing.expectEqual(@as(usize, 1), r.relation_count);
    try std.testing.expectEqual(@as(usize, 0), r.operations.items[4].secure.output.?.riscv_relation);
    var oracle = core.channel.blake3.Channel{};
    oracle.mixU32s(&.{ 7, 8 });
    oracle.mixFelts(&.{Q.one()});
    oracle.mixU64(19);
    const expected = try oracle.drawSecureFelts(a, 2);
    defer a.free(expected);
    try std.testing.expectEqualSlices(Q, expected, draws);
    r.mixRoot(@splat(0x80));
    try r.check();
    oracle.mixRoot(@splat(0x80));
    try std.testing.expectEqualDeep(oracle, r.native);
    try std.testing.expectError(error.InvalidNativeBlake3Transcript, r.drawSecureFelts(a, 1));
    const state = r.native;
    _ = r.verifyPowNonce(0, 20);
    try r.check();
    r.mixU64(21);
    try std.testing.expectError(error.InvalidNativeBlake3Transcript, r.check());
    try std.testing.expectEqualDeep(state, r.native);
}
