/*
 * Test-only link definitions for Zig wrapper type checking on non-CUDA hosts.
 * C's empty parameter list deliberately accepts the real ABI arguments; no
 * pointer is dereferenced and the production archive never compiles this file.
 */
#define STUB(name) int name() { return 0; }

STUB(stwo_accumulate_quotient_numerator_single_write_on)
STUB(stwo_blake2s_fri_leaf_on)
STUB(stwo_blake2s_interior4_on)
STUB(stwo_blake2s_layer_on)
STUB(stwo_blake2s_pow_persistent_on)
STUB(stwo_blake2s_progressive_absorb_on)
STUB(stwo_blake2s_progressive_finalize_on)
STUB(stwo_blake2s_progressive_init_on)
STUB(stwo_blake2s_transcript_absorb_pow_on)
STUB(stwo_blake2s_transcript_draw_queries_on)
STUB(stwo_blake2s_transcript_draw_secure_on)
STUB(stwo_blake2s_transcript_draw_u32s_on)
STUB(stwo_blake2s_transcript_init_on)
STUB(stwo_blake2s_transcript_mix_words_on)
STUB(stwo_combine_quotients_from_numerators_on)
STUB(stwo_decommit_assemble_fri_on)
STUB(stwo_decommit_assemble_trace_on)
STUB(stwo_decommit_normalize_queries_on)
STUB(stwo_decommit_pack_trace_group_on)
STUB(stwo_decommit_prepare_fri_queries_on)
STUB(stwo_decommit_prepare_trace_queries_on)
STUB(stwo_decommit_sparse_parent_on)
STUB(stwo_finalize_quotient_numerator_groups_on)
STUB(stwo_fold_circle_into_line_on)
STUB(stwo_fold_line_on)
STUB(stwo_fri_fold_fused3_on)
STUB(stwo_fri_last_layer_on)
STUB(stwo_lde_n2b_columns_before_circle_on)
STUB(stwo_lde_n2b_columns_on)
STUB(stwo_ntt_b2n_columns_to_retained_on)
STUB(stwo_ntt_n2b_columns_on)
STUB(stwo_oods_barycentric_eval_many_on)
STUB(stwo_oods_barycentric_weights_on)
STUB(stwo_oods_derive_points_on)
STUB(stwo_oods_eval_first_on)
STUB(stwo_oods_eval_reduce_on)
STUB(stwo_oods_store_results_on)
STUB(stwo_prepare_quotient_numerator_terms_on)
STUB(stwo_zero_quotient_numerator_outputs_on)
