#!/usr/bin/env python3
"""Canonical direct Zig commands for the named Stwo protocol module graph."""

from __future__ import annotations

from pathlib import Path


def protocol_module_args(root_source: str) -> list[str]:
    return [
        "--dep",
        "stwo_core",
        "--dep",
        "stwo_backend_contracts",
        "--dep",
        "stwo_prover_impl",
        "--dep",
        "stwo_cpu_backend",
        "--dep",
        "stwo_riscv_frontend",
        "--dep",
        "stwo_cairo_frontend",
        f"-Mroot={root_source}",
        "-Mstwo_core=src/core/mod.zig",
        "--dep",
        "stwo_core",
        "-Mstwo_backend_contracts=src/backend/mod.zig",
        "--dep",
        "stwo_core",
        "--dep",
        "stwo_backend_contracts",
        "-Mstwo_prover_impl=src/prover/mod.zig",
        "--dep",
        "stwo_core",
        "--dep",
        "stwo_backend_contracts",
        "--dep",
        "stwo_prover_impl",
        "-Mstwo_cpu_backend=src/backends/cpu_scalar/mod.zig",
        "--dep",
        "stwo_core",
        "--dep",
        "stwo_prover_impl",
        "-Mstwo_riscv_frontend=src/frontends/riscv/mod.zig",
        "--dep",
        "stwo_core",
        "--dep",
        "stwo_backend_contracts",
        "--dep",
        "stwo_prover_impl",
        "-Mstwo_cairo_frontend=src/frontends/cairo/mod.zig",
    ]


def test_command(root_source: str, *arguments: str) -> list[str]:
    return ["zig", "test", *protocol_module_args(root_source), *arguments]


def aggregate_run_command(root_source: str, *arguments: str) -> list[str]:
    return [
        "zig",
        "run",
        "-lc",
        "--dep",
        "stwo",
        "--dep",
        "stwo_core",
        "--dep",
        "stwo_backend_contracts",
        "--dep",
        "stwo_prover_impl",
        "--dep",
        "stwo_cpu_backend",
        "--dep",
        "stwo_riscv_frontend",
        "--dep",
        "stwo_cairo_frontend",
        f"-Mroot={root_source}",
        "--dep",
        "stwo_core",
        "--dep",
        "stwo_backend_contracts",
        "--dep",
        "stwo_prover_impl",
        "--dep",
        "stwo_cpu_backend",
        "--dep",
        "stwo_riscv_frontend",
        "--dep",
        "stwo_cairo_frontend",
        "-Mstwo=src/stwo.zig",
        "-Mstwo_core=src/core/mod.zig",
        "--dep",
        "stwo_core",
        "-Mstwo_backend_contracts=src/backend/mod.zig",
        "--dep",
        "stwo_core",
        "--dep",
        "stwo_backend_contracts",
        "-Mstwo_prover_impl=src/prover/mod.zig",
        "--dep",
        "stwo_core",
        "--dep",
        "stwo_backend_contracts",
        "--dep",
        "stwo_prover_impl",
        "-Mstwo_cpu_backend=src/backends/cpu_scalar/mod.zig",
        "--dep",
        "stwo_core",
        "--dep",
        "stwo_prover_impl",
        "-Mstwo_riscv_frontend=src/frontends/riscv/mod.zig",
        "--dep",
        "stwo_core",
        "--dep",
        "stwo_backend_contracts",
        "--dep",
        "stwo_prover_impl",
        "-Mstwo_cairo_frontend=src/frontends/cairo/mod.zig",
        "--",
        *arguments,
    ]


def source_contract() -> tuple[Path, ...]:
    root = Path(__file__).resolve().parents[2]
    return (
        Path(__file__).resolve(),
        root / "src/core/mod.zig",
        root / "src/backend/mod.zig",
        root / "src/prover/mod.zig",
        root / "src/backends/cpu_scalar/mod.zig",
        root / "src/frontends/riscv/mod.zig",
        root / "src/frontends/cairo/mod.zig",
    )
