#!/usr/bin/env python3
"""Deterministically bind S31's Lean inventory/constants to repository sources.

Generation does not establish compiler correctness. The committed bindings make
semantic source changes visible to the formal CI gate and its reviewer.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
if __package__ in (None, ""):
    sys.path.insert(0, str(ROOT))
from scripts.s31_formal_lib.checks import (
    FormalError, check_audit, check_coverage, check_kernel_log, inventory, render_coverage,
)
from scripts.riscv_refinement import _skip_lean_string, _strip_lean_comments
from scripts.riscv_refinement_lib.model import RefinementError

FORMAL = ROOT / "formal/s31"
RELATION = "src/frontends/s31/language/relation.zig"
POSEIDON = "src/frontends/riscv/air/memory_commitment/poseidon2_constants.zig"
SHA = "src/frontends/riscv/air/guest_precompile/sha256_compression.zig"
SIGMA = "src/core/crypto/blake_sigma.zig"
BINDINGS = [
    RELATION,
    "src/frontends/s31/language/relation_compiler.zig",
    "src/frontends/s31/library/hash/poseidon2.zig",
    "src/core/crypto/blake2s_terminal_parallel.zig",
    "src/frontends/s31/library/hash/sha256d.zig",
    "src/frontends/s31/bitcoin/consensus/bitcoin_target.zig",
    "src/frontends/s31/bitcoin/consensus/bitcoin_work.zig",
    "src/frontends/circuit/builder/wrappers.zig",
    "src/frontends/circuit/builder/simd.zig",
    "src/frontends/circuit/builder/context.zig",
    "src/frontends/circuit/air_eval/manual/circuit.zig",
    "src/core/fields/m31.zig",
    "src/core/fields/cm31.zig",
    "src/core/fields/qm31.zig",
    "formal/riscv-refinement/RiscvRefinement/Field/M31.lean",
    "formal/riscv-refinement/RiscvRefinement/Recursion/CompactPoseidon.lean",
    "formal/riscv-refinement/lakefile.toml",
    "formal/s31/lakefile.toml",
    "formal/s31/lake-manifest.json",
    "formal/s31/lean-toolchain",
    "src/frontends/s31/python/oracle.py",
    "src/frontends/s31/python/poseidon2_oracle.py",
    POSEIDON, SHA, SIGMA,
]


def lean_code(source: str) -> str:
    """Reuse the refinement lexer at the command's cross-package boundary."""
    try:
        result = _strip_lean_comments(source)
    except RefinementError as error:
        raise FormalError(str(error)) from error
    rendered = list(result)
    index = 0
    while index < len(result):
        if result[index] == '"':
            end = _skip_lean_string(result, index)
            for i in range(index, end):
                if rendered[i] != "\n":
                    rendered[i] = " "
            index = end
        else:
            index += 1
    return "".join(rendered)


def array_values(path: str, name: str, count: int) -> list[int]:
    source = (ROOT / path).read_text()
    body = source.split(f"pub const {name}", 1)[1].split("=", 1)[1]
    body = body.split(";", 1)[0]
    body = re.sub(r"//[^\n]*", "", body)
    # A type expression after '=' may contain dimension identifiers, but the
    # source arrays used here contain no numeric dimensions before the body.
    values = [int(n.replace("_", ""), 0 if n.startswith("0x") else 10)
              for n in re.findall(r"\b(?:0x[0-9a-fA-F_]+|[0-9][0-9_]*)\b", body)]
    if len(values) != count:
        raise ValueError(f"{path}:{name}: expected {count}, got {len(values)}")
    return values


def lean_list(values: list[int]) -> str:
    return "[" + ", ".join(map(str, values)) + "]"


def generated() -> dict[Path, str]:
    source = (ROOT / RELATION).read_text()
    ops = [op.strip() for op in re.search(
        r"pub const Op = enum \{([^}]+)\};", source).group(1).split(",")]
    op = "/-! Generated by scripts/s31_formal.py from S31 relation IR v1. -/\n"
    op += "namespace S31\n\ninductive Op where\n"
    op += "".join(f"  | {name}\n" for name in ops)
    op += "deriving DecidableEq, Repr, BEq\n\n"
    op += "def Op.wireName : Op → String\n"
    op += "".join(f'  | .{name} => "{name}"\n' for name in ops)
    op += "\ndef Op.ofWireName : String → Option Op\n"
    op += "".join(f'  | "{name}" => some .{name}\n' for name in ops)
    op += "  | _ => none\n\ndef allOps : List Op := [\n"
    op += ",\n".join(f"  .{name}" for name in ops)
    op += "]\n\nend S31\n"

    constants = "/-! Generated by scripts/s31_formal.py; do not edit by hand. -/\n"
    constants += "namespace S31.Constants\n\n"
    for name, path, zig_name, count, row in [
        ("poseidonExternal", POSEIDON, "EXTERNAL_ROUND", 128, 16),
        ("poseidonInternal", POSEIDON, "INTERNAL_ROUND", 14, 0),
        ("poseidonDiagonal", POSEIDON, "INTERNAL_MATRIX", 16, 0),
        ("hashIV", SHA, "initial_state", 8, 0),
        ("shaRound", SHA, "round_constants", 64, 0),
        ("blakeSigma", SIGMA, "BLAKE_SIGMA", 160, 16),
        ("genesisBytes", RELATION, "mainnet_genesis_hash_raw", 32, 0),
    ]:
        values = array_values(path, zig_name, count)
        if row:
            rows = [lean_list(values[i:i + row]) for i in range(0, count, row)]
            constants += f"def {name} : List (List Nat) := [\n  "
            constants += ",\n  ".join(rows) + "]\n\n"
        else:
            constants += f"def {name} : List Nat := {lean_list(values)}\n\n"
    constants += "end S31.Constants\n"

    identity = {"schema": 1, "boundary": "normalized relation IR v1", "ops": ops,
                "sources": {p: hashlib.sha256((ROOT / p).read_bytes()).hexdigest()
                            for p in BINDINGS}}
    return {
        FORMAL / "S31/Semantics/Op.lean": op,
        FORMAL / "S31/Semantics/Constants.lean": constants,
        FORMAL / "S31/Evidence/Coverage.lean": render_coverage(
            json.loads((FORMAL / "coverage.json").read_text())),
        FORMAL / "source-bindings.json": json.dumps(identity, indent=2) + "\n",
    }


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--write", action="store_true", help="regenerate reviewed bindings")
    parser.add_argument("--audit", type=Path, help="validate the live Lean theorem/axiom log")
    parser.add_argument("--parity", type=Path, help="compare the built s31-check to the Python oracle")
    parser.add_argument("--controls", action="store_true", help="compile honest/false/mutated gadget controls")
    parser.add_argument("--lake", default="lake", help="Lake executable used for live controls")
    parser.add_argument("--kernel-log", type=Path, help="validate the successful verbose kernel replay log")
    parser.add_argument("--report", type=Path, help="write complete live CI evidence (requires all live checks)")
    args = parser.parse_args()
    if args.report and (args.write or not all((args.audit, args.parity, args.controls, args.kernel_log))):
        parser.error("--report requires --audit, --kernel-log, --parity and --controls; exclude --write")
    failures = []
    for path, expected in generated().items():
        if args.write:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(expected)
        elif not path.exists() or path.read_text() != expected:
            failures.append(str(path.relative_to(ROOT)))
    source_inventory = inventory(ROOT, lean_code)
    inventory_path = FORMAL / "proof-inventory.json"
    expected_inventory = json.dumps(source_inventory, indent=2) + "\n"
    if args.write:
        inventory_path.write_text(expected_inventory)
    elif not inventory_path.is_file() or inventory_path.read_text() != expected_inventory:
        failures.append("formal/s31/proof-inventory.json")
    if failures:
        raise SystemExit("stale S31 formal bindings: " + ", ".join(failures))
    print("S31 formal source bindings: OK")
    ops = json.loads((FORMAL / "source-bindings.json").read_text())["ops"]
    check_coverage(ROOT, ops, json.loads((FORMAL / "coverage.json").read_text()),
                   set(source_inventory["theorems"]))
    print(f"S31 operation/proof inventory: {len(ops)} operations, "
          f"{len(source_inventory['theorems'])} theorems")
    evidence = {"schema": "s31-formal-live-evidence-v1", "operations": len(ops),
                "source_inventory_sha256": hashlib.sha256(expected_inventory.encode()).hexdigest(),
                "production_compiler_correctness_proved": False,
                "stark_soundness_or_zero_knowledge_proved": False}
    if args.audit:
        result = check_audit(args.audit.read_text(), set(source_inventory["theorems"]))
        print(f"S31 axiom audit: {result['theorems']} theorems, approved axioms only")
        evidence["axiom_audit"] = result
    if args.kernel_log:
        result = check_kernel_log(args.kernel_log.read_text(), source_inventory["files"])
        print(f"S31 kernel replay: {result['replayed_modules']} modules")
        evidence["kernel_replay"] = result
    if args.parity:
        from scripts.s31_formal_lib.parity import run
        evidence["semantic_parity"] = run(args.parity.resolve())
        print("S31 independent semantic parity: " + json.dumps(evidence["semantic_parity"], sort_keys=True))
    if args.controls:
        from scripts.s31_formal_lib.controls import run
        evidence["controls"] = run(ROOT, args.lake)
        print("S31 kernel controls: " + json.dumps(evidence["controls"], sort_keys=True))
    if args.report:
        args.report.parent.mkdir(parents=True, exist_ok=True)
        args.report.write_text(json.dumps(evidence, indent=2) + "\n")


if __name__ == "__main__":
    try:
        main()
    except (FormalError, OSError, ValueError, KeyError) as error:
        raise SystemExit(str(error)) from error
