from pathlib import Path
import hashlib,json
src=Path('src/integrations/riscv_cpu/recursive_common_ethereum_incremental_leaf_genuine_runtime_v4.zig')
s=src.read_text(); start=s.index('/// Thin counter around');end=s.index('\nfn executionReceiptIdentity',start);old=s[start:end]
new=old.replace('TrackedSmpAllocatorV4','TrackedSmpAllocator')
Path('/tmp/pr198-tracked-allocator-original-v1.txt').write_text(old)
dst=Path('src/prover/tracked_smp_allocator.zig');dst.write_text('//! Shared producer allocation ownership accounting.\n//! Historical diagnostic/error names remain stable for existing consumers.\nconst std = @import("std");\n\n'+new)
src.write_text(s[:start]+'/// Compatibility alias; the shared prover owns allocation accounting.\npub const TrackedSmpAllocatorV4 = @import("stwo_prover_engine").tracked_smp_allocator.TrackedSmpAllocator;\n'+s[end:])
p=Path('src/prover/mod.zig');s=p.read_text().replace('pub const host_budget_allocator =','pub const tracked_smp_allocator = @import("tracked_smp_allocator.zig");\npub const host_budget_allocator =').replace('    _ = host_budget_allocator;','    _ = host_budget_allocator;\n    _ = @import("tracked_smp_allocator_test.zig");');p.write_text(s)
p=Path('src/integrations/riscv_cpu/recursive_segment_v2_outer_engine.zig');s=p.read_text().replace('@import("recursive_common_ethereum_incremental_leaf_genuine_runtime_v4.zig").TrackedSmpAllocatorV4','prover_engine.tracked_smp_allocator.TrackedSmpAllocator');p.write_text(s)
p=Path('src/integrations/riscv_cpu/recursive_segment_v2_two_segment_proof_test_support.zig');s=p.read_text().replace('integration.recursive_segment_v2_outer_engine.ProducerAllocator','@import("stwo_prover_engine").tracked_smp_allocator.TrackedSmpAllocator');p.write_text(s)
p=Path('src/integrations/riscv_cpu/recursive_common_ethereum_incremental_leaf_materializer_v4_test.zig');s=p.read_text();start=s.index('    var tracked = runtime_mod.TrackedSmpAllocatorV4{};',s.index('test "role0 genuine runtime allocator'));end=s.index('    const policy =',start);test=s[start:end].replace('runtime_mod.TrackedSmpAllocatorV4','TrackedSmpAllocator');s=s[:start]+s[end:];start=s.index('fn exerciseTrackedAllocator(');end=s.index('\ntest ',start);helper=s[start:end].replace('runtime_mod.TrackedSmpAllocatorV4','TrackedSmpAllocator');s=s[:start]+s[end:];s=s.replace('role0 genuine runtime allocator counts ownership and host workers','role0 genuine runtime accounts host workers');p.write_text(s)
Path('src/prover/tracked_smp_allocator_test.zig').write_text('const std = @import("std");\nconst TrackedSmpAllocator = @import("tracked_smp_allocator.zig").TrackedSmpAllocator;\n\ntest "tracked SMP allocator preserves ownership through growth and concurrent release" {\n'+test+'}\n\n'+helper)
p=Path('src/integrations/riscv_cpu/build_segment_steps.zig');p.write_text(p.read_text().replace('role0 genuine runtime allocator counts ownership and host workers','role0 genuine runtime accounts host workers'))
assert dst.read_text().split('const std = @import("std");\n\n',1)[1].replace('TrackedSmpAllocator','TrackedSmpAllocatorV4')==old
Path('/tmp/pr198-tracked-allocator-transfer-v1.json').write_text(json.dumps({'body_identical_after_type_rename':True,'original_body_sha256':hashlib.sha256(old.encode()).hexdigest(),'new_source':str(dst),'algorithm_changed':False,'existing_growth_and_concurrency_test_moved':True},indent=2)+'\n')
