//! Native BLAKE3 interaction kernels come only from authenticated typed AIRs.
const std = @import("std");
const frontend = @import("stwo_riscv_frontend");
const air = frontend.recursion.air;
const metal = @import("stwo_metal_backend");
const codegen = metal.riscv_polynomial_codegen.framework_interaction;

test "recursive framework AOT matches native BLAKE3 interaction catalog" {
    const a = std.testing.allocator;
    const path: ?[]u8 = std.process.getEnvVarOwned(a, "STWO_BLAKE3_INTERACTION_AOT_GENERATE") catch |err| switch (err) {
        error.EnvironmentVariableNotFound => null,
        else => return err,
    };
    defer if (path) |value| a.free(value);
    var source: std.ArrayList(u8) = .empty;
    defer source.deinit(a);
    var inventory: std.ArrayList(u8) = .empty;
    defer inventory.deinit(a);
    try source.appendSlice(a, "// Generated from the canonical typed BLAKE3 commitment AIRs.\n");
    try source.appendSlice(a, codegen.scan_source);
    try inventory.appendSlice(a, "// Generated by src/tests/riscv/blake3_interaction_aot_test.zig\npub const entries = .{\n");
    for ([_][]const u8{
        "stwo_zig_framework_interaction_block_scan_v1",            "stwo_zig_framework_interaction_scan_blocks_v1",            "stwo_zig_framework_interaction_finalize_v1",
        "stwo_zig_framework_interaction_cumulative_block_scan_v1", "stwo_zig_framework_interaction_cumulative_scan_blocks_v1", "stwo_zig_framework_interaction_cumulative_finalize_v1",
    }) |name| {
        const digest = try metal.shaders.declaration_digest.declarationDigestHex(codegen.scan_source, name);
        try inventory.writer(a).print("    .{{ .name = \"{s}\", .declaration_sha256 = \"{s}\" }},\n", .{ name, digest });
    }
    inline for (frontend.prover_mod.blake3_commitment_components.Airs) |Air| {
        var definition = try Air.build(a);
        defer definition.deinit();
        const direct = try air.direct_constraint_program.authenticate(&definition.arena, Air.SEMANTIC_DIGEST, Air.LOGICAL_INPUT_COUNT);
        const relations = try air.universal_relation_binding.Binding(Air).authenticate(&definition);
        var program = try air.framework_polynomial_export_v1.exportLocalPrepared(Air, a, &direct, &relations);
        defer program.deinit();
        const counts = [_]usize{ Air.PREPROCESSED_COLUMN_COUNT, Air.PHYSICAL_MAIN_COLUMN_COUNT, Air.INTERACTION_COLUMN_COUNT };
        const selected = codegen.Entry{ .program = &program, .tree_column_counts = &counts };
        const name = try codegen.kernelName(a, selected);
        defer a.free(name);
        const start = source.items.len;
        try codegen.emitKernel(a, source.writer(a), name, selected);
        const digest = try metal.shaders.declaration_digest.declarationDigestHex(source.items[start..], name);
        try inventory.writer(a).print("    .{{ .name = \"{s}\", .declaration_sha256 = \"{s}\" }},\n", .{ name, digest });
    }
    try inventory.appendSlice(a, "};\n");
    const output = path orelse {
        try std.testing.expectEqualStrings(metal.shaders.manifest.blake3_interaction_source, source.items);
        try std.testing.expectEqualStrings(metal.shaders.manifest.blake3_interaction_inventory, inventory.items);
        return;
    };
    var directory = try std.fs.cwd().makeOpenPath(output, .{});
    defer directory.close();
    try directory.writeFile(.{ .sub_path = "blake3_interactions.metal", .data = source.items });
    try directory.writeFile(.{ .sub_path = "blake3_interactions_exports.zig", .data = inventory.items });
}
