"""Per-track TASK.md generation (TRACKS §8, §9).

One hand-maintained TASK.md cannot describe six tracks: it silently drifts
from the manifest the moment a board's basket, guard portfolio, editable
paths, or era changes. So the per-track brief is *generated* from the
manifest and the epochs ledger — the same documents the runner gates on —
and committed, and the root TASK.md becomes an index over them.

Everything here is a projection of committed contract state. Nothing is
measured, nothing is invented: a field the manifest does not carry is
rendered as an explicit absence, never as a plausible default. Output is
deterministic — no timestamps, no host state, no dict-order dependence — so
`--check` can prove the committed briefs still match their sources.
"""

from __future__ import annotations

from pathlib import Path

from . import ledger
from .manifest import Manifest

TASK_DIR = "autoresearch/tasks"
INDEX_PATH = "autoresearch/TASK.md"

GENERATED_BANNER = (
    "<!-- GENERATED by `stwo-perf task --write` from autoresearch/MANIFEST.json "
    "and autoresearch/ledger/epochs.json. Do not edit by hand: edit the "
    "manifest, then regenerate. -->"
)

OBJECTIVE = (
    "Make the prover faster on this track's scored boundary, on this track's "
    "committed basket, without changing a single proof byte."
)


def brief_path(board: str) -> str:
    return f"{TASK_DIR}/TASK.{board}.md"


def track_boards(manifest: Manifest) -> list[str]:
    """Boards that own a workload group, in ledger.BOARDS order.

    A board with no group has no track to brief; ledger order keeps the index
    stable as boards are appended (they are never removed, TRACKS §6).
    """
    owned = {group.board for group in manifest.groups()}
    return [board for board in ledger.BOARDS if board in owned]


def _era_lines(repo_root: Path, board: str) -> list[str]:
    spec = ledger.current_epoch(repo_root, board=board)
    era = spec.get("era")
    if era is None:
        return [
            f"- **Era**: none declared; the board falls back to global epoch "
            f"`{int(spec['epoch'])}`.",
            f"- **Scored boundary**: `{spec.get('scored_dimension', ledger.DEFAULT_SCORED_DIMENSION)}`",
        ]
    status = era["status"]
    lines = [
        f"- **Era**: {int(era['era'])} (epoch `{int(era['epoch_ref'])}`), "
        f"status `{status}`, opened {era['opened_utc']}",
        f"- **Era opened because**: {era['reason']}",
        f"- **Scored boundary**: `{era['scored_dimension']}`",
    ]
    if status == "banked":
        lines.append(
            f"- **Banked**: this era closed {era['closed_utc']}. Its scores are "
            "final and are never compared with a live track's (TRACKS §6)."
        )
    if era.get("note"):
        lines.append(f"- **Era note**: {era['note']}")
    return lines


def _basket_lines(manifest: Manifest, board: str) -> list[str]:
    group = manifest.group_for_board(board)
    classes = manifest.class_names(
        board=board, scored_only=True, include_disabled=True,
    )
    lines = [
        "| class | workload | unit |",
        "| --- | --- | --- |",
    ]
    for workload in group.workloads:
        if workload.workload_class not in classes:
            continue
        lines.append(
            f"| `{workload.workload_class}` | `{workload.workload_id}` | "
            f"{workload.native_unit} |"
        )
    if len(lines) == 2:
        return ["No scored workload is registered for this board."]
    return lines


def _guard_lines(manifest: Manifest, board: str) -> list[str]:
    group = manifest.group_for_board(board)
    if group.guard_registry is None:
        return [
            "This track binds **no guard registry**: "
            + str(group.guard_registry_absent_reason or "no reason recorded"),
        ]
    registry = manifest.guard_registry(group.group_id)
    workloads = registry.get("workloads", {})
    policy = registry.get("policy", {})
    lines = [
        f"Registry `{group.guard_registry}` — {len(workloads)} guard(s), run on "
        f"this track's own binary (`{group.binary}`). A guard passes when its "
        f"paired upper CI bound stays at or below "
        f"`{policy.get('budget_upper')}`.",
        "",
    ]
    lines += [f"- `{gid}`" for gid in sorted(workloads)]
    rules = registry.get("impact_map", {}).get("rules", [])
    scoped = [
        rule for rule in rules if rule.get("board") in (None, board)
    ]
    if scoped:
        lines += ["", "Impact map (which edits select which guards):", ""]
        lines += ["| editable path prefix | guards |", "| --- | --- |"]
        for rule in scoped:
            selected = rule.get("guards")
            if selected == "all":
                rendered = "all"
            elif not selected:
                rendered = "none"
            else:
                rendered = ", ".join(f"`{g}`" for g in sorted(selected))
            for prefix in rule.get("prefixes", []):
                lines.append(f"| `{prefix}` | {rendered} |")
    lines += [
        "",
        "An editable path that matches no rule selects **every** guard in the "
        "registry (fail closed).",
    ]
    return lines


def _editable_lines(manifest: Manifest, board: str) -> list[str]:
    entries = manifest.editable_for_board(board)
    lines = ["| path | minimum acceptance rung |", "| --- | --- |"]
    for entry in sorted(entries, key=lambda e: e["glob"]):
        lines.append(f"| `{entry['glob']}` | `{entry['min_rung']}` |")
    lines += [
        "",
        "Everything else is out of scope for this track. Frontend sources are "
        "editable **only** by their own track: a Cairo submission may edit "
        "`src/frontends/cairo/**`, and the same edit is an out-of-scope stray "
        "on a native or RISC-V submission (G2 fails).",
        "",
        "Locked paths (never editable by any track): "
        + ", ".join(f"`{glob}`" for glob in manifest.locked),
    ]
    return lines


def _ladder_lines(manifest: Manifest) -> list[str]:
    ladder = manifest.confirmation_ladder
    tiers = ladder.get("tiers", {})
    if not tiers:
        return ["No confirmation ladder is registered in this manifest."]
    lines = ["| tier | cost target | what it buys |", "| --- | --- | --- |"]
    for name in sorted(tiers):
        tier = tiers[name]
        target = tier.get("cost_target_seconds")
        rendered = f"{int(target)} s" if target else "judge-scheduled"
        lines.append(f"| `{name}` | {rendered} | {tier.get('note', '')} |")
    return lines


def _oracle_lines(manifest: Manifest, board: str) -> list[str]:
    group = manifest.group_for_board(board)
    oracle = group.correctness_oracle
    if not oracle:
        return [
            "This track declares no pinned correctness oracle in the manifest."
        ]
    lines = [f"- **Authority**: `{oracle.get('authority')}`"]
    if oracle.get("repository"):
        lines.append(
            f"- **Repository**: {oracle['repository']} @ "
            f"`{oracle.get('commit')}`"
        )
    if oracle.get("performance_peer_repository"):
        lines.append(
            f"- **Performance peer**: {oracle['performance_peer_repository']} @ "
            f"`{oracle.get('performance_peer_commit')}`"
        )
    if oracle.get("rust_toolchain"):
        lines.append(f"- **Peer toolchain**: `{oracle['rust_toolchain']}`")
    if oracle.get("final_validator"):
        lines.append(
            "- The oracle is the **final correctness authority**: a proof it "
            "refuses is not a proof, whatever the harness measured."
        )
    return lines


def _status_lines(manifest: Manifest, board: str) -> list[str]:
    group = manifest.group_for_board(board)
    lines = [
        f"- **Board**: `{board}` · **group**: `{group.group_id}` · "
        f"**report schema**: `{group.report_schema}`",
        f"- **Enabled**: {'yes' if group.enabled else 'no'} · "
        f"**promotion eligible**: "
        f"{'yes' if group.promotion_eligible else 'no'}",
        f"- **Build**: `{group.build_step}` → `{group.binary}`",
    ]
    if not group.enabled and group.disabled_reason:
        lines.append(f"- **Disabled because**: {group.disabled_reason}")
    if group.promotion_blocked_reason:
        lines.append(
            f"- **Promotion blocked because**: {group.promotion_blocked_reason}"
        )
    if group.retirement:
        lines.append(
            f"- **Retired** {group.retirement.get('retired_at_utc')}: "
            f"{group.retirement.get('reason')}"
        )
    return lines


def title_for(manifest: Manifest, board: str) -> str:
    return f"TASK — the `{board}` track"


def render_brief(manifest: Manifest, board: str) -> str:
    """The per-track agent brief, as markdown. Deterministic."""
    group = manifest.group_for_board(board)
    out: list[str] = [
        GENERATED_BANNER,
        "",
        f"# {title_for(manifest, board)}",
        "",
        OBJECTIVE,
        "",
        "This brief is generated from `autoresearch/MANIFEST.json` and "
        "`autoresearch/ledger/epochs.json`. Those documents are the contract; "
        "this file is a view of them. Regenerate with "
        f"`stwo-perf task --board {board}`.",
        "",
        "## Track state",
        "",
        *_status_lines(manifest, board),
        *_era_lines(manifest.root, board),
        "",
        "## Scored basket",
        "",
        *_basket_lines(manifest, board),
        "",
        "Scores are compared only inside one era on one board. A number from "
        "another track, another era, or another boundary is not a comparison "
        "(TRACKS §3, §7).",
        "",
        "## Editable paths for THIS track",
        "",
        *_editable_lines(manifest, board),
        "",
        "## Regression guards",
        "",
        *_guard_lines(manifest, board),
        "",
        "## Correctness oracle",
        "",
        *_oracle_lines(manifest, board),
        "",
        "## Confirmation ladder",
        "",
        *_ladder_lines(manifest),
        "",
        "T0 and T1 never rank; they gate scheduling. The claimed (T2) and "
        "ranked (T3) numbers always keep the full dual boundary — the ranked "
        "number never excludes anything (TRACKS §3.5).",
        "",
        "## Participate",
        "",
        "```sh",
        "stwo-perf clone ../work && cd ../work",
        f"stwo-perf setup --board {board}",
        f"stwo-perf ladder t0 --board {board} --class "
        f"{_first_class(manifest, board)} --phase <phase> --predecessor <tree>",
        f"stwo-perf ladder t1 --board {board} --class "
        f"{_first_class(manifest, board)} --predecessor <tree> --fast-boundary",
        f"stwo-perf run --board {board} --class "
        f"{_first_class(manifest, board)} --predecessor <tree>",
        "stwo-perf submit",
        "```",
        "",
        f"`--board {board}` is explicit above because auto-routing only fires "
        "when the diff names a frontend or backend (TRACKS §8); a diff that "
        "spans two frontends is refused rather than routed.",
        "",
    ]
    if not group.promotion_eligible:
        out += [
            "**This track cannot promote today.** Runs still record evidence, "
            "and the ledger still serves history; no new row is scored until "
            "the manifest says otherwise.",
            "",
        ]
    return "\n".join(out)


def _first_class(manifest: Manifest, board: str) -> str:
    classes = manifest.class_names(
        board=board, scored_only=True, include_disabled=True,
    )
    return classes[0] if classes else "small"


def render_index(manifest: Manifest) -> str:
    """The root TASK.md: an index over the generated per-track briefs."""
    out: list[str] = [
        GENERATED_BANNER,
        "",
        "# TASK — the autoresearch campaign index",
        "",
        "**" + OBJECTIVE + "**",
        "",
        "The campaign is partitioned into tracks (TRACKS §2): one board per "
        "(frontend, backend) pair, each with its own basket, era, guard "
        "portfolio, and editable paths. There is no blended score and no "
        "cross-track comparison — so there is no single task, and this file is "
        "an index rather than a brief.",
        "",
        "Read the brief for the track you are working on. Each is generated "
        "from `autoresearch/MANIFEST.json` and "
        "`autoresearch/ledger/epochs.json`, so it cannot drift from the "
        "contract the runner gates on.",
        "",
        "| track | era | scored boundary | promotion | brief |",
        "| --- | --- | --- | --- | --- |",
    ]
    for board in track_boards(manifest):
        group = manifest.group_for_board(board)
        spec = ledger.current_epoch(manifest.root, board=board)
        era = spec.get("era")
        if era is None:
            era_cell = f"epoch {int(spec['epoch'])}"
            dimension = spec.get(
                "scored_dimension", ledger.DEFAULT_SCORED_DIMENSION
            )
        else:
            era_cell = f"{int(era['era'])} ({era['status']})"
            dimension = era["scored_dimension"]
        promotion = "eligible" if group.promotion_eligible else "blocked"
        if not group.enabled:
            promotion = "staged"
        out.append(
            f"| `{board}` | {era_cell} | `{dimension}` | {promotion} | "
            f"[TASK.{board}.md](tasks/TASK.{board}.md) |"
        )
    out += [
        "",
        "## What every track shares",
        "",
        "- **Proof bytes never change.** Both arms of a paired run must emit "
        "byte-identical proofs; a cross-arm digest mismatch is a conformance "
        "failure, not a slow result.",
        "- **Paired, two-arm, ABBA.** A frozen report is provenance, never a "
        "denominator: `--predecessor <worktree>` is required.",
        "- **Guards are per track.** A track's regression guards run on its own "
        "product binary, selected by the impact map from your diff (TRACKS §8).",
        "- **Editable paths are per track.** A frontend's sources are editable "
        "only by that frontend's track.",
        "- **Local iterate never ranks.** `--guards none` and the T0/T1 ladder "
        "tiers are for your inner loop; ranked rows come only from the judge "
        "path (TRACKS §3.5b).",
        "",
        "Contract documents: [TRACKS.md](TRACKS.md) (the partition and its "
        "reasoning), [MANIFEST.json](MANIFEST.json) (the machine-readable "
        "contract), [README.md](README.md) (harness overview), "
        "[schema/](schema/) (report and feed schemas).",
        "",
    ]
    return "\n".join(out)


def generate(manifest: Manifest) -> dict[str, str]:
    """Every generated document, keyed by repo-relative path. Deterministic."""
    out = {INDEX_PATH: render_index(manifest)}
    for board in track_boards(manifest):
        out[brief_path(board)] = render_brief(manifest, board)
    return out


def write(manifest: Manifest) -> list[str]:
    """Write every generated document; returns the paths that changed."""
    changed = []
    for rel, text in sorted(generate(manifest).items()):
        path = manifest.root / rel
        path.parent.mkdir(parents=True, exist_ok=True)
        if not path.exists() or path.read_text(encoding="utf-8") != text:
            path.write_text(text, encoding="utf-8")
            changed.append(rel)
    return changed


def stale(manifest: Manifest) -> list[str]:
    """Generated documents that no longer match the manifest and epochs."""
    out = []
    for rel, text in sorted(generate(manifest).items()):
        path = manifest.root / rel
        if not path.exists() or path.read_text(encoding="utf-8") != text:
            out.append(rel)
    return out


def feed_export(manifest: Manifest, board: str) -> dict | None:
    """The `boards.<board>.task` feed export (TRACKS §9).

    None for a board with no workload group: there is no track to brief, and a
    placeholder would render as a track that does not exist.
    """
    if board not in track_boards(manifest):
        return None
    return {
        "path": brief_path(board),
        "title": title_for(manifest, board),
        "objective": OBJECTIVE,
        "editable_paths": manifest.editable_for_board(board),
        "markdown": render_brief(manifest, board),
    }
