const std = @import("std");
const core = @import("stwo_core");
const Owner = @import("blake3_poseidon_witness.zig").Owner;
pub fn check(a: std.mem.Allocator, owned: *Owner, elf: []const u8) !void {
    var owner_alive = true;
    defer if (owner_alive) owned.deinit();
    const pool_mod = @import("stwo_prover_engine").work_pool;
    var pool: pool_mod.WorkPool = undefined;
    try pool.initInPlaceWithOptions(.{ .worker_count = 4, .backing_allocator = a });
    defer pool.deinit();
    var binding = try pool_mod.ScopedPoolBinding.init(&pool);
    defer binding.deinit();
    const Api = @import("blake3_poseidon_proof.zig").ForBackend(@import("stwo_cpu_backend").CpuBackend);
    const codec = @import("blake3_poseidon_proof.zig").codec;
    const config = core.pcs.PcsConfig{ .pow_bits = 26, .fri_config = try core.fri.FriConfig.init(0, 1, 70) };
    const prepared = try Api.PreparedVerifier.init(a, &owned.native.statement, owned.statement, try owned.admission(), config);
    defer prepared.deinit();
    const manifest = @import("blake3_poseidon_manifest.zig");
    const source = try @import("blake3_execution_source.zig").validateProfile(.rv32im_zkvm_poseidon2_v1, a, elf, &.{}, &prepared.native.public_data);
    const metadata = try manifest.encode(a, &prepared.native, prepared.extension, prepared.admission(), config, source, .{});
    defer a.free(metadata);
    const statement_id = manifest.identity(metadata);
    const expected = prepared.id;
    var wrong = expected;
    wrong[0] ^= 1;
    try std.testing.expectError(error.UntrustedExecutionKey, Api.prove(a, owned, prepared, wrong, &pool));
    try std.testing.expect(!owned.native.interaction_ready);
    var proved = try Api.prove(a, owned, prepared, expected, &pool);
    defer proved.proof.deinit(a);
    const raw = try codec.encode(a, &proved.proof, prepared, expected);
    defer a.free(raw);
    const artifact = @import("blake3_profile_artifact.zig").ForExecutionProfile(.rv32im_zkvm_poseidon2_v1);
    const published = try artifact.encode(a, &proved.proof, prepared, elf, &.{}, .{});
    defer a.free(published.bytes);
    try std.testing.expectEqualSlices(u8, &statement_id, &published.statement_id);
    owned.deinit();
    owner_alive = false;
    const fresh_digest = try artifact.ForBackend(@import("stwo_cpu_backend").CpuBackend).verify(a, published.bytes, statement_id, config, elf, &.{}, .{});
    try std.testing.expectEqualSlices(u8, &proved.transcript_digest, &fresh_digest);
    var wrong_statement = statement_id;
    wrong_statement[0] ^= 1;
    try std.testing.expectError(error.UntrustedExecutionManifest, artifact.ForBackend(@import("stwo_cpu_backend").CpuBackend).verify(a, published.bytes, wrong_statement, config, elf, &.{}, .{}));
    try std.testing.expectError(error.ExecutionSourceMismatch, artifact.ForBackend(@import("stwo_cpu_backend").CpuBackend).verify(a, published.bytes, statement_id, config, elf, &.{1}, .{}));
    try std.testing.expectError(error.InvalidExecutionArtifactVersion, @import("blake3_profile_artifact.zig").ForProfile(true).split(published.bytes, .{}));
    const fresh = try Api.PreparedVerifier.init(a, &prepared.native, prepared.extension, prepared.admission(), config);
    defer fresh.deinit();
    try std.testing.expectEqualSlices(u8, &expected, &fresh.id);
    var failing = std.testing.FailingAllocator.init(a, .{ .fail_index = 0 });
    try std.testing.expectError(error.UntrustedExecutionKey, codec.decode(failing.allocator(), raw, fresh, wrong));
    try std.testing.expectError(error.InvalidExecutionArtifactLength, codec.decode(failing.allocator(), raw[0 .. raw.len - 1], fresh, expected));
    const first = raw[codec.HEADER_BYTES..][0..4].*;
    std.mem.writeInt(u32, raw[codec.HEADER_BYTES..][0..4], core.fields.m31.Modulus, .little);
    try std.testing.expectError(error.InvalidInteractionClaim, codec.decode(failing.allocator(), raw, fresh, expected));
    @memcpy(raw[codec.HEADER_BYTES..][0..4], &first);
    var decoded = try codec.decode(a, raw, fresh, expected);
    var decoded_alive = true;
    defer if (decoded_alive) decoded.deinit(a);
    const roundtrip = try codec.encode(a, &decoded, fresh, expected);
    defer a.free(roundtrip);
    try std.testing.expectEqualSlices(u8, raw, roundtrip);
    decoded_alive = false;
    var capture = try Api.verifyCaptureOwned(a, decoded, fresh, expected);
    defer capture.deinit();
    try std.testing.expectEqualSlices(u8, &proved.transcript_digest, &capture.final_channel.digestBytes());
    try capture.validate(fresh, expected);
    const draw = capture.extension_draws[0];
    capture.extension_draws[0] = draw.add(core.fields.qm31.QM31.one());
    try std.testing.expectError(error.InvalidExecutionCapture, capture.validate(fresh, expected));
    capture.extension_draws[0] = draw;
    capture.extension_placements[0].main_offset += 1;
    try std.testing.expectError(error.InvalidExecutionCapture, capture.validate(fresh, expected));
    capture.extension_placements[0].main_offset -= 1;
    try capture.validate(fresh, expected);
    std.debug.print("BLAKE3_GUEST_POSEIDON_PROOF verified=true queries=70 pow_bits=26 artifact_bytes={d} witness_released=true fresh_key=true capture_mutations_rejected=true outer_artifact_verified=true source_and_pin_mutations_rejected=true\n", .{raw.len});
}
