//! Symbolically execute the production verifier's LogUp batch finalizer for
//! qm31_ops (two reads, then one write) and Eq (two reads).
//! Export both an isolated zero accumulator and an arbitrary prior
//! accumulator; production adds the component's arithmetic constraints first.
const std = @import("std");
const fields = @import("stwo_core").fields;
const QM31 = fields.qm31.QM31;
const evaluation = @import("stark_verifier/constraint_eval.zig");
const logup = @import("stark_verifier/logup.zig");

const Symbolic = struct {
    allocator: std.mem.Allocator,
    pub const Var = []const u8;

    pub fn zero(_: *const @This()) Var {
        return "0";
    }

    pub fn constant(_: *@This(), value: QM31) !Var {
        if (value.eql(QM31.fromU32Unchecked(0, 1, 0, 0))) return "basisI";
        if (value.eql(QM31.fromU32Unchecked(0, 0, 1, 0))) return "basisU";
        if (value.eql(QM31.fromU32Unchecked(0, 0, 0, 1))) return "basisIU";
        return error.UnexpectedConstant;
    }

    pub fn add(self: *@This(), left: Var, right: Var) !Var {
        return std.fmt.allocPrint(self.allocator, "({s} + {s})", .{ left, right });
    }

    pub fn sub(self: *@This(), left: Var, right: Var) !Var {
        return std.fmt.allocPrint(self.allocator, "({s} - {s})", .{ left, right });
    }

    pub fn mul(self: *@This(), left: Var, right: Var) !Var {
        return std.fmt.allocPrint(self.allocator, "({s} * {s})", .{ left, right });
    }

    pub fn inv(self: *@This(), value: Var) !Var {
        return std.fmt.allocPrint(self.allocator, "({s})⁻¹", .{value});
    }
};

const Data = struct {
    pub fn nInstances(_: @This()) Symbolic.Var {
        return "nInstances";
    }
};

pub fn main() !void {
    var arena = std.heap.ArenaAllocator.init(std.heap.page_allocator);
    defer arena.deinit();
    const allocator = arena.allocator();
    var ctx = Symbolic{ .allocator = allocator };
    var preprocessed: evaluation.ColumnMap(Symbolic.Var) = .empty;
    var public_params: evaluation.ColumnMap(Symbolic.Var) = .empty;
    var acc = evaluation.CompositionConstraintAccumulator(Symbolic).init(
        allocator,
        &ctx,
        &preprocessed,
        &public_params,
        "rho",
        .{ "z", "alpha" },
    );
    defer acc.deinit();
    const terms = [_]logup.LogupTerm(Symbolic.Var){
        .{ .numerator = "a.numerator", .denominator = "a.denominator" },
        .{ .numerator = "b.numerator", .denominator = "b.denominator" },
        .{ .numerator = "c.numerator", .denominator = "c.denominator" },
    };
    for (terms) |term| try acc.terms.append(allocator, term);

    const Column = evaluation.InteractionAtOods(Symbolic.Var);
    const columns = [_]Column{
        .{ .at_oods = "first 0" },                     .{ .at_oods = "first 1" },
        .{ .at_oods = "first 2" },                     .{ .at_oods = "first 3" },
        .{ .at_oods = "last 0", .at_prev = "prev 0" }, .{ .at_oods = "last 1", .at_prev = "prev 1" },
        .{ .at_oods = "last 2", .at_prev = "prev 2" }, .{ .at_oods = "last 3", .at_prev = "prev 3" },
    };
    try acc.finalizeLogupInPairs(&ctx, &columns, Data{}, "claimed");
    var prefixed = evaluation.CompositionConstraintAccumulator(Symbolic).init(
        allocator,
        &ctx,
        &preprocessed,
        &public_params,
        "rho",
        .{ "z", "alpha" },
    );
    defer prefixed.deinit();
    prefixed.accumulation = "prior";
    for (terms) |term| try prefixed.terms.append(allocator, term);
    try prefixed.finalizeLogupInPairs(&ctx, &columns, Data{}, "claimed");
    var equality = evaluation.CompositionConstraintAccumulator(Symbolic).init(
        allocator,
        &ctx,
        &preprocessed,
        &public_params,
        "rho",
        .{ "z", "alpha" },
    );
    defer equality.deinit();
    equality.accumulation = "prior";
    for (terms[0..2]) |term| try equality.terms.append(allocator, term);
    try equality.finalizeLogupInPairs(&ctx, columns[4..], Data{}, "claimed");

    var buffer: [8192]u8 = undefined;
    var stdout = std.fs.File.stdout().writer(&buffer);
    const writer = &stdout.interface;
    try writer.writeAll(
        "import S31.Gadgets.Air.NativeLogUpAir\n\n" ++
            "/-! Generated by executing the native two- and three-term LogUp batch finalizer. -/\n" ++
            "namespace S31.Gadgets.Air.NativeLogUpBatches\n" ++
            "open S31.Gadgets.Air.GateChallenge\n" ++
            "open S31.Gadgets.Air.LogUpInteraction\n\n" ++
            "def basisI : GateSecure := ⟨⟨0, 1⟩, ⟨0, 0⟩⟩\n" ++
            "def basisU : GateSecure := ⟨⟨0, 0⟩, ⟨1, 0⟩⟩\n" ++
            "def basisIU : GateSecure := ⟨⟨0, 0⟩, ⟨0, 1⟩⟩\n\n",
    );
    try writer.print(
        "def threeTermAccumulator (a b c : Term GateSecure)\n" ++
            "    (first prev last : Fin 4 → GateSecure)\n" ++
            "    (rho claimed nInstances : GateSecure) : GateSecure :=\n  {s}\n\n",
        .{acc.finalize()},
    );
    try writer.print(
        "def threeTermWithPrefix (prior : GateSecure) (a b c : Term GateSecure)\n" ++
            "    (first prev last : Fin 4 → GateSecure)\n" ++
            "    (rho claimed nInstances : GateSecure) : GateSecure :=\n  {s}\n\n",
        .{prefixed.finalize()},
    );
    try writer.print(
        "def twoTermWithPrefix (prior : GateSecure) (a b : Term GateSecure)\n" ++
            "    (prev last : Fin 4 → GateSecure)\n" ++
            "    (rho claimed nInstances : GateSecure) : GateSecure :=\n  {s}\n\n",
        .{equality.finalize()},
    );
    try writer.writeAll("end S31.Gadgets.Air.NativeLogUpBatches\n");
    try writer.flush();
}
