//! Run the native LogUp builder formulas over a symbolic string context and
//! print the resulting Lean expressions. The production verifier calls these
//! same functions with its circuit context.
const std = @import("std");
const logup = @import("stark_verifier/logup.zig");

const Symbolic = struct {
    allocator: std.mem.Allocator,
    pub const Var = []const u8;

    pub fn add(self: *@This(), left: Var, right: Var) !Var {
        return std.fmt.allocPrint(self.allocator, "({s} + {s})", .{ left, right });
    }

    pub fn sub(self: *@This(), left: Var, right: Var) !Var {
        return std.fmt.allocPrint(self.allocator, "({s} - {s})", .{ left, right });
    }

    pub fn mul(self: *@This(), left: Var, right: Var) !Var {
        return std.fmt.allocPrint(self.allocator, "({s} * {s})", .{ left, right });
    }
};

pub fn main() !void {
    var arena = std.heap.ArenaAllocator.init(std.heap.page_allocator);
    defer arena.deinit();
    var ctx = Symbolic{ .allocator = arena.allocator() };
    const tuple = [_]Symbolic.Var{
        "tuple 0", "tuple 1", "tuple 2", "tuple 3", "tuple 4", "tuple 5",
    };
    const combine = try logup.combineTerm(Symbolic, &ctx, &tuple, .{ "z", "alpha" });
    const single = try logup.singleLogupConstraint(Symbolic, &ctx, .{ .numerator = "term.numerator", .denominator = "term.denominator" }, "diff");
    const pair = try logup.pairLogupConstraint(Symbolic, &ctx, .{ .numerator = "left.numerator", .denominator = "left.denominator" }, .{ .numerator = "right.numerator", .denominator = "right.denominator" }, "diff");

    var buffer: [4096]u8 = undefined;
    var stdout = std.fs.File.stdout().writer(&buffer);
    const writer = &stdout.interface;
    try writer.writeAll(
        "import S31.Gadgets.Air.LogUpInteraction\n\n" ++
            "/-! Generated by symbolic execution of the native LogUp builder formulas. -/\n" ++
            "namespace S31.Gadgets.Air.NativeLogUpAir\n" ++
            "open S31.Gadgets.Air.GateChallenge\n" ++
            "open S31.Gadgets.Air.LogUpInteraction\n\n",
    );
    try writer.print(
        "def combine (tuple : Fin 6 → GateSecure) (alpha z : GateSecure) : GateSecure :=\n  {s}\n\n",
        .{combine},
    );
    try writer.print(
        "def single (term : Term GateSecure) (diff : GateSecure) : GateSecure :=\n  {s}\n\n",
        .{single},
    );
    try writer.print(
        "def pair (left right : Term GateSecure) (diff : GateSecure) : GateSecure :=\n  {s}\n\n",
        .{pair},
    );
    try writer.writeAll("end S31.Gadgets.Air.NativeLogUpAir\n");
    try writer.flush();
}
